### ISSUE TITLE
Querying PubMed via web returns different results

### ISSUE THREAD

**Issue by reach4bawer** [biopython/biopython#4160] opened 2022-11-14 02:43 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
Results for the above code -

```
3.9.1 (default, Nov 26 2021, 01:39:58) 
[Clang 13.0.0 (clang-1300.0.29.3)]
CPython
macOS-12.6-arm64-arm-64bit
1.79
```

### Expected behaviour

I am trying to search articles on PubMed. I was hoping to get the same articles when searching the website, test out the search terms and then use it via python code. I tried a few libraries but the results are different from the web.

    from Bio import Entrez
    from Bio import Medline
    term = "Cyber Security"
    Entrez.email = "A.N.Other@example.com"  # Replaced for obvious reasons
    handle = Entrez.esearch(db="pubmed", term=term, retmax=5)
    esearch_record = Entrez.read(handle)
    handle.close()
    print(f"Records found: {esearch_record['Count']}")

returns - 

> Records found: 15442
The number of results I was expecting should be 15,045
### Actual behaviour

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/52763317/201563729-9b9d79b7-ee60-4473-807d-99cb18a3a824.png">

### Steps to reproduce

    from Bio import Entrez
    from Bio import Medline
    term = "Cyber Security"
    Entrez.email = "A.N.Other@example.com"  # Replaced for obvious reasons
    handle = Entrez.esearch(db="pubmed", term=term, retmax=5)
    esearch_record = Entrez.read(handle)
    handle.close()
    print(f"Records found: {esearch_record['Count']}")

Please let me know if my understanding is incorrect or if I am doing something wrong.

**Comment by MarkusPiotrowski** [comment] 2022-11-14 08:03
I just did a search with a smaller set of results and can confirm what you reported, just the other way round, I got more results with the web search than when using Biopython (580 vs 545 with the term "nitrilase").
Without knowing the inner details of `Bio.Entrez` I would speculate that the web user interface is using slightly different default settings, but it seems hard to find them.
Maybe you can do a much more stringent search which returns only a handful of articles, and then you can possibly see which articles are different and try to find the reason for this.

**Comment by mdehoon** [comment] 2022-11-15 00:52
See https://stackoverflow.com/questions/16458126/biopython-pubmed-eutils-url for a previous discussion of this issue.

**Comment by reach4bawer** [comment] 2022-11-15 04:39
@MarkusPiotrowski I tried different types of queries. On searching with "Cyber Security" https://pubmed.ncbi.nlm.nih.gov/?term=%22Cyber+security%22 I got 628 results. And I downloaded the list into a text file for the PMIDS. 

I queried the same using the API and used the following code -

 `from Bio import Entrez
from Bio import Medline

term = '"Cyber+Security"[ALL]'

Entrez.email = "A.N.Other@example.com"  # Always tell NCBI who you are
handle = Entrez.esearch(db="pubmed", term=term,datetype="pdat" ,retmax=1000, sort='relevance')
esearch_record = Entrez.read(handle)
handle.close()

print(f"Records found: {esearch_record['Count']}")
all_pmids = esearch_record["IdList"]
Online_list = """36081138
34220596
36337532
34723814
35813991
35591211
32834204
29867661
31634146
32070468
34372354
31872107
34696020
33748750
32971956
34573738
33537477
32226406
34065086
32063872
29609670
35967829
33586204
27730416
33776611
34356419
24457326
35408406
30857581
35178644
33255859
25685516
30510527
35755325
30397993
35214237
24781874
36325843
35591187
36248916
35746411
34577370
33322224
26578272
34797896
32055092
29504488
28058619
33351134
32542864
32837479
32124786
34696125
35190020
34545834
25685517
32993623
31946622
25028059
24701803
24457321
24457325
33192769
26642176
34450915
34833653
34022422
31739400
36015878
27487057
35252852
33247280
35602317
35016746
36300412
26262217
35431600
25517697
17624350
33019270
34587070
33086542
19558397
34007054
34450740
25896029
31338464
28679022
33466335
28366962
26065024
31146589
28264190
31042956
31780540
35808292
20807381
32630182
29601684
35531088
36066559
25751054
34883923
29459838
36169126
33558792
32411955
30307888
31546782
28401507
31201966
33223930
24457327
33693409
27186282
33585823
34637392
33251087
32410530
24457322
27837161
33057091
34640735
28459867
34746516
33235260
34341626
33286602
31355445
26875310
26363788
32834254
33266925
30577633
25685509
29312051
30697023
33918353
32754080
35595974
34502635
35808354
35271163
33612528
34138337
32269778
28328511
32163854
31114676
35611122
35496198
35052322
35756173
30483669
29256383
31575038
30812052
32239357
34280692
32948169
33733105
29713296
31128822
35890784
31361041
31868925
24457323
34917891
32300159
34946379
32455752
30984752
32904653
34595080
31266325
35401030
25209218
33299907
32050004
33748365
34640841
35009609
35205530
35474674
30496581
15192882
32751627
34821613
33375512
31500096
29785204
16948685
34054941
22130338
31203468
34149309
35957478
35506054
33110340
30609820
34577703
33042580
35370392
35036492
34708019
36357220
35062393
26420390
34801981
34112575
35459038
33217936
34549196
35680983
34300556
29308346
35135236
35465441
33719997
32256246
30047886
32885319
34623828
35072058
35746321
36015800
32230946
30136975
32375374
35957440
35720929
33746729
30110442
35606367
35319707
27686221
34339376
31878065
29368749
34577329
32293866
34450707
34517569
36208946
35741495
35684591
35149018
26101280
35957337
33918446
34900233
32549887
34696053
27892599
34671393
36015924
31374902
33919114
30287785
36185135
33913359
35890833
24721764
31013664
30862110
28231323
32270220
33462535
24066046
29783278
32233515
31893637
28588416
34812221
33805841
32570837
35009682
32612551
30571721
34204291
36275843
35161996
35308803
27784829
30452455
35928515
35336322
28635672
33670097
31548492
29894923
30709922
27198089
34070719
33705331
35699779
25552331
31217136
34973345
33960506
32331407
35096507
33635893
33892569
35161725
31098572
28144943
33365367
30463746
36084002
34414352
36124122
33571219
30044837
35765301
35603225
34059850
27443418
31467682
35808161
28384312
32233546
34924898
35408413
34998518
34770390
33036135
34497501
34726529
28833117
31154258
35002668
33198399
34122533
35224514
28657792
34219755
34541582
35684879
32404969
34875409
35240802
34786290
35800924
29350328
33994905
32316556
32322726
28230745
35590922
27330890
34322596
35340686
24948726
33786073
33041735
29791469
35845834
32226110
32283771
36236684
22291569
30621436
35804303
35596153
35730293
29867680
35772072
35430850
34712639
31395538
32824014
32316220
33467692
36320827
32836644
31539791
33816934
32121637
35783847
33816995
29351287
35341272
31211254
34823834
35205596
35128371
33816936
35719987
36261675
31054823
32501313
30463282
35853320
32347465
35886076
33169067
34656885
32706677
32349237
36366214
29081597
35127623
36052028
35591245
29875368
32028053
26918590
30059310
29638153
36359642
35719491
35185304
28577543
35408092
31130644
32768049
29959607
27651127
35898032
35885437
35161958
36255736
35408217
36118433
29700427
35062491
35431613
33047982
33106604
28467505
25478915
36112980
36188111
36107930
27885663
36172314
34192116
27564373
35240825
35209883
32759032
30579241
35336298
35601345
35214295
28468313
31528674
29705947
29355341
27462986
28299796
36236199
28289565
28441331
28629131
36120535
34176603
34430067
35632261
35781036
35201572
23860922
28336797
35746198
30780227
31554171
35634116
32709090
22130342
30149678
35603363
36277015
27967148
27611686
28004287
27893761
28328992
29659508
28150301
29292792
27384239
36366034
27739417
36371967
32288925
36081126
35890988
36319287
35741531
25513824
24578661
28282948
28422084
27704456
27611312
27537890
27792784
27475583
22060334
35126484
34833723
34687614
34682445
33916309
33669191
33286195
32962627
32947915
33062389
35932855
35535197
35345648
35309219
33484133
32708862
32610606
32272801
30844142
29126132
34408917
36236692
35729964
35371238
35125937
34868288
34790960
34300476
32858921
27973618
27855165
36164325
35746176
34901420
34400854
33606574
35782185
32565678
36146347
35990145
35957487
35724477
35668731
35372217
35120175
35096755
33817036
33814730
33564090
32845901
32295298
31945620
29641228
35280109
34776809
33454535
36146271
36080965
35009686
33672196
33466821
30840679
36032183
36016001
35271053
34770672
34312582
34066766
33362458
32271763
32189085
30956623
34341656
34249172
34135009
27653042
35979449
35954350
34795790
31271698
36162198
35685134
34630550
28456512
35161567
31795384
35328404
34152277
27016383
36115103
33395676
33297436
36360286
35626290
34926383
35126487
34803477
32957977
35782180
31888213
35251316
33882019
36236584
35082307
34224147
34043242
33630876
30199520
36015985
35336261
33689823
29321535
30841547
32725140
34236992
35350664
34876778
28558655
31726368
31401235
33499134
32347805
30767906
32554376
29923638
32353827
33683015
34203584"""
pmid_online = Online_list.splitlines()
api_pmid = esearch_record.IdList
all_pmids = list(all_pmids)
list(set(pmid_online).symmetric_difference(set(all_pmids)))`

The result was `['36359642', '36357220', '36366034', '36360286', '36371967', '36366214']` These PMIDs are posted very recently with the exception of '36371967' https://pubmed.ncbi.nlm.nih.gov/36371967/ published in September. 


@mdehoon  not sure if this is helpful but the url generated for my code is  - https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22Cyber%2BSecurity%22%5BALL%5D&datetype=pdat&retmax=1000&sort=relevance&tool=biopython&email=A.N.Other%40example.com

Let me know if I am doing something incorrectly.

**Comment by mdehoon** [comment] 2022-11-15 05:40
@reach4bawer  Now that you have the URL, you can compare it to the URL used when querying PubMed over the web. If it's different, then that explains why you get different results.

Most likely this is not a Biopython issue.

**Comment by MarkusPiotrowski** [comment] 2022-11-15 08:39
@reach4bawer After including the quotes (as you did), I don't see any differences in the number of hits. You get 628 with the manual search on the Web page and also 628 hits when using `Bio.Entrez`. 

Still, there may be a difference when using the NCBI etools or the webpage 'human' interface. E.g. 'Bio.Entrez' gives me 545 hits with the term `nitrilase`:
```
C:\Windows\system32>python3
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on
 win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> Bio.__version__
'1.79'
>>> from Bio import Entrez
>>> term = 'nitrilase'
>>> Entrez.email = 'Markus.Piotrowski@rub.de'
>>> handle = Entrez.esearch(db='pubmed', term=term)
>>> record = Entrez.read(handle)
>>> record['Count']
'545'
>>> term = '"nitrilase"'
>>> handle = Entrez.esearch(db='pubmed', term=term)
>>> record = Entrez.read(handle)
>>> record['Count']
'545'
>>>
```
But the webpage gives 580, obviously because there `nitrilase` is understood as `nitrilase*`:
nitrilase: 580
"nitrilase": 545
nitrilase NOT "nitrilase": 35 (these have only 'nitrilase**s**' in their abstract

**Comment by aCampello** [comment] 2022-11-21 10:43
I can confirm the above for any different terms. For instance:

```python
handle = Entrez.esearch(db="pubmed", retmax=10, term="covid")
record = Entrez.read(handle)
handle.url

print(record['Count'])
```

gives me 308305, whereas the website gives me 309554

**Comment by aCampello** [comment] 2022-11-21 11:11
Doing some investigation, it seems to have to do with the fact that the APIs themselves return different results. E.g.: 

https://www.ncbi.nlm.nih.gov/search/ajax/?db=pubmed&term=covid and https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=covid

produce different results. Any ideas why?

**Comment by peterjc** [comment] 2022-11-21 11:45
Maybe it would fit in the Tutorial, and/or the esearch docstring?

**Comment by aCampello** [comment] 2022-11-21 12:02
Sounds good, I'll give it a shot

**Comment by peterjc** [comment] 2022-11-23 10:18
See https://ncbiinsights.ncbi.nlm.nih.gov/2022/11/22/updated-pubmed-eutilities-live/

**Comment by aCampello** [comment] 2022-11-23 10:56
Let me give it a test

**Comment by aCampello** [comment] 2022-11-23 11:08
I can confirm that with the new API the records match. With the OPs query:

```
from Bio import Entrez
from Bio import Medline
term = "Cyber Security"
Entrez.email = "A.N.Other@example.com"  # Replaced for obvious reasons
handle = Entrez.esearch(db="pubmed", term=term, retmax=5)
esearch_record = Entrez.read(handle)
handle.close()
print(f"Records found: {esearch_record['Count']}")
```

I get `15086` hits, the same as the web UI

![Screenshot 2022-11-23 at 11 07 54](https://user-images.githubusercontent.com/27929341/203531898-47fdc074-b04a-4a21-947e-2c68535d18e3.png)

**Comment by aCampello** [comment] 2022-11-23 11:08
Shall we close @peterjc ?

**Comment by peterjc** [comment] 2022-11-23 11:35
Thanks for checking - with the NCBI's work updating the Entrez API to match the PubMed website again, I agree we can close this.

**Closed by peterjc** 2022-11-23 11:35 UTC
