### ISSUE TITLE
SeqIO.read() fails parsing genbank formated file from NCBI with extraneous comment lines

### ISSUE THREAD

**Issue by santirdnd** [biopython/biopython#1273] opened 2017-06-09 09:30 UTC
Sequences NZ_CP015967.1 and NZ_CP015968.1 have these kind of lines on COMMENT section:

`            StructuredCommentPrefix###Genome-Assembly-Data-START## Assembly`
`            Method#HGAP v. 2.3.0 Genome Coverage#83.43x Sequencing`
`            Technology#PacBio.`

followed by the real `##Genome-Assembly-Data-START##` section and, certainly, deleting them fix the problem.

Obviously, this should be better dealed on NCBI side but, perhaps, there is an easy way to modify the parser.

**Comment by peterjc** [comment] 2017-06-09 09:36
Which version of Biopython are you using?

```python
>>> import Bio
>>> print(Bio.__version__)
```

How *exactly* did you download NZ_CP015967.1 and NZ_CP015968.1 from the NCBI? Do you have the exactly FTP or HTTP URL? I'm asking because on their website in particular there are multiple options which affect the data returned.

**Comment by santirdnd** [comment] 2017-06-09 19:41
Ughh, sorry! It was with 1.68 from anaconda. I have just realised there is a new version released and now I can't reproduce it.

Again, sorry for the noise.

**Comment by peterjc** [comment] 2017-06-10 23:37
Thanks for the additional information - my guess is this was a duplicate of #951 which was fixed in Biopython 1.69.

Since updating your Biopython fixed this, I'm going to close this issue. Cheers.

**Closed by peterjc** 2017-06-10 23:37 UTC
