### ISSUE TITLE
HMMER Parser doesn't work with Windows

### ISSUE THREAD

**Issue by jou-schrodinger** [biopython/biopython#4361] opened 2023-07-18 01:25 UTC
The regex defined here:

https://github.com/krdav/ANARCI_KD_copy/blob/5c4a17f6f0bc530b3e5154667e285eea1195a485/lib/python/anarci/Bio/SearchIO/HmmerIO/hmmer3_text.py#L24

Is unable to find any matches in this output banner from hmmscan:

'# C:\\msys64\\scr\\jou\\builds\\22-2\\build\\thirdparty\\bin\\Windows-x64\\hmmer\\bin\\hmmscan :: search sequence(s) against a profile database\n'

and as a result

https://github.com/biopython/biopython/blob/9965ece1d76adc8ee65904f87ea68c0b1206050a/Bio/SearchIO/HmmerIO/hmmer3_text.py#L20

Sometimes leaves query_start, query_end, hit_start, and hit_end as None. It's worse than assigning without correction, and should really be an error, or handled gracefully with its current downstream warning.

**Comment by JoaoRodrigues** [comment] 2023-07-18 03:02
Hi Jonathan,

Could you provide us with a sample input we can reproduce the problem with?

Cheers,

João

A segunda, 17/07/2023, 21:26, Jonathan Jou ***@***.***>
escreveu:

**Comment by peterjc** [comment] 2023-07-18 10:07
It sounds like this input file has a full path to the hmmscan binary (a Windows path starting C:) but the regular expression in the parser is expecting just ``hmmscan`` alone. If so, this _might_ also break on Linux or macOS too if used with an explicit path to the binary?

But yes, a small sample output file would be useful. And if @bow thought it useful, ideally a test case we could add to Biopython's test suite.

**Comment by bow** [comment] 2023-07-18 10:50
Thanks for reporting this @jou-schrodinger.

Out of curiosity, can I ask how you did you execute `hmmscan`? Was `hmmscan` already in your `PATH` or did you have to refer to its absolute path as shown here?

Either way, seconding @JoaoRodrigues and @peterjc ~ we'd appreciate it if you have an example output. And with your permission, we might like to include it in our test suite :slightly_smiling_face:.

**Comment by byerlyj** [comment] 2023-10-26 14:34
I've been working with @jou-schrodinger on this issue -- I've attached an hmmscan result file that reproduces this issue:
[6fr3_hmmscan_space_in_path.txt](https://github.com/biopython/biopython/files/13178955/6fr3_hmmscan_space_in_path.txt)

In this case, anarci was running hmmer with the following arguments:
```
['C:\\msys64\\scr\\byerly\\builds\\NB\\20231025 _\\thirdparty\\bin\\Windows-x64\\hmmer\\bin\\hmmscan', '-o', 'C:\\Users\\byerly\\AppData\\Local\\Temp\\tmpkslp61l0.txt', 'C:\\msys64\\scr\\byerly\\builds\\NB\\20231025 _\\internal\\lib\\site-packages\\anarci\\dat\\HMMs\\ALL.hmm', 'C:\\Users\\byerly\\AppData\\Local\\Temp\\tmpn5zlrimi.fasta']
```

**Comment by peterjc** [comment] 2023-10-26 15:38
So yes, surprisingly you do indeed appear to have a space in the path to ``hmmscan``, very odd:

``C:\msys64\scr\byerly\builds\NB\20231025 _\thirdparty\bin\Windows-x64\hmmer\bin\hmmscan``

This looks like an accident perhaps, why have the "date space underscore" as a folder name? But in general I would recommend avoiding using any file or folder as it makes life harder (extra steps to escape or quote paths), and sometimes leads to bugs where other people's code has not handled this.

@bow is this enough info for you to try to fix this?

**Comment by byerlyj** [comment] 2023-10-26 16:09
yeah, this can happen if someone has a python installation in a nonstandard place, e.g. "Program Files" on Windows. The inclusion of a space is deliberate to make sure my testing is thorough.

I have a fix for this almost ready, just preparing a pull request now. I'm not super familiar with GitHub so it may take a little while!

**Comment by bow** [comment] 2023-10-26 16:31
@peterjc That should be enough for a PR ~ looks like @byerlyj has it under control :slightly_smiling_face:. Let us know if you need any help and feel free to ping me for the MR review.

**Closed** 2023-10-28 15:36 UTC
