### ISSUE TITLE
Bio.SearchIO could only parse the first query record in blast-tab file

### ISSUE THREAD

**Issue by wpwupingwp** [biopython/biopython#1598] opened 2018-04-05 07:33 UTC
### Setup

Python: 3.6.5rc1 (default, Mar 14 2018, 06:54:23) \n[GCC 7.3.0]
Platform: Linux-4.9.0-3-amd64-x86_64-with-debian-buster-sid
Biopython: 1.70
BLAST: 2.7.1

### Steps to reproduce
blast.xml:
`blastn -query a.fasta -db db -outfmt 5 -max_target_seqs 1 -max_hsps 1 > blast.xml`
blast.tab:
`blastn -query a.fasta -db db -outfmt 5 -max_target_seqs 1 -max_hsps 1 > blast.tab`
**_edit:_**
**`blastn -query a.fasta -db db -outfmt 7 -max_target_seqs 1 -max_hsps 1 > blast.tab`**
Two files comes from same query and db, only different in format. Bio.SearchIO.parse(file, 'blast-tab') could only parse the first query in blast-tab file, other querys were skipped. 
Bio.SearchIO.parse(file, 'blast-xml') is fine.

[blast.zip](https://github.com/biopython/biopython/files/1878921/blast.zip)

I tested in several different input data and the results are same. Here is a simple test.
```
#!/usr/bin/python3

from Bio import SearchIO

a = SearchIO.parse('./blast.tab', 'blast-tab')
print(len(list(a)))
b = SearchIO.parse('./blast.xml', 'blast-xml')
print(len(list(b)))

```

**Comment by peterjc** [comment] 2018-04-05 08:55
We released Biopython 1.71 this week, so if possible could you retest with that?

Also there is a typo on your steps to reproduce - both lines use ``-outfmt 5`` which is XML. It looks like you probably used ``-outfmt 7`` for commented tab separated:

```
# BLASTN 2.7.1+
# Query: ndhA.1_ndhA.2|Poales|Poaceae|Oryza|meyeriana_var._granulata|DQ289169|
# Database: db
# Fields: query acc.ver, subject acc.ver, % identity, alignment length, mismatches, gap opens, q. start, q. end, s. start, s. end, evalue, bit score
# 1 hits found
ndhA.1_ndhA.2|Poales|Poaceae|Oryza|meyeriana_var._granulata|DQ289169|   ndhA.1_ndhA.2|Poales|Poaceae|Oryza|meyeriana_var._granulata|DQ289169|   100.000 970     0       0
       1       970     1       970     0.0     1792
# BLASTN 2.7.1+
# Query: _R_ndhA.2_ndhA.1|Poales|Poaceae|Oryza|meyeriana|NC_034765|
# Database: db
# Fields: query acc.ver, subject acc.ver, % identity, alignment length, mismatches, gap opens, q. start, q. end, s. start, s. end, evalue, bit score
# 1 hits found
_R_ndhA.2_ndhA.1|Poales|Poaceae|Oryza|meyeriana|NC_034765|      _R_ndhA.2_ndhA.1|Poales|Poaceae|Oryza|meyeriana|NC_034765|      100.000 970     0       0       1       970     1       970     0.0     1792
...
```

**Comment by wpwupingwp** [comment] 2018-04-05 09:10
Thanks for reminding typo.
Biopython 1.71 test:
```
#!/usr/bin/python3

from Bio import SearchIO
from Bio import __version__

print(__version__)
a = SearchIO.parse('./blast.tab', 'blast-tab')
print(len(list(a)))
b = SearchIO.parse('./blast.xml', 'blast-xml')
print(len(list(b)))

```

Result:
```
/usr/local/lib/python3.6/dist-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
1.71
1
298

```

**Comment by bow** [comment] 2018-04-05 11:59
@wpwupingwp This is related to my latest comment in #1591. In this case, you would get the correct result by adding `comments=True`. So instead of:

```
a = SearchIO.parse('./blast.tab', 'blast-tab')
```

You should do:
```
a = SearchIO.parse('./blast.tab', 'blast-tab', comments=True)
```

Perhaps I should also have pointed the official documentation earlier, [specifically the `blast-tab` part](http://biopython.org/DIST/docs/api/Bio.SearchIO.BlastIO-pysrc.html). To quote it here:

> The default format for blast-tab support is the variant without comments (-m 6 flag). Commented BLAST tabular files may be parsed, indexed, or written  the keyword argument 'comments' set to True

**Comment by peterjc** [comment] 2018-04-05 12:53
This seems like a bug then, if ``SearchIO.parse('./blast.tab', 'blast-tab')`` handles commented files badly. It should either given an exception, or cope (e.g. by ignoring the comment lines).

**Comment by bow** [comment] 2018-04-05 13:11
Hmm..

How about adding a simple `if self.line.startswith("#")` [somewhere around here](https://github.com/biopython/biopython/blob/master/Bio/SearchIO/BlastIO/blast_tab.py#L218) and then raising a `ValueError` if that evaluates to `True` but `comments` is `False`?

The catch here is that we assume that the values of the first column must not begin with `#` (i.e. `#` is a reserved character that determines whether a file is of the commented variant or not). On the other hand though, [we are already doing this anyway](https://github.com/biopython/biopython/blob/master/Bio/SearchIO/BlastIO/blast_tab.py#L389), so this looks ok.

**Comment by peterjc** [comment] 2018-04-05 13:14
That would be an improvement.

How easy would it be to deprecate then remove the ``comments=`` argument, and simply infer this from the data?

**Comment by bow** [comment] 2018-04-05 13:31
I think relatively trivial. I changed the attribute assignment order in [the `__init__` function](https://github.com/biopython/biopython/blob/master/Bio/SearchIO/BlastIO/blast_tab.py#L204) after adding `self.has_comments = self.line.startswith("#")` and all our tests still pass. I should still check if there are corner cases that are not yet covered, just to be sure.

Having said that, the reason `comments` was added as a keyword argument was related more to `SearchIO` asking the user to be as explicit as possible when specifying file formats (inherently, how the file should be parse). Since we do not try to infer file formats magically, the way the tabular + commented file is specified should also be explicit.

**Comment by peterjc** [comment] 2018-04-05 15:32
This boils down to do we regard ``-outfmt 6`` tabular and ``-outfmt 7`` commented tabular as different formats, or variants of the same basic format. There are arguments either way.

I'd be happy if the example would raise an exception saying use ``commented=True``.

**Comment by bow** [comment] 2018-04-05 18:14
Ok then. I've opened PR #1602. Let's continue the discussion there.

**Comment by peterjc** [comment] 2018-04-06 09:38
I've merged #1602, so this example should now give an error recommending using ``comments=True``. Does this solve the issue for you @wpwupingwp?

**Comment by wpwupingwp** [comment] 2018-04-06 14:03
Thank you. It did solve the problem. However, here is another question:

blast.xml:
`blastn -query a.fasta -db db -outfmt 5 -max_target_seqs 1 -max_hsps 1 > blast.xml`
blast.tab.6:
`blastn -query a.fasta -db db -outfmt 6 -max_target_seqs 1 -max_hsps 1 > blast.tab.6`
blast.tab.7:
`blastn -query a.fasta -db db -outfmt 7 -max_target_seqs 1 -max_hsps 1 > blast.tab.7`
Same query and db used. The size:
`wc -l blast*`
```
112289 blast.tab.6
113780 blast.tab.7
  14030 blast.xml
```
Test code:
```
#!/usr/bin/python3

from Bio import SearchIO
from Bio import __version__


@profile
def main():
    print(__version__)
    a = SearchIO.parse('./blast.tab.6', 'blast-tab')
    print('outfmt 6:', len(list(a)))
    b = SearchIO.parse('./blast.tab.7', 'blast-tab', comments=True)
    print('outfmt 7:', len(list(b)))
    c = SearchIO.parse('./blast.xml', 'blast-xml')
    print('outfmt 5:', len(list(c)))


if __name__ == '__main__':
    main()

```

Output is fine:

```
/usr/local/lib/python3.6/dist-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
1.71.dev0
outfmt 6: 298
outfmt 6: 298
outfmt 5: 298
Wrote profile results to test.py.lprof

```

And here is the line_profiler result:
```
Timer unit: 1e-06 s

Total time: 103.649 s
File: test.py
Function: main at line 7

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     7                                           @profile
     8                                           def main():
     9         1         21.0     21.0      0.0      print(__version__)
    10         1          3.0      3.0      0.0      a = SearchIO.parse('./blast.tab.6', 'blast-tab')
    11         1   52188454.0 52188454.0     50.4      print('outfmt 6:', len(list(a)))
    12         1         10.0     10.0      0.0      b = SearchIO.parse('./blast.tab.7', 'blast-tab', comments=True)
    13         1   51190663.0 51190663.0     49.4      print('outfmt 7:', len(list(b)))
    14         1          9.0      9.0      0.0      c = SearchIO.parse('./blast.xml', 'blast-xml')
    15         1     269690.0 269690.0      0.3      print('outfmt 5:', len(list(c)))


```
Parsing blast-tab is about **_200x_** slower than parsing blast-xml. Although they do differ from file size, I think a tsv file rarely use such long time to parse. Is this performance ok?

P.S.: I know that line_profiler could slow down the running. So I also tried to use `timeit.default_timer`, get similar result, that parsing blast-tab file use 18 second compare with 0.1 second used by parsing blast-xml file.

P.P.S: I also worried about if it's my harddisk's problem. So I copy data files and code into ramdisk (tmpfs in Linux). I got same result, too.

**Comment by peterjc** [comment] 2018-04-06 14:07
If I am reading this right, the tabular files are about 10 times bigger than the XML file, so from a disk IO point of view, you would expect parsing them to be about 10 times slower. But this is much worse. Can you open a new issue on this please (copy and paste that comment), and we'll close the original issue as resolved.

**Closed by peterjc** 2018-04-06 14:07 UTC
