### ISSUE TITLE
Bug: `Bio.PDB.ResidueDepth.get_surface` runs forever with a likely corrupted PDB file

### ISSUE THREAD

**Issue by gcroci2** [biopython/biopython#4231] opened 2023-02-10 12:33 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
[GCC 11.2.0]
CPython
Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28
1.80
```

### Expected behaviour

When running `Bio.PDB.ResidueDepth.get_surface` with a wrong/corrupted PDB file, the code should raise an error.

### Actual behaviour

With the PDB file attached (first unzip it), `Bio.PDB.ResidueDepth.get_surface` function never stops running, and doesn't raise any errors. We'll investigate the PDB file to see which problems are there, but this shouldn't be happening. 

### Steps to reproduce

```python
from Bio.PDB.PDBParser import PDBParser
from Bio.PDB.ResidueDepth import get_surface
pdb_path = "my_file.pdb"
parser = PDBParser()
structure = parser.get_structure('_tmp', pdb_path)
bio_model = structure[0]
surface = get_surface(bio_model)
```

[my_file.pdb.zip](https://github.com/biopython/biopython/files/10707340/my_file.pdb.zip)

**Comment by JoaoRodrigues** [comment] 2023-02-10 18:20
Hi @gcroci2, thanks for the report. Seems like the issue is with running MSMS on this particular PDB file. Our parser also doesn't throw any warnings - why would you say the file is corrupted?

**Comment by rob-miller** [comment] 2023-02-11 17:26
Seems like it shouldn't matter and is probably allowed in the spec, but all
of the sidechains are in the middle of the backbones:

```
ATOM   1553  N   THR P   4       4.932  -1.246   0.353  1.00125.36
  N
ATOM   1554  CA  THR P   4       4.259  -2.135  -0.542  1.00125.36
  C
ATOM   1555  CB  THR P   4       5.029  -3.410  -0.746  1.00125.36
  C
ATOM   1556  OG1 THR P   4       5.169  -4.115   0.481  1.00125.36
  O
ATOM   1557  CG2 THR P   4       6.416  -3.027  -1.294  1.00125.36
  C
ATOM   1558  C   THR P   4       2.931  -2.436   0.087  1.00125.36
  C
ATOM   1559  O   THR P   4       2.669  -3.546   0.550  1.00125.36
  O
```

instead of:

```
ATOM     40  N   THR A   3      21.061  26.200   2.373  1.00 11.69
  N
ATOM     41  CA  THR A   3      22.444  26.745   2.238  1.00 12.47
  C
ATOM     42  C   THR A   3      23.424  25.749   2.981  1.00 11.52
  C
ATOM     43  O   THR A   3      23.051  24.967   3.783  1.00 11.28
  O
ATOM     44  CB  THR A   3      22.587  28.143   2.780  1.00 13.91
  C
ATOM     45  OG1 THR A   3      22.446  28.038   4.208  1.00 14.71
  O
ATOM     46  CG2 THR A   3      21.610  29.180   2.206  1.00 14.39
  C
```

**Comment by JoaoRodrigues** [comment] 2023-02-12 18:49
Good point @rob-miller , but unfortunately not the case. Even with the atoms sorted properly, MSMS still hangs.

I bisected the file until msms works, turns out there's a single atom that it causing problems: `ATOM   1252  OE2 GLU M 155      -3.669  -7.061  13.230  1.00 41.57           O`. If you delete it, then everything works. Now why that is the case, no idea, but I'll close this as an issue with MSMS itself, not our wrapper.

In the future though, we should maybe look into supporting other tools to compute the SES.

**Closed by JoaoRodrigues** 2023-02-12 18:49 UTC
