### ISSUE TITLE
Is there a way to get GC SS_cons from an alignment in the Stockholm format?

### ISSUE THREAD

**Issue by mmagnus** [biopython/biopython#1066] opened 2017-02-22 18:56 UTC
```
# STOCKHOLM 1.0
#=GC SS_cons       .................<<<<<<<<...<<<<<<<........>>>>>>>..
AP001509.1         UUAAUCGAGCUCAACACUCUUCGUAUAUCCUC-UCAAUAUGG-GAUGAGGGU
#=GR AP001509.1 SS -----------------<<<<<<<<---..<<-<<-------->>->>..--
AE007476.1         AAAAUUGAAUAUCGUUUUACUUGUUUAU-GUCGUGAAU-UGG-CACGA-CGU
#=GR AE007476.1 SS -----------------<<<<<<<<-----<<.<<-------->>.>>----
```

i would like to get the first line? If there is no way how to do it, is there any problem to do it? I could do it but is it breaking something else? 

(I'm new to Biopython development, but I'd love to contribute).

**Comment by peterjc** [comment] 2017-02-23 10:27
Right now you can't, sorry. Closing as a duplicate of #357.

There are a few bits of code looking at doing this, e.g. #528 and #769, fresh eyes on  this would be good if you're interested in helping.

**Closed by peterjc** 2017-02-23 10:27 UTC
