### ISSUE TITLE
test_PDB_DSSP failure with mmcif_chain_dict[chain_id] KeyError: 'E'

### ISSUE THREAD

**Issue by emollier** [biopython/biopython#3763] opened 2021-10-13 19:55 UTC
Greetings,

When trying to upgrade the _python-biopython_ package to version 1.79 in Debian Sid, I'm getting the following unit test error:

```
======================================================================
ERROR: test_dssp_with_mmcif_file_and_different_chain_ids (test_PDB_DSSP.DSSP_tool_test)
Test DSSP generation from MMCIF which has different label and author chain IDs.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9/build/Tests/test_PDB_DSSP.py", line 125, in test_dssp_with_mmcif_file_and_different_chain_ids
    dssp = DSSP(model, pdbfile)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9/build/Bio/PDB/DSSP.py", line 476, in __init__
    chain_id = mmcif_chain_dict[chain_id]
KeyError: 'E'
```

It turns out that the _KeyError_ occurs a couple of lines before the _try: except KeyError:_ statement which, I suppose, is the object of the test.  Note that this occurs with the patch mentionned in the [issue #3433](https://github.com/biopython/biopython/issues/3433), in order to work around the issue caused by the new default file format, so there is a good chance this is a self inflicted breakage.  If need be, you can refer to the [full log on Salsa CI](https://salsa.debian.org/med-team/python-biopython/-/jobs/2061317/raw), on which I added a couple of _print_ in the loop, in an attempt to understand what happens.

Core components versions are:

```
>>> import sys; print(sys.version)
3.9.7 (default, Sep 24 2021, 09:43:00)
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.14.0-1-amd64-x86_64-with-glibc2.32
```

Current versions of _mkdssp_ and _libcifpp_ available in Sid are:

```
$ mkdssp --version
mkdssp version 4.0.0 2020-12-18
$ dpkg -l | grep libcifpp
ii  libcifpp1  1.0.1-3  amd64  Library files for libcifpp
```

Kind Regards,
Étienne.

**Comment by peterjc** [comment] 2021-10-15 11:55
I think we can close this issue as a duplicate of #3433, not yet supporting DSSP v4. But the test failure is worth knowing about.

**Comment by emollier** [comment] 2021-10-16 14:27
Hi Peter,

Yes, I thought it would be better that you'd be aware of the issue.  Please feel free to sort the bug entry in the way you think is the most sensible; I was a bit unsure of the channel to use to be honest.

For information, I uploaded to Experimental with the following workaround to skip the test, in case the _mkdssp_ version is too recent:
```
--- python-biopython.orig/Tests/test_PDB_DSSP.py
+++ python-biopython/Tests/test_PDB_DSSP.py
@@ -117,8 +117,8 @@
 
     def test_dssp_with_mmcif_file_and_different_chain_ids(self):
         """Test DSSP generation from MMCIF which has different label and author chain IDs."""
-        if self.dssp_version < StrictVersion("2.2.0"):
-            self.skipTest("Test requires DSSP version 2.2.0 or greater")
+        if self.dssp_version < StrictVersion("2.2.0") or self.dssp_version >= StrictVersion("4.0.0"):
+            self.skipTest("Test requires DSSP version between 2.2.0 and 4.0.0.")
 
         pdbfile = "PDB/1A7G.cif"
         model = self.cifparser.get_structure("1A7G", pdbfile)[0]
```

As usual, Thanks for your time!

Have a nice day,  :)
Étienne.

**Closed** 2022-08-07 02:46 UTC
