### ISSUE TITLE
QueryResult object from Bio.SearchIO is not picklable

### ISSUE THREAD

**Issue by docmanny** [biopython/biopython#1241] opened 2017-05-18 17:33 UTC
Hello all,

I first encountered this issue when trying to adapt script running BLAST analysis in parallel to use BLAT and SearchIO:
```
File "/usr/lib64/python3.4/multiprocessing/queues.py", line 247, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib64/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function QueryResult.<lambda> at 0x7f4bcc2f0bf8>: attribute lookup <lambda> on Bio.SearchIO._model.query failed
```
After confirming that the rest of my code was free of lambdas, I was able to conclude that the error was intrinsic to the QueryResults object, and was able to generate a minimal reproducible example:
```
from Bio import SearchIO
# Note that it doesn't matter what the input file selected is; 
# I tried psl, pslx, and blast8 formats
record = SearchIO.read('./blatx_test.psl', 'blat-psl')
import pickle
with open('./test.pickle', 'w') as testpickle:
    pickle.dump(record, testpickle)
```
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
_pickle.PicklingError: Can't pickle <function QueryResult.<lambda> at 0x7f1a3667c1e0>: attribute lookup <lambda> on Bio.SearchIO._model.query failed
```
From what I can see in the source code, I suspect that the offending line is in the def__init__() in Bio.SearchIO._model.query: `def __init__(self, hits=(), id=None, hit_key_function=lambda hit: hit.id):`

The inability to pickle QueryResults objects means that SearchIO cannot be easily used in multiproccessing-or-pickling-based scripts. Is this something that could be fixed in Bio.SearchIO, or is the presence of lambda functions in the class something that must be worked around?

**Comment by peterjc** [comment] 2017-05-18 17:35
Probably we should do:

```python
def __init__(self, hits=(), id=None, hit_key_function=None):
    ...
    if  hit_key_function is None:
       hit_key_function=lambda hit: hit.id
    ...
```

Better yet, define the this as a private function once at module level?

**Comment by bow** [comment] 2017-05-18 21:38
Ah indeed, the closure makes the object unplickable. @peterjc , I think we should go with not using lambda at all (so private function is an option). How about making it a private staticmethod of the class? Just to avoid cluttering the module namespace, even as a private function.

Anyway, I'll open a PR soon.

**Comment by bow** [comment] 2017-05-18 21:44
@docmanny , thanks again by the way for reporting the issue (with a bit of a detective work on your end which makes it easier to write the fix :) ). I've just opened a PR to address this, which should already be visible to you.

**Comment by docmanny** [comment] 2017-06-01 18:50
Sorry it took me so long to get around to checking this. There's now an error when Pickle tries to look-up _hit_key_function:
```
>>> from Bio import SearchIO
>>> # Note that it doesn't matter what the input file selected is; 
>>> # I tried psl, pslx, and blast8 formats
>>> record = SearchIO.read('./blatx_test.psl', 'blat-psl')
>>> import pickle
>>> with open('./test.pickle', 'w') as testpickle:
>>>     pickle.dump(record, testpickle)
>>> 
    
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-efa2f9be86af>", line 7, in <module>
    pickle.dump(record, testpickle)
_pickle.PicklingError: Can't pickle <function QueryResult._hit_key_func at 0x7f860a71cd90>: attribute lookup _hit_key_func on Bio.SearchIO._model.query failed
```

**Comment by bow** [comment] 2017-06-01 19:23
Hi @docmanny ,

This seems to be related to the Python version. I could reproduce this locally in Python 3.4, but it works in Python 3.5 (Changelog [here](https://docs.python.org/3/whatsnew/3.5.html#pickle)).

I'm not sure how to make this works for versions 3.4 or before (without applying too big of a hack). Is it an option for you to switch to Python 3.5?

**Comment by peterjc** [comment] 2017-06-02 09:12
Given the Python 3 release notes talk about nested functions, my guess is we can fix this by moving the static class method:

```python
class QueryResult(_BaseSearchObject):

...

    # Default function for hit_key_function argument in QueryResult.__init__
    @staticmethod
    def _hit_key_func(hit):
        return hit.id
```

into a self-contain top level module function:

```python
def _hit_key_func(hit):
    return hit.id
```

**Comment by docmanny** [comment] 2017-06-08 19:22
@bow I see... I'll make a new env with Python 3.5+ for future testing. Regarding Python 3.4, however, one fix that works well is to either use `dill` instead of `pickle` when explicitly pickling functions, or in the case of parallelizing code, using `multiprocess` rather than `multiprocessing`, which is a fork that uses `dill` internally.

**Comment by bow** [comment] 2017-06-09 09:19
@docmanny Thank you for the tip ~ that is certainly possible. @peterjc is also right that we can move the offending function to a top-level function so that it is pickle-able. I've added now some tests to ensure that we catch any pickle-related errors from now on.

I will close this issue when [this PR](https://github.com/biopython/biopython/pull/1272) is merged.

**Comment by bow** [comment] 2017-06-09 19:05
Ok, the PR is merged ~ you should be able to work on this using the regular pickle in Python < 3.5 @docmanny. Feel free to reopen this if you stumble on any pickling-failures.

**Closed by bow** 2017-06-09 19:05 UTC
Labels: Enhancement
