### ISSUE TITLE
misspelled "coment" in NewickIO.py line 87

### ISSUE THREAD

**Issue by wrpearson** [biopython/biopython#3436] opened 2020-12-07 21:06 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
>>> 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
>>> CPython
Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
>>> import Bio; print(Bio.__version__)
1.78

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

Newick.IO does not properly print out "comments" associated with Clades

The problem is here:  (NewickIO.py):

```
def _get_comment(clade):
    try:
        comment = clade.coment
    except AttributeError:
        pass
    else:
        if comment:
            return _format_comment(str(comment))
    return ""
```

`clade.coment` is mis-spelled in the try: statement.  It should be:

```
def _get_comment(clade):
    try:
        comment = clade.comment
    except AttributeError:
        pass
    else:
        if comment:
            return _format_comment(str(comment))
    return ""
```

**Comment by peterjc** [comment] 2020-12-07 21:31
Thanks for reporting. Good news - this is a duplicate of #3361, fixed recently in #3366.

I hope we'll do the next release later this month (Dec 2020), if not early Jan 2021.

**Closed by peterjc** 2020-12-07 21:31 UTC
