### ISSUE TITLE
Bad XML in Entrez should raise CorruptedXMLError

### ISSUE THREAD

**Issue by xapple** [biopython/biopython#594] opened 2015-08-09 14:26 UTC
Consider the following example:

    from Bio import Entrez
    import cStringIO
    bad_xml = """<?xml version="1.0"?>
    <!DOCTYPE GBSet PUBLIC "-//NCBI//NCBI GBSeq/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_GBSeq.dtd">
    <GBSet><GBSeq><GBSeq_locus>
    """
    bad = cStringIO.StringIO()
    bad.write(bad_xml)
    bad.seek(0)
    bad_records = list(Entrez.parse(bad, validate=True))

It produces the following error:

    /Users/me/Library/Python/2.7/lib/python/site-packages/Bio/Entrez/Parser.pyc in parse(self, handle)
        235                     # No more XML data, but there is still some unfinished
        236                     # business
    --> 237                     raise CorruptedXMLError
        238                 try:
        239                     for record in self.object:

    TypeError: __init__() takes exactly 2 arguments (1 given)

I think that's a bug !

**Comment by peterjc** [comment] 2015-08-10 08:35
Your example is supplying a partial XML fragment, which is not a valid XML document and would fail validation. It *should* give an error, this is a feature of XML not a bug. 

But yes, the TypeError is a mistake, we should be doing something like this:

```
raise CorruptedXMLError("Incomplete XML file?")
```

**Comment by xapple** [comment] 2015-08-10 08:38
Obviously the XML is bad, that's why it's in a variable called `bad_xml`, but you still have a bad bug. My `except Bio.Entrez.Parser.CorruptedXMLError` block wasn't working anymore and my script that was supposed to run for 100+ hours stopped. Of course I could just do a `except TypeError` now.

**Comment by peterjc** [comment] 2015-08-10 08:42
Without the current bug title, it wasn't 100% clear what the problem was - maybe I should have edited the bug report rather than restating the problem for anyone else reading it.

It is unfortunate as you did the right thing by trying to catch ``CorruptedXMLError``, but it didn't trigger. Thanks for reporting this.

Do you want to do a pull request with a unit test with ``assertRaises`` in ``test_Entrez.py``?

**Comment by xapple** [comment] 2015-08-10 08:58
OK I did it. It's in pull request #595

**Comment by xapple** [comment] 2015-08-10 15:12
So the test I wrote failed apparently because of this:

    File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 4212, in test_truncated_xml
    import StringIO
    ImportError: No module named 'StringIO'

But that's a built-in module in python ?

**Comment by cbrueffer** [comment] 2015-08-10 15:20
StringIO seems a bit problematic; have a look at this snippet from test_SeqIO.py:

```
try:
    from StringIO import StringIO  # Python 2
    # Can't use cStringIO, quoting the documentation,
    #   "Unlike the StringIO module, this module is not able to accept
    #    Unicode strings that cannot be encoded as plain ASCII strings."
    # Therefore can't use from Bio._py3k import StringIO
except ImportError:
    from io import StringIO  # Python 3
```

**Comment by peterjc** [comment] 2015-08-10 15:38
Assuming nothing weird is going on with unicode, just use ``from Bio._py3k import StringIO`` rather than a complex try/except to take care of the Python 2/3 conversion.

**Comment by peterjc** [comment] 2015-08-10 15:50
Thanks for reporting this with a test case and turning it into a pull request - closing as fixed now :)

**Closed by peterjc** 2015-08-10 15:50 UTC
