### ISSUE TITLE
URL won't open, did something change?

### ISSUE THREAD

**Issue by mhsultan-1998** [biopython/biopython#3562] opened 2021-05-28 01:23 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
from datetime import datetime 
import pandas as pd
from Bio.Blast import NCBIWWW
from Bio.Blast import NCBIXML
from Bio import SearchIO

def protein_formatter(input_string, name):
    n = 60
    chunks = [input_string[i:i+n] for i in range(0, len(input_string), n)]
    k = chunks[0]
    chunks[0] = '>' + name + '\n' + k + '\n'
    v = 1
    b = len(chunks)
    while v <= (b-1):
        
        g = chunks[v]
        chunks[v] = g + '\n'
        
        v += 1
    fg = "".join(chunks)
    return fg

def str_list_sum(input_list):
    x = 0
    for z in input_list:
        x += len(z)
    return x

def list_manager(y, x, limit):
    d = []
    d1 = []
    e = []
    e1 = []
    z = 1
    v = 0
    while z <= len(x):
        if str_list_sum(x[v:z]) <= limit:
            # k = '>' + y[v] + '\n' + x[v] + '\n'
            d1.append(x[v])
            e1.append(y[v])
            if z == len(x):
                d.append(d1.copy())
                e.append(e1.copy())
                d1 = []
                e1 = []
        if str_list_sum(x[v:z]) > limit:
            g = d1[-1][:-1]
            d1[-1] = g
            d.append(d1.copy())
            e.append(e1.copy())
            d1 = []
            e1 = []
            v += 1
            z = z - 1
        z += 1
    return d

def list_manager1(x, limit):
    d = []
    d1 = []
    v = 0
    z = 1
    while z <= len(x):
        if str_list_sum(x[v:z]) <= limit:
            d1.append(x[z-1])
            
            if z == len(x):
                d.append(d1.copy())
                d1 = []
                
        if str_list_sum(x[v:z]) > limit:
            
            d.append(d1.copy())
            d1 = []
            v = z-1
            z = v
            
        z += 1
    return d
def data_parser1_21(input_xml, output_csv):
    blast_qresult = SearchIO.parse(input_xml, "blast-xml")
    #print(blast_qresult.__dict__.keys())
    x1 = 0
    for j in blast_qresult:
        #print(j, '\n')
        #query result
        ogp = j._id
        ql = j.seq_len
        k = 0
        m = 0 #match indicator
        for x in j:
            #hit
            k += 1
            np = x.id
            if np == 'pdb|6F1T|X':
                print(j,'\n')
            c = 0
            for z in x:
                #HSP
                #df1 = pd.read_csv(output_csv, header=None)
                c += 1
                
                if ((z.ident_num)/(z.hit_span)) == 1 and z.ident_num == ql:
                    #if ((df1[0] == np) & (df1[1] == 2)).any() == False:
                    d = {0: [(np + ' ' + ogp)], 1: [2]}
                    df = pd.DataFrame(data=d)
                    df.to_csv(output_csv, mode = 'a', header = False, index = False)
                    m = 1
                    #break
                    #(jw < 1) or 
                if (m == 1) and (c == len(x) and (((z.ident_num)/(z.hit_span)) != 1 or z.ident_num != ql) and k == 5):
                    #if ((df1[0] == ogp) & (df1[1] == 0)).any() == False:
                    d = {0: [ogp], 1: [0]}
                    df = pd.DataFrame(data=d)
                    df.to_csv(output_csv, mode = 'a', header = False, index = False)
                    #break
            # else:
            #     continue
            # break
        # else:
        #     continue
        # break
        x1 += 1
    return
def bp1_data_2(input_csv, output_csv):
    start_time = datetime.now() 
    print(start_time)
    data = pd.read_csv(input_csv, header=None)
    ogn = data.columns.tolist()
    n = data[ogn[0]].tolist()
    seqs = data[ogn[1]].tolist()
    
    x = 0
    while x != len(seqs):
        g = protein_formatter(seqs[x], n[x])
        #print(g)
        seqs[x] = g
        x += 1
    print('Total length:', len(seqs))
    v = list_manager1(seqs, 100000)
    
    f = 0
    for x in v:
        
        for b in x:
            f += 1
    print('f', f)
    gg = v[0] + v[1]
    rd = pd.DataFrame({0: gg})
    rd.to_csv('a_1-2_test.csv', mode = 'a', header = False, index = False)
    x = 0
    while x != len(v):
        k = v[x][-1][:-1]
        v[x][-1]=k
        x += 1
    
    x = 0
    while x != len(v):
        v1 = "".join(v[x])
        v[x] = v1
        x += 1
    print('Lists organized')
    x = 0
    while x != len(v):
        start_time1 = datetime.now()
        _result_handle = NCBIWWW.qblast("blastp", "pdbaa", v[x], hitlist_size = 5, alignments=5, 
                                       descriptions=5)
        the_xml = "zzzout" + str(x+1) + '.xml'
        with open(the_xml, "w") as out_handle:
            out_handle.write(result_handle.read())
        print('the', the_xml,'is made')
        result_handle.close()_
        data_parser1_21(the_xml, output_csv)
        x += 1
        print(x)
        single_xml_time_elapsed = datetime.now() - start_time1
        print('Single xml formation and processing time elapsed (hh:mm:ss.ms) {}'.format(single_xml_time_elapsed))
    total_time_elapsed = datetime.now() - start_time
    print ('Total time elapsed (hh:mm:ss.ms) {}'.format(total_time_elapsed))
    return x
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
I feed in a csv file where one column has the names of proteins and the next column has their primary sequences. What I'm supposed to output is a csv where one column is the names from the original csv if there were no matches in PDB or the matching PDB names, and the second column are tags in 0 and 2 to indicate a match was found (2) or if a match wasn't found (0). 
(*Please fill this in*)

### Actual behaviour
However, the primary URL https://blast.ncbi.nlm.nih.gov/Blast.cgi won't open giving me the "python urlerror: <urlopen error [errno 11001] getaddrinfo failed>".
(*Please fill this in, and provide any exception message in full*)

It's not my internet causing the issue and this program was running fine two days ago. Did something change with NCBI?

### Steps to reproduce
Just try running a BLAST the way I did. If it works for you, then I've no idea what the problem is.
(*Please fill this in *)

**Comment by Caiofcas** [comment] 2021-05-28 22:17
When I run this code, which I believe is a minimal example for what you are asking:

```
>>> from Bio.Blast import NCBIWWW
>>> url = NCBIWWW.qblast("blastp", "pdbaa", "LLKLKK", hitlist_size = 5, alignments=5, descriptions=5)
>>> url
<_io.StringIO object at 0x7f654a3054c0>
```

There seems to be no problem, all information is retrieved. Could you try running this code just to make sure the problem is connecting to the NCBI server? 

Also, what version of python/Biopython/OS are you running? The code bellow should print this information:

```
>>> import sys; print(sys.version)
>>> import platform; print(platform.python_implementation()); print(platform.platform())
>>> import Bio; print(Bio.__version__)
```

Mine are:
```
3.9.5 (default, May  4 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
CPython
Linux-5.11.20-200.fc33.x86_64-x86_64-with-glibc2.32
1.78
```

**Comment by peterjc** [comment] 2023-06-05 15:07
Closing due to lack of information. It was hopefully a temporary network issue only.

**Closed by peterjc** 2023-06-05 15:07 UTC
