### ISSUE TITLE
 HTTP Error 404 issue

### ISSUE THREAD

**Issue by LivC182** [biopython/biopython#2765] opened 2020-02-26 23:57 UTC
I am reporting a problem with Biopython version 1.73, Python version 3, and operating
system Ubuntu 18.04.
I am trying to run the code below using multiprocessing package. I send less than 10 requests/second and yet I get urllib.error.HTTPError: HTTP Error 404.
Anyone how knows why ?
```
         Entrez.email = 'my_email'
         Entrez.tool = my_tool'
         handle = Entrez.efetch(db = 'pubmed',
                                retmode = 'text',
                                rettype = 'Medline',
                                id = pubmed_id,
                                api_key = 'my api key')

         results = handle.read()
         handle.close()
         rec_file = io.StringIO(results)
         medline_rec = Medline.read(rec_file)
```

**Comment by peterjc** [comment] 2020-02-27 00:01
https://www.ncbi.nlm.nih.gov/books/NBK25499/table/chapter4.T._valid_values_of__retmode_and/ suggests ``rettype='medline'`` (lower case string), as in the example in http://biopython.org/DIST/docs/tutorial/Tutorial.html

**Comment by LivC182** [comment] 2020-02-27 00:05
it doesn't work either.

**Comment by peterjc** [comment] 2020-02-27 00:09
Right now I can't run your partial example to debug it. Have you got a similar example working with an API key? Can you get this example to work if you don't use an API key? That would tell you if the problem is the API key, or more fundamental.

**Comment by LivC182** [comment] 2020-02-27 00:11
It is working fine with remode = xml. Tks for your input, maybe is something wrong on their end.

**Comment by chebizarro** [comment] 2020-07-24 05:42
The following code seems to work as expected, returning a `TextIOWrapper` object with the publication information in MEDLINE format:

```
from Bio import Entrez
Entrez.email = 'my_email'
Entrez.tool = 'my_tool'
pmid = "19304878"
handle = Entrez.efetch(db = 'pubmed',
                       retmode = 'text',
                       rettype = 'medline',
                       id = pmid)
```

Presumably this issue can be closed now?

**Comment by mdehoon** [comment] 2020-07-24 07:12
@LivC182  's code works for me. I guess it was a network glitch. Closing this as the problem cannot be replicated.

**Closed by mdehoon** 2020-07-24 07:12 UTC
