### ISSUE TITLE
Bug in parsing Nexus comments with commas

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython#471] opened 2015-02-09 15:57 UTC
The nexus parser of Bio.Phylo seems to have some problem with dealing with extra meta data.

I am trying to parse a (heavily annotated) nexus file with `Bio.Phylo`. The file is from a paper on science http://www.sciencemag.org/content/345/6202/1369/suppl/DC1 available here http://www.sciencemag.org/content/suppl/2014/08/27/science.1259657.DC1/1259657_file_s2.zip and called `trees/ebola.raxml.tree`

I am able to parse this with DendroPy just fine, but not with Bio.Phylo

The error that I get is:

```
hdl = Phylo.read('trees/ebola.raxml.tree', 'nexus')

/home/tra/Dropbox/soft/biopython/Bio/Nexus/Trees.pyc in _get_values(self, text)
    161             if nc_end == -1:
    162                 raise TreeError('Error in tree description: Found %s without matching %s'
--> 163                                 % (NODECOMMENT_START, NODECOMMENT_END))
    164             nodecomment = text[nc_start:nc_end + 1]
    165             text = text[:nc_start] + text[nc_end + 1:]
TreeError: Error in tree description: Found [& without matching ]
```

**Comment by tiagoantao** [comment] 2015-02-09 15:58
I am far from being a specialist here, but here is what I have found:

1. I can process it with dendropy

2. It is the internal node meta-data information (like [&label=100]). If I remove it, it works. I do not find any issue with mismatched tags.

To sum it up: I suspect the parser is choking on the internal node meta-data...

**Comment by vincentdavis** [comment] 2015-02-28 16:07
I fiddled with this a bit and the problem is with the ',' in the sections like 
* '[&label=100,!collapse={"collapsed",0.0}]:0.419411'
 * problem with 0,! and ",0
* '[&label=88_!cartoon={4,0.0}_'
 * problem with 4,0

If I remove all of these by replacing the with '_' then it appears to work.
I did this by doing a find replace like.
,! replace with _!
", replace with "_
,0.0 replace with _0.0

**Comment by vincentdavis** [comment] 2015-12-07 20:05
I was looking at pull request https://github.com/biopython/biopython/pull/668 If I read the Nexus format definition correctly a "," is not allowed. The above problem is caused by the "," i.e. replacing the "," fixes the error. Then the problem is the NEXUS file. Maybe a better error and/or validation of the file would be helpful?

**Comment by peterjc** [comment] 2015-12-07 21:37
I don't know the NEXUS format well enough to know if the commas here are simple not allowed, need escaping somehow, or if there are actually allowed.

How about you, @etal?

**Comment by ArtPoon** [comment] 2017-01-19 15:55
I ran into this same problem when attempting to parse a NEXUS tree generated using [MASTER](https://github.com/tgvaughan/MASTER).  In my experience, the NEXUS format is not a strict standard, and there are many different (often not cross-compatible) implementations of NEXUS in different programs.  Replacing commas with underscores within comments via regex worked for me, but it would be great if the output could be read directly into Python.

**Comment by nylander** [comment] 2017-03-15 09:55
Hi,
I'm running into similar issues as described, and

> I don't know the NEXUS format well enough to know if the commas here are simple not allowed, need escaping somehow, or if there are actually allowed.

The problem is definitely with the Nexus parser. It should not choke on the commas **inside the comments**, it should ignore them along with the rest of the comment - that's what the square brackets are for!

Ever since people realized that the current Nexus standard is limited, they started putting all sorts of information inside the comments. But if someone wishes to parse the (structured) info inside the comments, they need a different parser. Or start writing in NeXML.

Cheers
Johan

**Comment by etal** [comment] 2017-07-03 20:35
The unit tests `test_NexusComments` in `Tests/test_Nexus.py` currently passes with a tree that includes commas in comments. Is this bug fixed now?

**Comment by peterjc** [comment] 2017-07-03 21:36
Confirming - @cswarth's work on #668 sounds like it would have fixed this - and going back to @tiagoantao's example the file now parses. Closing issue - thanks everyone.

**Closed by peterjc** 2017-07-03 21:36 UTC
