### ISSUE TITLE
Option to ignore format GenBank specs/warnings

### ISSUE THREAD

**Issue by kescobo** [biopython/biopython#747] opened 2016-01-06 18:50 UTC
I'm trying to add some information to a collaborators' genbank files by reading in the file, altering certain fields (like `record.annotations['source']` and then re-writing them. Unfortunately, the LOCUS definition is too long and BioPython keeps spitting out warnings, eg:

```
File "/usr/local/lib/python3.5/site-packages/Bio/SeqIO/InsdcIO.py", line 555, in _write_the_first_line
    raise ValueError("Locus identifier %r is too long" % str(locus))
ValueError: Locus identifier 'BW77_ACAGTG.R1_(paired)_contig_28' is too long
```
(that's line 616 in the current `master` branch)

I'd rather not change the name to keep consistent with collaborator's files, and the files are parsed just fine. If I go in and suppress all of the `assert` statements and the `ValueError`, nothing seems to break. I don't want to get rid of these checks completely, but it would be nice to be able to set a flag or something to ignore these assertions in cases where the file doesn't need to meet strict standards.

**Comment by peterjc** [comment] 2016-01-07 04:12
You probably got a parser wanting when loading these files in Biopython?

The NCBI does seem to be working towards longer LOCUS names, having relaxed the length limit slightly in recent years. Until they change the LOCUS line format though, being column based all the additional fields are a problem if you want to use an overly long identifier. For now breaking the spec is just going to cause trouble with interoperability with other tools.

**Comment by kescobo** [comment] 2016-01-07 17:35
>You probably got a parser wanting when loading these files in Biopython?

Actually no - they load in just fine (I'm using v1.66 and python3). I don't get any warnings or errors until I go to write the file. If this is a problem, let me know if you'd like the code/file I'm using to diagnose it. 

>The NCBI does seem to be working towards longer LOCUS names

This is actually the output of some annotation software (RAST I think), and it's really long (you can see it above, 33 chars), I doubt it would fit any of the standards. But it seems like there are plenty of non-standard files out there. Obviously supporting all of them would be a nightmare though... 

>Until they change the LOCUS line format though, being column based all the additional fields are a problem if you want to use an overly long identifier. For now breaking the spec is just going to cause trouble with interoperability with other tools.

I agree breaking the spec is a bad idea in principal, but I need to do it nevertheless. I modified the relevant functions to include an optional `standard=True` flag, and just have it spit a warning instead of an error if it's set to `False`. This seems to work fine for my purposes (the file that's written is identical to the input, except for the fields I changed), but I don't know if breaks something else. I'd be happy to submit a PR, but if this is a niche enough use-case that it's not worth including, please feel free to close this issue.

**Comment by peterjc** [comment] 2016-01-08 04:07
If you can share the input file that would be interesting (gist.github.com or email me at Google Mail if you want it private).

The annotation tool Prokka also has problems with long identifiers when trying to write a GenBank LOCUS line...

**Comment by kescobo** [comment] 2016-01-11 18:29
Gist seems to be having issues with the whole thing. [Here's](https://gist.github.com/kescobo/3f9c663daafd79615b5f) the first couple of contigs. 

I also included the code that I'm running. Uncommenting line 14 allows it to work with default `Bio`, the `standard` flag in the last line makes it work with the modifications I mentioned.

**Comment by kblin** [comment] 2016-04-01 09:03
Just ran into this as well. As I mentioned on twitter, I think the current behaviour does violate the principle of least surprise for the user.

I can understand the "be generous with what you accept, but strict with what you output" reasoning, but as mentioned the parser doesn't even throw a warning. Not that a warning is very helpful in non-interactive programs.

From the perspective of an application that loads user-provided GBK files, processes them somehow and writes the output, I'm happy to return invalid fields just as invalid as I got them. With the current setup, my only option to get my output to my user is to manually sanitize it. So :+1: from me for a PR, I'm happy to review code.

**Comment by peterjc** [comment] 2016-04-01 09:11
I am surprised your input GenBank files didn't trigger a warning. Can you share an example with us (by email if you can't share it publicly). A few sample LOCUS lines might help. My guess is your data is in the grey area where an over-long identifier but short length together can squeeze into the available space. If so perhaps we can relax the writer to do that too (with a warning)?

**Comment by kblin** [comment] 2016-04-01 09:25
I'm sure I can easily reproduce that with a slight tweak to one of the test GBKs, hang on

**Comment by kblin** [comment] 2016-04-01 09:43
Ok, so this is with a slight variation from `biopython/Tests/GenBank/invalid_locus_line_spacing.gb`, but instead of the invalid locus line spacing, I just made the locus tag longer. (It's a .txt file because github file upload only allows very few file extensions) [too_long_locus.gb.txt](https://github.com/biopython/biopython/files/199337/too_long_locus.gb.txt)

Now, if you run the following script:
```python
from Bio import SeqIO
rec = SeqIO.read('too_long_locus.gb', 'gb')
SeqIO.write([rec], 'nope.gb', 'gb')
```

You will a) not see a warning from the parser, b) have the `write()` call die with a ValueError and c) have an empty `nope.gb` file in your current directory, adding to the confusion.

**Comment by peterjc** [comment] 2016-04-01 09:59
Thanks @kblin. We are indeed as I suspected in the grey area where we can preserve the column based layout by stealing spaces from the length field in order to go beyond the 16 character identifier limit.

LOCUS from ``too_long_locus.gb.txt``,

```
LOCUS       AB070938_too_long_now   6497 bp    DNA     linear   BCT 11-OCT-2001
```

Original LOCUS line as used in other test files,

```
LOCUS       AB070938                6497 bp    DNA     linear   BCT 11-OCT-2001
```

Variant using 16 chars, called this ``max_id_len.gb`` in example below:

```
LOCUS       AB070938_max_len        6497 bp    DNA     linear   BCT 11-OCT-2001
```

This shows the error you described,

```
$ python -c "from Bio import SeqIO; SeqIO.convert('too_long_locus.gb', 'gb', 'output.gb', 'gb')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 1012, in convert
    alphabet)
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/_convert.py", line 377, in _handle_convert
    return SeqIO.write(records, out_handle, out_format)
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 483, in write
    count = writer_class(fp).write_file(sequences)
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/Interfaces.py", line 211, in write_file
    count = self.write_records(records)
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/Interfaces.py", line 196, in write_records
    self.write_record(record)
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/InsdcIO.py", line 730, in write_record
    self._write_the_first_line(record)
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/InsdcIO.py", line 555, in _write_the_first_line
    raise ValueError("Locus identifier %r is too long" % str(locus))
ValueError: Locus identifier 'AB070938_too_long_now' is too long
```

Here's the OK file with a 16 letter identifier:

```
$ python -c "from Bio import SeqIO; SeqIO.convert('max_id_len.gb', 'gb', 'output.gb', 'gb')"
```

And here's the invalid file which rightly fails to parse:

```
$ python -c "from Bio import SeqIO; SeqIO.convert('invalid_locus_line_spacing.gb', 'gb', 'output.gb', 'gb')"
/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py:1222: BiopythonParserWarning: Attempting to parse malformed locus line:
'LOCUS       AB070938          6497 bp    DNA     linear   BCT 11-OCT-2001\n'
Found locus 'AB070938' size '6497' residue_type 'DNA'
Some fields may be wrong.
  splitline[2], splitline[4]), BiopythonParserWarning)
```

Proposal:

* Add a warning to the parser where currently it silently accepts the long identifier;

* Modify the writer to accept long identifiers provided the sequence length is short enough to squeeze in both, but issue a warning in this case.

However, this will not address the wider problem of very long identifiers as originally raised by @kescobo

**Comment by kescobo** [comment] 2016-04-01 14:15
Seems like that would be an improvement. Have you sorted why my locus identifier (I just counted, 33 characters) works if I suppress the assertions?

**Comment by peterjc** [comment] 2016-04-01 14:20
I've not looked at what happens if the assertions are removed, no. If you really really want to output with a long identifier, it make be safest if Biopython deliberately drops the rest of the LOCUS line (since the fields cannot be placed at the right columns)?

**Comment by kblin** [comment] 2016-04-02 06:20
I think most implementations just split() and count fields, even though the GBK specs explicitly recommend not doing this.

**Comment by peterjc** [comment] 2016-06-10 09:03
Via pull request #802, which I've just applied to the master branch, we will now write out longer GenBank LOCUS names if we can steal space from the length field.

This still doesn't allow really long names like the 33 characters @kescobo wanted to use, but that would mean breaking the current GenBank specification for all the other column-based fields in the LOCUS line.

As @kblin notes, some GenBank parsers will try splitting on white space rather than assuming the column based standard is being used, so perhaps there is more leeway here for our output.

Closing for now, hopefully the NCBI will do something about the LOCUS line in a future revision to the standard.

**Closed by peterjc** 2016-06-10 09:03 UTC
