### ISSUE TITLE
Default treatment of .description in SeqIO FASTA format

### ISSUE THREAD

**Issue by rsharris** [biopython/biopython#2270] opened 2019-09-16 18:55 UTC
### Setup

I am reporting a problem with Biopython 1.74, Python 3.7.3, and linux as follows:

Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.19.0-6-amd64-x86_64-with-debian-10.1
>>> import Bio; print(Bio.__version__)
1.73

for r in SeqIO.parse(infile, "fasta"):
	d=str(len(r.seq))
	SeqIO.write(SeqRecord(r.seq,id=r.id,description=d),outfile,"fasta")

### Expected behaviour

I expect the fasta headers to contain the sequence name and the sequence length.

### Actual behaviour

If the sequence length happens to equal the sequence name, as_fasta() incorrectly assumes the "description includes the id at the start" and discards the id.

This is a serious problem. I am using a third party package that uses BioPython. the package reads a fasta file, does some computation on each sequence, then outputs the same sequences with several statistics annotated in the fasta header lines. The first stat happens to be the sequence length.

Meanwhile, the input sequence I am using is the output of a 3rd party sequence assembler. The sequence assembler happens to number its output sequences.

I can't change either of the 3rd party tools. (And why should I need to -- both are correct).

As SeqIO is currently implemented, it seems like for any program using SeqIO.write() and using a description, that calling program has to check to make sure the description's prefix doesn't match the sequence's name. And then I guess they can work around that by doubling the prefix. But that really seems nutty.

Maybe you could add an argument to SeqIO.write() that says 'use all of my description.'

### Steps to reproduce

Create a fasta file with a length 5 sequence named "5". Then feed it to this snippet.

for r in SeqIO.parse(infile, "fasta"):
	d=str(len(r.seq))
	SeqIO.write(SeqRecord(r.seq,id=r.id,description=d),outfile,"fasta")

The output will contain a fasta header ">5" rather than the correct ">5 5".

**Comment by chris-rands** [comment] 2019-09-17 08:25
I believe this behaviour is [by design
](https://github.com/biopython/biopython/blob/master/Bio/SeqIO/FastaIO.py#L359)

Would this kind of workaround be okay for you?

```
for r in SeqIO.parse(infile, "fasta"):
    d = len(r.seq)
    r.description = '{} {}'.format(r.id, d)
    SeqIO.write(r, outfile, "fasta")
```

**Comment by peterjc** [comment] 2019-09-17 09:25
It is indeed by design, due to what was in hindsight a poor design choice in the very early Biopython FASTA parser (setting the full ``>`` line content as the ``.description``). Note you can already change this on the parser if you use ``Bio.SeqIO.FastaIO.FastaIterator`` directly and over-ride the legacy behaviour with a custom ``title2ids`` function argument.

I see no easy way out of this without breaking vast numbers of existing scripts using the old behaviour from the top level ``SeqIO`` functionality under the format name ``fasta`` (and more recently ``fasta-2line``).

Probably the least bad option is new sister format names in ``Bio.SeqIO``, leaving ``fasta`` etc with the legacy behaviour - but what would you call the more sensible behaviour?

**Comment by rsharris** [comment] 2019-09-17 13:09
Thanks.

I agree, there's not really any good way to correct this behavior without breaking many existing scripts.

The workaround Chris suggests is what I would use if I were coding something myself (once I became aware of the issue). Basically, since the function assumes you've replicated the id in the description, you'd better replicate the id in the description. However, I'm using a third party package, so I can't apply such a fix. I will certainly suggest this to the author of that package.

In my case ... 3rd party assembler created fasta with numbered names, fed to third party package that uses BioPython to annotate fasta headers ... the best workaround I can think of is for me to change the names the assembler created, before the fasta is fed into the program that uses BioPython.

I'm tempted to suggest that a warning about this behavior should be added to the Sequence Output section of https://biopython.org/wiki/SeqIO, with something that points to the workaround. Because technically for any program to confidently use SeqIO.write() for fasta they do have to use a workaround. But then, adding that to the docs would clutter up the description. And few people would ever notice that and use the workaround anyway.

Thanks,
Bob H

**Comment by peterjc** [comment] 2019-09-17 14:25
You've got a good grasp of this, yes. If you would like to suggest a particular wording on the SeqIO page, a pull request would be welcome.

As to the workaround,  I've use a similar code snippet myself when needing exact control over FASTA output, usually something like: ``record.description = record.id + " " + desired_description``

**Comment by rsharris** [comment] 2019-09-17 21:17
Yeah, I can't think of a good way to bring this up in the SeqIO page. Adding too much special case detail to documentation clobbers readability.

As it is, the description field is only mentioned twice on that page, only in passing. (Maybe it is described in some other section of the documentation?). None of the simple code examples use it. If there were a code example that read fasta and added sequence length as the description and wrote it, that example could demonstrate the workaround. Perhaps the filter by sequence length example could have another snippet added which does that, after the part where it talks about iterators.

Bob H

**Comment by peterjc** [comment] 2019-09-18 08:37
There is a lot of ``Bio.SeqIO`` documentation in the Tutorial (a whole chapter), and in the module's docstrings:

http://biopython.org/DIST/docs/tutorial/Tutorial.html

https://biopython.org/DIST/docs/api/Bio.SeqIO-module.html (old URL, will eventually retire this)
https://biopython.org/docs/dev/api/Bio.SeqIO.html (new URL, could change)

**Comment by chris-rands** [comment] 2019-09-26 14:13
I can write a PR for the tutorial ([here](https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_seqio.tex) I guess?) with an example of how to rename a FASTA title when using `SeqIO.parse()` and `SeqIO.write()` via the 'workaround' if it helps?

this question has been asked on a few forums too:
https://bioinformatics.stackexchange.com/questions/307/changing-the-record-id-in-a-fasta-file-using-biopython
https://www.biostars.org/p/156428/

I also noticed another odd feature is that `as_fasta` cleans that `description` by not only removing any stray `\n` and `\r` (sensible), but also double-spaces are replaced with single-spaces (why?) via `Bio.SeqIO.Interfaces._clean()`. It can lead to some quesiontable(?) outputs that still contain double spaces but not as many as where in the description, e.g. 

```
>>> s
SeqRecord(seq=Seq('ATG', SingleLetterAlphabet()), id='1', name='1', description='1 2 3 4 a            b c', dbxrefs=[])
>>> s.description
'1 2 3 4 a            b c'
>>> SeqIO.write(s, sys.stdout, 'fasta')
>1 2 3 4 a      b c
ATG
1
```

**Comment by peterjc** [comment] 2019-09-26 14:21
Yes, that is the source of the SeqIO chapter in the tutorial - written in LaTeX for now.

As to the clean code - Good question, I don't remember why I did the double space to single space, but it was originally here:

d1b1acbba8c87fe8780258319a580e2971823e3c

This now exists in both SeqIO and AlignIO - by all means try removing that and if nothing breaks in the test suite, make a pull request.

**Comment by peterjc** [comment] 2019-10-10 15:23
I think we can close this with the updated Tutorial?

**Comment by rsharris** [comment] 2019-10-10 16:57
Seems reasonable to me, FWIW.

**Closed** 2019-10-11 08:37 UTC
