### ISSUE TITLE
10.5.2  Searching Swiss-Prot sprot_search_ful example does not run.

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#996] opened 2016-11-13 16:37 UTC
I was testing this in reference to an [old redmine issue](https://redmine.open-bio.org/issues/3301)
reporting the URL for sprot_search_ful no longer being valid.

```python
from Bio import ExPASy
import re

#handle = ExPASy.sprot_search_de("Orchid Chalcone Synthase")
# or:
handle = ExPASy.sprot_search_ful("Orchid and {Chalcone Synthase}")
html_results = handle.read()
if "Number of sequences found" in html_results:
    ids = re.findall(r'HREF="/uniprot/(\w+)"', html_results)
else:
    ids = re.findall(r'href="/cgi-bin/niceprot\.pl\?(\w+)"', html_results)
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-ae78a961bd3d> in <module>()
      6 handle = ExPASy.sprot_search_ful("Orchid and {Chalcone Synthase}")
      7 html_results = handle.read()
----> 8 if "Number of sequences found" in html_results:
      9     ids = re.findall(r'HREF="/uniprot/(\w+)"', html_results)
     10 else:

TypeError: a bytes-like object is required, not 'str'
```

**Comment by peterjc** [comment] 2016-11-13 17:24
Its Python 2 code, for Python 3 you need to convert the bytes-based network handle into a text-based one. See #754.

Also looks like a partial duplicate of #253?

**Comment by peterjc** [comment] 2018-07-04 15:41
Good news: The bytes vs string issue seems to have been fixed.

Bad news: The regular expression used in the ``Doc/Tutorial/chapter_uniprot.tex`` tutorial example to get the matches fails.

Parsing HTML is always going to be fragile, but unless there is a better way to do this we might just want to remove that example (and consider deprecating ``Bio.ExPASy.sprot_search_ful``)?

**Comment by peterjc** [comment] 2018-10-08 08:54
Cross reference #253, I think we should deprecate ``sprot_search_ful`` as well.

**Comment by chebizarro** [comment] 2020-07-21 23:32
`sprot_search_ful` was deprecated and removed in 2ceb458. Can this issue be closed now?

**Comment by peterjc** [comment] 2020-07-22 09:27
Thank you, closing.

**Closed by peterjc** 2020-07-22 09:27 UTC
Labels: Bug, Documentation, help wanted
