### ISSUE TITLE
PDBParser.get_structure throws unhandled ValueError in rare case

### ISSUE THREAD

**Issue by ekiefl** [biopython/biopython#2819] opened 2020-03-25 21:31 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-18.2.0-x86_64-i386-64bit
1.75
```

### Description

In rare instances, so far 1 / 46,000 cases, this error crops up. The PDB ID in question is 3cmy

```
Traceback (most recent call last):
  File "mre.py", line 9, in <module>
    structure = p.get_structure('3cmy', path)
  File "/Users/evan/virtual-envs/anvio-master/lib/python3.6/site-packages/Bio/PDB/PDBParser.py", line 89, in get_structure
    self._parse(handle.readlines())
  File "/Users/evan/virtual-envs/anvio-master/lib/python3.6/site-packages/Bio/PDB/PDBParser.py", line 110, in _parse
    self.header, coords_trailer = self._get_header(header_coords_trailer)
  File "/Users/evan/virtual-envs/anvio-master/lib/python3.6/site-packages/Bio/PDB/PDBParser.py", line 128, in _get_header
    header_dict = _parse_pdb_header_list(header)
  File "/Users/evan/virtual-envs/anvio-master/lib/python3.6/site-packages/Bio/PDB/parse_pdb_header.py", line 310, in _parse_pdb_header_list
    missing_res_info = _parse_remark_465(tail)
  File "/Users/evan/virtual-envs/anvio-master/lib/python3.6/site-packages/Bio/PDB/parse_pdb_header.py", line 165, in _parse_remark_465
    model, residue["res_name"] = match.group(1).split(" ")
ValueError: too many values to unpack (expected 2)
```

### Steps to reproduce

Paste this in a python interpreter:

```python
import Bio.PDB as PDB

l = PDB.PDBList()
p = PDB.PDBParser()

path = l.retrieve_pdb_file('3cmy', file_format='pdb', overwrite=True)
structure = p.get_structure('3cmy', path)
```

**Comment by peterjc** [comment] 2020-03-26 10:00
It might be worth updating to Biopython 1.76 just in case that fixed this (not my area of the code so I'm not sure immediately).

**Comment by rob-miller** [comment] 2020-03-26 16:16
Current dev branch does not handle this, I created a pull request with a
small change and added test case to cover it.  Passes previous test cases,
but would be nice if OP could run the 46k through with this change to see
if it breaks something that worked before?

The issue with PDB file 3CMY appears to be that the missing residue 'REMARK
465' line that breaks refers to a DNA base instead of a standard residue.
The regex captures this, however the split did not handle multiple spaces.
I believe this works as intended; the previous test cases pass, and have
added an additional test case from 3CMY.

**Comment by peterjc** [comment] 2020-03-26 18:54
Thanks Rob - @ekiefl are you comfortable with testing Rob's proposed fix? You're on macOS so installing Biopython from source shouldn't be too tricky. You don't have to know git either - we could give some basic directions for getting his branch.

**Comment by ekiefl** [comment] 2020-03-26 19:02
I'm happy to test a couple hundred on master, but testing 45k structures is more internet usage than I'm willing to use.

**Comment by peterjc** [comment] 2020-03-26 19:05
OK, assuming this gets merged to master soon that'd be very helpful. Sometimes people already have vast numbers of PDB files cached locally, so large scale testing is possible - it depends on what you are working on really. Thanks!

**Comment by ekiefl** [comment] 2020-03-26 19:06
Actually I was not thinking clearly. I have those structures cached in a database--no internet required. I can test this next week.

**Comment by peterjc** [comment] 2020-03-30 12:50
Should be fixed on the master branch now that #2821 is merged, testing would be appreciated.

**Comment by collinarnett** [comment] 2020-04-18 02:22
Will this be in the pypi package any time soon? Getting this error with 2f03 on version 1.76

**Comment by ekiefl** [comment] 2020-04-18 02:25
Sorry I was never able to test this. My stored structures actually have comments removed so there are no remark 465s :/

**Comment by rob-miller** [comment] 2020-04-18 08:01
On Sat, 18 Apr 2020 at 03:22, Collin Arnett <notifications@github.com>
wrote:

> Will this be in the pypi package any time soon? Getting this error with
> 2f03 on version 1.76
>
not the solution you’re asking for, but I’ve found installing from source
very easy:

Clone the repository from github
Pip uninstall biopython
Pip install /path/to/cloned/repo

As noted in this thread above, the fix has been committed to the current
master branch, and I confirm I can load 2f03 with it now (albeit with
several discontiguous chain warnings).

**Comment by collinarnett** [comment] 2020-04-22 22:32
Tested 2f03 and it works when I install from source.

**Comment by peterjc** [comment] 2020-04-23 10:18
Thanks everyone - I think we can close this then.

**Closed by peterjc** 2020-04-23 10:18 UTC
