### ISSUE TITLE
AttributeError: 'SeqFeature' object has no attribute 'strand'

### ISSUE THREAD

**Issue by ryandward** [biopython/biopython#4563] opened 2024-01-02 20:34 UTC
## Setup
- **Biopython Version:** 1.82
- **Python Version:** 3.11.5 (main, Sep 27 2023, 11:42:37) [GCC 11.4.0]
- **Operating System:** Linux-5.15.0-91-generic-x86_64-with-glibc2.35
- **Python Implementation:** CPython

## Expected Behaviour
When processing GenBank files using Biopython, each gene feature should have a 'strand' attribute.

## Actual Behaviour
The 'strand' attributes are missing for gene features in GenBank files.

## Steps to Reproduce
1. Run the following script to parse a GenBank file and check for the presence of 'strand' attributes in gene features:
   ```python
   from Bio import SeqIO

   import sys; print(sys.version)
   import platform; print(platform.python_implementation()); print(platform.platform())
   import Bio; print(Bio.__version__)

   def check_strand_in_genes(genome_file):
       count = 0
       for record in SeqIO.parse(genome_file, "genbank"):
           for feature in record.features:
               if feature.type == "gene":
                   gene_name = feature.qualifiers.get('gene', ['Unknown'])[0]
                   if hasattr(feature, 'strand'):
                       print(f"'strand' attribute exists for {gene_name} in record {record.id}")
                       count += 1
                   else:
                       print(f"'strand' attribute does not exist for {gene_name} in record {record.id}")
                       count += 1
                   if count >= 5:
                       return

   # Replace 'genome_file.gb' with the path to your GenBank file
   # Example file: https://www.ncbi.nlm.nih.gov/nuccore/U00096.3/
   check_strand_in_genes('sequence.gb')
   ```

2. Note that the output indicates the absence of 'strand' attributes for the genes.

## Observed Output
```bash
3.11.5 (main, Sep 27 2023, 11:42:37) [GCC 11.4.0]
CPython
Linux-5.15.0-91-generic-x86_64-with-glibc2.35
1.82
'strand' attribute does not exist for thrL in record U00096.3
'strand' attribute does not exist for thrA in record U00096.3
'strand' attribute does not exist for thrB in record U00096.3
'strand' attribute does not exist for thrC in record U00096.3
'strand' attribute does not exist for yaaX in record U00096.3
```

**Comment by peterjc** [comment] 2024-01-02 22:50
Change ``.strand`` to ``.location.strand`` when working with a ``SeqFeature`` under Biopython 1.82 (works on older versions too).

See #4555 (recent discussion) and #4503 (pull request where this change was made), which on re-reading we had explicitly deprecated strand etc as arguments to the SeqFeature initialization, but technically the properties of the same name were not officially deprecated. In hindsight I would have kept them for Biopython 1.82, but perhaps deprecated them.

Do you feel we should restore the ``.strand`` attribute? Would read only suffice? Would you object to restoring it just to deprecate it?

**Comment by ryandward** [comment] 2024-01-03 14:22
Thanks for the clarification regarding the `.strand` attribute in 1.82.

I believe adding an official note in the release about this change would be helpful for coders transitioning to the new version. It could probably prevent any confusion.

While I have already updated my code to use `.location.strand`, implementing a read-only `.strand` attribute or marking it as deprecated could be helpful to give some time to adapt to the new method while maintaining backward compatibility.

Again, thank you for addressing this issue and for your ongoing efforts to improve Biopython.

**Comment by ialbert** [comment] 2024-01-05 00:17
These types of undocumented changes make it extremely difficult to use Biopython for any kind of reproducible and reusable tooling.

Code will randomly start breaking, across minor release from 1.81 to 1.82

One's code will end up a kludge of monkey patches.

The same issues occurred from 1.78 to 1.79 and now from 1.81 to 1.82 

You should never just remove a valid attribute without some sort of documented deprecation policy.

**Comment by peterjc** [comment] 2024-01-05 10:33
Note using ``.location.strand`` will work from Biopython 1.59 (Feb 2012) though to the current release 1.82 (and beyond).

**Comment by mdehoon** [comment] 2024-01-05 14:15
@ialbert  I still don't understand what exactly you are proposing. Never deprecate anything? Never remove deprecated code?

**Comment by ialbert** [comment] 2024-01-05 14:49
I think you should not deprecate any feature where the cost of maintaining it is exceedingly low. 

I want to refer to your own words here, "trivial". If the fix is trivial as you say it is, then Biopython should carry the fix and not break everyone's work. 

In the end we are not talking about keeping thousands of lines of complex algorithms where the author has long left the building. The fix is something as simple as:

```
@property
def strand(self):
    return self.location.strand
    
```
 Then, somewhere in the tests  
 
      assert self.strand == self.location.strand
      
 Now all prior code is still working. How is this effort not worth the tradeoffs of keeping decades of code working?
 
I am not trying to advocate a general policy or a mandate. a rule. Foolish consistency is just as big of an error than not having any rules.

All I am advocating is a common sense tradeoff, where you look at your effort, contrast that to the problems, anguish, and setbacks the changes cause, and say, I am going to be kind to all these people that use Biopython and not break their code when the fix is indeed trivial.

**Comment by mdehoon** [comment] 2024-01-05 14:56
My issue with that is that `self.location` can be `None`. The property assumes that `self.location` cannot be `None`. It is buggy code.

**Comment by peterjc** [comment] 2024-01-05 15:13
The existing code (which Biopython 1.82 just removed) assumed ``self.location`` was not ``None`` when reading the property (the default error seems self explanatory to me), but caught the case when writing the property (when the default error would have been unclear).

@ialbert do you support #4572 as currently written? Restores the alias but read only, and starts the deprecation process - with ``.strand`` merely marked as obsolete (with a pending deprecation warning).

**Comment by ialbert** [comment] 2024-01-05 15:22
> My issue with that is that self.location can be None. 

Now we are in a different discussion mode altogether.  I would say the indicates a deeper problem that you are trying to paper over by moving strand to `self.location.strand`. It is how having a problem leads you to a solution with even more problems.

if indeed `self.location` can be `None` then what happens when I try to read `self.location.strand` in my code as you suggest?  

I will get a cryptic error: ''NoneType' object has no attribute 'strand'" how is that a solution then? Should everyone start wrapping their codes with ifs and try except blocks when reading the strand?

`None` is not a proper null value for an object model. `None `is a proper value for an actual value and even in that case it is questionable. 

The null value for location should be a valid Location object that properly informs the user when an attribute is not set or returns a default value rather than a cryptic error.

**Comment by peterjc** [comment] 2024-01-05 15:24
@ialbert That would be an API breaking change though, and ``None`` is often used as a null value for missing data. I don't see any upside there.

**Comment by ialbert** [comment] 2024-01-05 15:27
What I am saying is that a construct such as

@property
def strand(self):
     if self.location is None:
         raise a meaningful error
     else:
         return self.location.strand
         
 is actually helpful and does not break API, versus using what you advocate:
 
     self.location.strand
    
which will actually lead to a cryptic message and also breaks the API

**Comment by mdehoon** [comment] 2024-01-05 15:27
@ialbert 

> if indeed self.location can be None then what happens when I try to read self.location.strand in my code as you suggest?

Then it is your code, and your responsibility. It may not matter in your particular use case.

Feel free to submit a PR if you think you can improve on the current situation.

**Comment by peterjc** [comment] 2024-01-05 18:25
If you are reading the value then ``my_feature.strand`` (on Biopython 1.81 or older) it was doing ``my_feature.location.strand`` internally. They both fail the same way if ``my_feature.location`` is ``None``.

I have added raising a more helpful ``AttributeError`` to proposal on #4572 (that specific exception type to match the historic behaviour).

> Should everyone start wrapping their codes with ifs and try except blocks when reading the strand?

That is a little extreme but depending on where your records/features/locations come from, you *should* be wrapping your location code (including usage of strand) in a try/except or some defensive if statements. For example the GenBank parser will sometimes return a record where a feature as location none.

**Comment by ialbert** [comment] 2024-01-05 19:13
I like the proposed solution in #4572 that restores the attributes.

I would venture to say that proper construct is not a Try/Except block since the value is known to be None.

One shouldn't catch a much broader set of errors in this case "AttributeError" when in in fact detecting a well defined value (None) was the intent. There could be other reasons why an attribute error is raised later.

The try-except block was designed for a different purpose, it has is a far more complicated construct and sends the wrong message. 

In my opinion, it should be an `if self.location is None`  construct.

**Comment by peterjc** [comment] 2024-01-05 19:37
The time difference is likely minimal, but I was guided by the assumption that a never-used try-except is near zero cost since Python 3.11 https://docs.python.org/3.11/whatsnew/3.11.html#optimizations :

> “Zero-cost” exceptions are implemented, eliminating the cost of [try](https://docs.python.org/3.11/reference/compound_stmts.html#try) statements when no exception is raised.

The only way I can see this differing in behaviour is if the ``.location`` object is not the expected Biopython class. But OK, I am open to changing to the if-statement.

--

Note right now #4572 does *not* fully restore the original behaviour. It only implements a read-only alias, it does not let you set the strand.

**Comment by ialbert** [comment] 2024-01-05 19:45
Upon some consideration, it might be too late.

What could end up being even more confusing is code where BioPython 1.81 and 1.83 runs, but BioPython 1.82 does not. Imagine that...

Now that I thought about it, the proper solution would, in my opinion, be to raise an error on `.strand` in a way that tells the user how to fix the code. That way, at least, you help people fix the code rather than sending them to Googling.

**Comment by peterjc** [comment] 2024-01-05 20:38
We've broken code under 1.82, we can fix it again under 1.83. This is easy to trouble shoot with the proposed notes in the NEWS files, or indeed searching the issue tracker.

The proposed code on #4572 uses deprecation warnings to say how to change the code for the long term (when these aliases intentionally go away).

And the sooner we restore the alias and release 1.83, the less people will be affected as many would end up skipping 1.82.

**Comment by ialbert** [comment] 2024-01-05 20:40
Makes sense. Perhaps you can yank the 1.82 from PyPI and that way it won't even install unless pinned to it.

**Comment by peterjc** [comment] 2024-01-05 20:44
Yanking 1.82 from PyPI currently seems an overreaction based on three packages/people reporting the issue, but that is a possibility once 1.83 is out. Yanking it now would hurt anyone already happily using new functionality in 1.82.

**Comment by ialbert** [comment] 2024-01-05 20:47
I meant yanking after 1.83 is out. Yanking only means it won't install by default and is not considered in the resolution order; it is not actually removing the release and it is still installable by pinning to the version.

**Comment by ialbert** [comment] 2024-01-05 20:48
https://pypi.org/help/#yanked

**Comment by mdehoon** [comment] 2024-01-06 00:39
> Now that I thought about it, the proper solution would, in my opinion, be to raise an error on .strand in a way that tells the user how to fix the code. That way, at least, you help people fix the code rather than a confusing traceback sending them to Googling.

I agree with that.

**Comment by mdehoon** [comment] 2024-01-06 00:40
@peterjc  Should we do release 1.83 on a separate branch? The cleanest solution would be to have a 1.83 release that addresses the SeqFeature issue, but is otherwise the same as 1.82.

**Comment by mdehoon** [comment] 2024-01-06 01:37
There is also the possibility that the location is not `None`, but still the strand is not defined (for example, a SNP location or a methylated region).
Then I would suggest to
- first check if the location is `None`, and raise an exception with a helpful error message if it is;
- then try to get the attribute `strand`, and raise an exception with a helpful error message in case of an `AttributeError`;
- if there is no problem, return the strand, but issue a `DeprecationWarning` explaining why we advise against using `feature.strand`.

**Comment by peterjc** [comment] 2024-01-06 18:35
@mdehoon a branch is possible for 1.83, although I think the tutorial work is good enough (with #4573 applied) that we could stick to the master branch - what do you feel about the BLAST work etc?

And if you want to work on an alternative to #4572, sure. I may not get time to work further on that in the next few days.

**Comment by mdehoon** [comment] 2024-01-07 00:22
> @mdehoon a branch is possible for 1.83, although I think the tutorial work is good enough (with https://github.com/biopython/biopython/pull/4573 applied) that we could stick to the master branch - what do you feel about the BLAST work etc?

I think the tutorial is fine, but I think the Blast work will confuse everybody at this stage.

> And if you want to work on an alternative to https://github.com/biopython/biopython/pull/4572, sure. I may not get time to work further on that in the next few days.

I am not sure if we have converged on a solution yet.

**Comment by peterjc** [comment] 2024-01-07 19:13
Proposal: Revert to the 1.82 code (which allowed read and writing), add (pending) deprecation warnings.

If there is no objection about deprecating the aliases (following https://biopython.org/wiki/Deprecation_policy with warnings and timeline), then I see no reason to attempt to improve their behavior in corner cases.

**Comment by ialbert** [comment] 2024-01-07 20:00
This is a good point and a precedent and guideline for the future.

**Comment by peterjc** [comment] 2024-01-07 20:34
If we want an interim release with the strand fix, but not the BLAST work, then that would be easiest done branching right after Biopython 1.82. That means also without the Tutorial changes, and the handful of other changes since.

**Comment by mdehoon** [comment] 2024-01-07 22:54
Are we planning to follow the deprecation policy as usual and remove the aliases after two releases?

**Comment by peterjc** [comment] 2024-01-07 23:24
I am suggesting that for ``.ref`` and ``.ref_db`` (which I believe to be almost never used), yes.

However for ``.strand`` right now my PR only labels that as "obsolete" and gives a silent-by-default pending deprecation warning. I would expect it to stay like that for at least one release, possibly more if there turn out to be more people inconvenienced by its removal.

**Comment by mdehoon** [comment] 2024-01-08 08:42
I think @ialbert 's solution (to raise an Exception if `.strand` is used, with an explanation on how to fix the code) is better than a silent-by-default pending deprecation warning. Those are pretty much useless, as most people will not notice them.

My question on the deprecation policy is broader:

If we move away from the deprecation policy and keep deprecated code around if people complain, then I see a long-term problem for Biopython.

Deprecated code still needs to be maintained, tested, and described in the documentation. The current case is fairly simple; other deprecations can be much more complicated. If we start keeping deprecated code, then Biopython will become a mess. And it is not much fun to work on that.

The biggest problem with that it will then be difficult to motivate people to work on Biopython.  Biopython is already short on developers. Personally, I would not be much motivated to contribute to Biopython if it means working around old buggy code that cannot be cleaned up.

We may end up in a situation then that there are too few developers to keep Biopython going, at least the 1.xx series, and the project will die off.

**Comment by peterjc** [comment] 2024-01-08 10:05
The ``.strand`` issue will get plenty of publicity due to the extra release even with a (silent by default) pending deprecation warning. I think this strikes the right balance for not breaking existing code but providing a clear pathway to removing the legacy code from Biopython. However we could apply the noisy BiopythonDeprecation warning instead (as I am proposing for the ``.ref`` and ``.ref_db`` aliases).

As to the broader question, I don't think anyone is suggesting keeping alive legacy code when the maintenance burden is non-trivial. I accept the ``.strand`` alias is in itself fairly trivial, but it still adds to a cumulative burden of legacy code. This nuance is why I felt we could afford a slightly slower timetable to drop the ``.strand`` alias.

**Comment by ialbert** [comment] 2024-01-08 13:08
I think radically breaking backward compatibility is the most significant impediment to a framework's adoption.

Especially when that compatibility loss does not net any novel functionality or overall improvement. 

From someone that uses BioPython for their work what is the benefit of moving strand from `self.strand` to `self.location.strand`?  When was the last time this kept them from achieving their goals? For me, it feels like a move for the sake of "purity of design".

In my opinion, BioPython does not attract developers because it is too inward-focused. You are moving `strand` to `location.strand` instead of revamping the way BioPython works. What the world needs are better designed BioPython classes not patching up legacy codes here and there. You can't fix the mistakes of the past, without making the system even less inviting.

BioPython needs a new Feature class that does not carry all that legacy code, it needs a fast BED/GFF parser, how come I have to implement my own such class? BioPython needs a fast FASTQ parses based on kseq.h. BioPython needs function to access databases, etc. Things we actually use in the real world. 

And again I never felt constrainded or confused by a feature having a strand. In fact that made a lot of sense. Now strand will be tucked away more into an even less accessible format.

**Comment by peterjc** [comment] 2024-01-08 13:33
The strand was moved to ``.location.strand`` 13 years ago https://github.com/biopython/biopython/commit/3ced0ded0595d5dc3d075ca3702acdcbf39a5f17 as part of a major cleanup of the location/position objects. That seems to have worked well in terms of not breaking code.

--

That the GenBank influenced SeqFeature object model wasn't a good fit to GFF did stall and has effectively blocked integrating Brad Chapman's work on a parser but you can use that - see https://biopython.org/wiki/GFF_Parsing and https://github.com/chapmanb/bcbb/tree/master/gff and https://github.com/daler/gffutils - we didn't "radically break backward compatibility" there in Biopython but it had a cost.

Are you in a position to propose a more flexible feature object model which would work for GFF/GTF and GenBank/EMBL/UniProt? Ideally something backward compatible, but that is not easy (at least I didn't see a good route last time I tried).

**Comment by mdehoon** [comment] 2024-01-08 13:43
@ialbert  

> It feels like a slog to contribute because it demands that the new contributor adopt and deal with all the mistakes of the past.

Exactly. And the only way to fix the mistakes of the past is deprecating and removing old code.

@ialbert  Try and maintain Biopython for a while. See how you like it. Especially when you then get yelled at by angry users, as no good deed goes unpunished.

**Comment by ialbert** [comment] 2024-01-08 14:11
My point is precisely the opposite. I believe old code cannot be fixed and should be left as is.  

But long story short, I can write here whatever I want, and I am a driveby commenter. The true test is your evaluation of BioPython's state in the developer's mindset. If BioPython is not gaining mindshare, then that is caused by the way you prioritize goals and deliverables.

**Comment by mdehoon** [comment] 2024-01-08 14:47
> I believe old code cannot be fixed and should be left as is.

Yes but then Biopython 1.xx will die, as there won't be enough people willing to maintain it.

**Closed** 2024-01-10 09:42 UTC

**Comment by peterjc** [comment] 2024-01-10 09:44
That's fixed on the main branch now, with an interim release to follow.
