### ISSUE TITLE
can't set auth_residues=False in MMCIFParser

### ISSUE THREAD

**Issue by Jeff-LaFrence** [biopython/biopython#4276] opened 2023-04-05 00:02 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
parser = PDB.MMCIFParser(QUIET=True,auth_residues=False)
strure = parser.get_structure("",'../../../datasets/PDBs/1ab9.cif')
```

### Expected behaviour

I would expect this to make it so that I can index the structure as ``structure[model#][chain_name][index]`` with index being the 2 in  TRP B 2 126  instead of 141 from 141 TRP B from below
```
ATOM   1008 C CH2 . TRP B 2 126 ? 14.801 1.309   29.870 1.00 11.99 ? 141 TRP B CH2 1 
```
or make it so that residue.get_id can parse similarly 

### Actual behaviour

returns type error upon file parsing

```
TypeError                                 Traceback (most recent call last)
parser = PDB.MMCIFParser(QUIET=True,auth_residues=False)
----> structure = parser.get_structure("",f'../../../datasets/PDBs/1ab9.cif)

~/anaconda3/envs/data/lib/python3.10/site-packages/Bio/PDB/MMCIFParser.py:74), in MMCIFParser.get_structure(self, structure_id, filename)
     72         warnings.filterwarnings("ignore", category=PDBConstructionWarning)
     73     self._mmcif_dict = MMCIF2Dict(filename)
---> 74     self._build_structure(structure_id)
     75     self._structure_builder.set_header(self._get_header())
     77 return self._structure_builder.get_structure()

~/anaconda3/envs/data/lib/python3.10/site-packages/Bio/PDB/MMCIFParser.py:241), in MMCIFParser._build_structure(self, structure_id)
    239     except (KeyError, IndexError):
    240         msg = f"Non-existing residue ID in chain '{chainid}'"
--> 241     warnings.warn(
    242         "PDBConstructionWarning: ",
    243         msg,
    244         PDBConstructionWarning,
    245     )
    246     continue
    247 int_resseq = int(resseq)

TypeError: 'type' object cannot be interpreted as an integer
```

### Steps to reproduce

parsing a structure with ``PDB.MMCIFParser(auth_residues=False)``

**Comment by peterjc** [comment] 2023-04-05 08:05
Issue edited to use markup to show indentation etc.

I am not familiar with this area of the code. Maybe @jgreener64 or @JoaoRodrigues might be able to advise?

**Comment by jgreener64** [comment] 2023-04-05 11:33
Looks like a repeat of https://github.com/biopython/biopython/issues/4216, I'll submit a PR to fix.

Looks like we don't test the `auth_residues` or `auth_chains` options, ideally we would.

**Comment by peterjc** [comment] 2023-04-05 11:44
I agree, closing as a duplicate of #4216. Thanks Joe.

**Comment by peterjc** [comment] 2023-04-05 15:54
This should be working now (thanks @jgreener64)! You'd need to install Biopython from source or wait for Biopython 1.82 to be released.

**Closed** 2023-04-05 15:54 UTC
