### ISSUE TITLE
Partial codons in SearchIO exonerate parser

### ISSUE THREAD

**Issue by pschwede** [biopython/biopython#367] opened 2014-10-07 14:23 UTC
I'm trying to convert [exonerate](http://www.ebi.ac.uk/~guy/exonerate/) output to psl using a simple script:

``` python
from Bio import SearchIO
QRESULTS = SearchIO.parse("my_exonerate.out", 'exonerate-text')
SearchIO.write(QRESULTS, "my_psl.out, 'blat-psl')
```

The error message depends on the output format. In the case above, it reads

``` plain
Traceback (most recent call last):
  File "./vulgar2psl.py", line 14, in <module>
    SearchIO.write(QRESULTS, ARGS.outfile, 'blat-psl')
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py", line 620, in write
    writer.write_file(qresults)
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/BlatIO.py", line 602, in write_file
    for qresult in qresults:
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py", line 316, in parse
    for qresult in generator:
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/ExonerateIO/_base.py", line 236, in __iter__
    for qresult in self._parse_qresult():
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/ExonerateIO/_base.py", line 364, in _parse_qresult
    hsp = _create_hsp(prev_hid, prev_qid, prev['hsp'])
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/ExonerateIO/_base.py", line 188, in _create_hsp
    frags = _adjust_aa_seq(frags)
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/ExonerateIO/_base.py", line 43, in _adjust_aa_seq
    assert len(frag) % 3 == 0
AssertionError
```

I get other assertion errors with "exonerate-vulgar" and "exonerate-cigar". In none of the cases, the script finishes successfully.

Is this a bug? Am I doing something wrong? Are there any restrictions in using the exonerate parameters?

**edit:**

Here is the exonerate result for now: https://gist.githubusercontent.com/pschwede/df803361b7f6647183c0/raw/6529e84ba6c13a97a50f6a9712ce34f6e8cee28a/Alignments%20Sample

``` plain
$ exonerate --version
exonerate from exonerate version 2.2.0
Using glib version 2.31.12
Built on Jan 24 2012
Branch: unnamed branch
```

**Comment by peterjc** [comment] 2015-08-06 19:51
See also #591 (which I just closed as a duplicate of this) where @zbwrnz shared another sample output file, which would probably make a great test case.

**Comment by zbwrnz** [comment] 2015-08-06 20:23
It is common for splice junctions to interrupt codons. Often this phenomena is of biological interest.

I recommend replacing the missing letters in the split codons with N's before translating them. The translator should interpret these as an unknown residues and represent them as X's. 

For example, take the following sequence

AAAT <<< intron >>> TTGGG

This codes for the amino acid sequence 'KFG', but the 'F' codon is split. I recommend converting the exons to 'AAATNN' and 'NTTGGG' before translating them. The resulting amino acid sequences for the two HSPs will be 'KX' and 'XG'.

Reporting the first HSP as coding for either 'KF' or 'K' would lead to incorrect scientific conclusions. It has to be 'KX'. This is common practice in bioinformatics. For example, the alignment editor Seaview translates incomplete codons surrounding gaps as 'X'.

If you want the whole peptide sequence, you'd have to concatenate the HSP nucleotide sequences and then translate.

**Comment by bow** [comment] 2015-08-06 20:35
Hi @zbwrnz,

Hmm..that sounds sensible actually (making the split amino acid as Xs). This will make the internal length checks slightly off (since we will, in effect, be introducing an extra `X` amino acid for each split codon alignment). But it does make the representation neater. 

Perhaps it is also useful to mark the fragment with some other property (e.g. `fragment.has_split_codon`)? Are there other software using the same convention as SeaView?

**Comment by zbwrnz** [comment] 2015-08-06 21:01
@bow 

*transeq* from the EMBOSS toolkit also interprets incomplete codons as X, e.g.

```bash
echo -e '>a\nAAATTTT' | transeq -filter
>a_1
KFX
```

I'd say this is the expected behavior.

Maybe you could give each fragment the property "phase". This is the convention used in [GFF files](http://www.sequenceontology.org/gff3.shtml), they explain it as follows:

> For features of type "CDS", the phase indicates where the feature begins with reference to  the reading frame. The phase is one of the integers 0, 1, or 2, indicating the number of bases that should be removed from the beginning of this feature to reach the first base of the next codon. In other words, a phase of "0" indicates that the next codon begins at the first base of the region described by the current line, a phase of "1" indicates that the next codon begins at the second base of this region, and a phase of "2" indicates that the codon begins at the third base of this region. This is NOT to be confused with the frame, which is simply start modulo 3.

> For forward strand features, phase is counted from the start field. For reverse strand features, phase is counted from the end

Do you have to translate the coding sequences? Maybe it would be better to store the nucleotide sequences and translate upon request? This would avoid the length problem and maybe reduce overhead, but I'm not very familiar with the biopython setup.

**Comment by bow** [comment] 2015-08-06 21:26
> Maybe you could give each fragment the property "phase". This is the convention used in GFF files, they explain it as follows

That sounds sensible, too. We've already implemented the notion of a reading frames, but as you pointed out, phase is something else.

> Do you have to translate the coding sequences? Maybe it would be better to store the nucleotide sequences and translate upon request? This would avoid the length problem and maybe reduce overhead, but I'm not very familiar with the biopython setup.

We try to keep the primary alignment information intact. This requires some work when the alignment is between protein and DNA, since it is difficult to represent DNA to protein alignment when codons are split (as you can see).

So while we don't do any translations per se, I want to keep the exonerate-translated DNA to protein alignment as much as possible.

**Comment by bow** [comment] 2016-12-17 03:36
Closing since #815 has addressed this.

**Closed by bow** 2016-12-17 03:36 UTC
