### ISSUE TITLE
SearchIO.write crashes with AttributeError

### ISSUE THREAD

**Issue by claudiusmueller** [biopython/biopython#2218] opened 2019-08-16 17:36 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
CPython Linux-4.12.14-lp150.12.67-default-x86_64-with-glibc2.3.4
1.74

### Expected behaviour

```
qresults = SearchIO.parse('raw_blast.xml', 'blast-xml')
SearchIO.write(qresults, 'test.tab', 'blast-tab')
```

or 

`SearchIO.convert('raw_blast.xml', 'blast-xml', 'test.tab', 'blast-tab')`

should read a previously saved blast result file in xml-format ("raw_blast.xml") and save a tab formatted blast output file ("test.tab").

### Actual behaviour

Instead, both crash with the following message:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/Bio/SearchIO/BlastIO/blast_tab.py", line 732, in _build_rows
    value = getattr(hsp, _COLUMN_HSP[field][0])
AttributeError: 'HSP' object has no attribute 'mismatch_num'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/Bio/SearchIO/__init__.py", line 636, in write
    qresult_count, hit_count, hsp_count, frag_count = writer.write_file(qresults)
  File "/usr/lib64/python3.6/site-packages/Bio/SearchIO/BlastIO/blast_tab.py", line 692, in write_file
    handle.write(self._build_rows(qresult))
  File "/usr/lib64/python3.6/site-packages/Bio/SearchIO/BlastIO/blast_tab.py", line 736, in _build_rows
    value = getattr(hsp, attr)
AttributeError: 'HSP' object has no attribute 'mismatch_num'

### Steps to reproduce

1. Perform a peptide blast search using the nr database.
2. Save result as xml file.
3. Try to conver the xml file into human readable format.
4. Crash.

**Comment by peterjc** [comment] 2019-08-19 14:53
Confirming using ``Tests/Blast/xml_2226_tblastx_004.xml``, looks like a regression from Biopython 1.73 to 1.74:

```
$ python -c "from Bio import SearchIO; import sys; SearchIO.convert(sys.stdin, 'blast-xml', sys.stdout, 'blast-tab')" < xml_2226_tblastx_004.xml 
/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/SearchIO/_legacy/NCBIStandalone.py:45: BiopythonWarning: Parsing BLAST plain text output file is not a well supported functionality anymore. Consider generating your BLAST output for parsing as XML or tabular format instead.
  BiopythonWarning
gi|296147483:1-350	gi|296147483|ref|NM_001183135.1|	100.00	116	0	0	2	349	2	349	1e-76	 289
gi|296147483:1-350	gi|296147483|ref|NM_001183135.1|	100.00	116	0	0	349	2	349	2	2e-73	 278
gi|296147483:1-350	gi|296147483|ref|NM_001183135.1|	100.00	116	0	0	348	1	348	1	4e-72	 274
gi|296147483:1-350	gi|296147483|ref|NM_001183135.1|	100.00	116	0	0	3	350	3	350	9e-71	 270
gi|296147483:1-350	gi|296147483|ref|NM_001183135.1|	100.00	116	0	0	350	3	350	3	1e-58	 229
gi|296147483:1-350	gi|296147483|ref|NM_001183135.1|	100.00	85	0	0	94	348	94	348	9e-54	 197
gi|296147483:1-350	gi|296147483|ref|NM_001183135.1|	100.00	14	0	0	1	42	1	42	9e-54	36.3
gi|296147483:1-350	gi|365982352|ref|XM_003667962.1|	72.94	85	23	0	94	348	88	342	2e-37	 152
gi|296147483:1-350	gi|365982352|ref|XM_003667962.1|	78.57	14	3	0	69	110	63	104	2e-37	26.3
gi|296147483:1-350	gi|365982352|ref|XM_003667962.1|	61.82	55	21	0	350	186	344	180	5e-20	68.0
gi|296147483:1-350	gi|365982352|ref|XM_003667962.1|	61.54	39	15	0	137	21	131	15	5e-20	52.8
gi|296147483:1-350	gi|365982352|ref|XM_003667962.1|	34.95	103	67	0	41	349	35	343	7e-08	61.1
gi|296147483:1-350	gi|365982352|ref|XM_003667962.1|	43.08	65	37	0	261	67	255	61	0.024	42.8
gi|296147483:1-350	gi|366988334|ref|XM_003673886.1|	68.24	85	27	0	94	348	94	348	1e-32	 143
gi|296147483:1-350	gi|366988334|ref|XM_003673886.1|	55.56	54	24	0	350	189	350	189	6e-16	62.5
gi|296147483:1-350	gi|366988334|ref|XM_003673886.1|	60.61	33	13	0	137	39	137	39	6e-16	44.6
gi|296147483:1-350	gi|366988334|ref|XM_003673886.1|	33.04	115	77	0	345	1	345	1	8e-06	54.2
gi|296147483:1-350	gi|255710474|ref|XM_002551475.1|	65.48	84	29	0	97	348	94	345	4e-32	 141
gi|296147483:1-350	gi|255710474|ref|XM_002551475.1|	45.45	55	30	0	350	186	347	183	0.005	45.1
gi|296147483:1-350	gi|254579534|ref|XM_002495708.1|	67.86	84	27	0	97	348	97	348	5e-32	 141
gi|296147483:1-350	gi|254579534|ref|XM_002495708.1|	55.10	49	22	0	350	204	350	204	9e-12	51.0
gi|296147483:1-350	gi|254579534|ref|XM_002495708.1|	47.62	42	22	0	140	15	140	15	9e-12	41.8
gi|296147483:1-350	gi|254579534|ref|XM_002495708.1|	31.31	99	68	0	51	347	51	347	0.005	45.1
```

(note the unwanted ``BiopythonWarning`` in the above, that at least was fixed)

versus:

```
$ python -c "from Bio import SearchIO; import sys; SearchIO.convert(sys.stdin, 'blast-xml', sys.stdout, 'blast-tab')" < xml_2226_tblastx_004.xml 
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/SearchIO/BlastIO/blast_tab.py", line 732, in _build_rows
    value = getattr(hsp, _COLUMN_HSP[field][0])
AttributeError: 'HSP' object has no attribute 'mismatch_num'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/SearchIO/__init__.py", line 693, in convert
    return write(qresults, out_file, out_format, **out_kwargs)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/SearchIO/__init__.py", line 636, in write
    qresult_count, hit_count, hsp_count, frag_count = writer.write_file(qresults)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/SearchIO/BlastIO/blast_tab.py", line 692, in write_file
    handle.write(self._build_rows(qresult))
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/SearchIO/BlastIO/blast_tab.py", line 736, in _build_rows
    value = getattr(hsp, attr)
AttributeError: 'HSP' object has no attribute 'mismatch_num'
```

**Comment by bow** [comment] 2019-10-13 18:22
Both: Sorry for the long delay in responding, had been away off GitHub the past few weeks ~ back now :).

@claudiusmueller: #2291 (which was just recently merged) seems to solve this. Would you mind confirming that this is the case?

@peterjc I realized the current tests in `tests_SearchIO_write.py` does not really cover this as they are all round-trip parse-and-write tests. How would you prefer a regression test be added for this particular case?

**Comment by peterjc** [comment] 2019-10-14 08:56
I would have expected a round trip to exercise most of the object attributes, but evidently not.

Perhaps (format specific) parsing tests which check all the attributes explicit? Lots of Michael's tests are like that - although for this one file per format, and checking just one of each object in the hierarchy, is probably enough?

**Comment by bow** [comment] 2019-10-14 17:01
> I would have expected a round trip to exercise most of the object attributes, but evidently not.

This particular case has to do with how an attribute is calculated differently depending on the data source. [There is a function written specifically to accomodate cases](https://github.com/biopython/biopython/blob/master/Bio/SearchIO/BlastIO/blast_tab.py#L166) where the target attribute (`mismatch_num`) is not present but can be derived from existing ones.

When we do a round-trip, `mismatch_num` does not need to be calculated as it is already present. But when the source data is, in this case, `blast-xml`, `mismatch_num` needs to be calculated, hence the different code path and so the error we see here.

> Perhaps (format specific) parsing tests which check all the attributes explicit? Lots of Michael's tests are like that - although for this one file per format, and checking just one of each object in the hierarchy, is probably enough?

Hmm..does it make sense to narrow it down to only the calculated attributes (as done in [that function](https://github.com/biopython/biopython/blob/master/Bio/SearchIO/BlastIO/blast_tab.py#L166)), I suppose?

**Comment by peterjc** [comment] 2020-01-08 12:08
Confirming working on the current master with the same test case I used earlier.

Bow - do you want to open a new issue on the round trip attributes? Or re-open this one?

**Closed by peterjc** 2020-01-08 12:08 UTC
