### ISSUE TITLE
pairwise2 global(local)xx bug and memory leak

### ISSUE THREAD

**Issue by sergpolly** [biopython/biopython#603] opened 2015-09-01 17:39 UTC
I was happily using `pairwise2.align.globalxx(s1,s2)` to align nearly identical sequences up until I faced a couple of ~4000 long proteins - `globalxx` stalls there and keeps leaking memory (30 mins of runtime and >100GB of RAM is not a limit, I've never waited any longer). Minimal example:

```
from Bio import pairwise2
seq1 = ''.join(['A',]+['I' for x in range(4000)])
seq2 = ''.join(['V',]+['I' for x in range(4000)])
aln = pairwise2.align.globalxx(seq1,seq2)
```

getting the matches-score only (which is all I need actually) as `pairwise.align.globalxx(seq1,seq2,score_only=True)`, make things better - `globalxx` does yield an answer (seems to be correct), but for those made up 4001 proteins it takes ~5 mins. Smaller sequences (~40,~400) do align well and in a reasonable time (hundreds of milliseconds scale), though.

importing cpairwise2 does not raise any exceptions, so I'm guessing it's C implementation running.
My `sys.version` output is `2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]`
`Bio.__version__` is 1.65
OS `Ubuntu 14.04.3 LTS`

**Comment by peterjc** [comment] 2015-09-01 18:04
If you are using the C code, this will work:

```
>>> from Bio import pairwise2
>>> from Bio import cpairwise2
>>> pairwise2._make_score_matrix_fast is cpairwise2._make_score_matrix_fast
True
```

Your example also behaves badly on Mac OS X. Deliberately running the Pure Python version:

```
$ cd ~/repository/biopython
$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import pairwise2
>>> seq1 = ''.join(['A',]+['I' for x in range(4000)])
>>> seq2 = ''.join(['V',]+['I' for x in range(4000)])
>>> aln = pairwise2.align.globalxx(seq1,seq2)
^C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Bio/pairwise2.py", line 317, in __call__
    return _align(**keywds)
  File "Bio/pairwise2.py", line 338, in _align
    score_only)
  File "Bio/pairwise2.py", line 540, in _make_score_matrix_fast
    best_score = max(nogap_score, row_score, col_score)
KeyboardInterrupt
```

Sat at 100% CPU according to the Mac Activity Monitor, reaching 5GB in 2 minutes, 10GB after 3.5 minutes, and rising until I aborted. Here "Memory" and "Real Mem" were consistent (see below).

```
$ cd ~
$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import pairwise2
>>> seq1 = ''.join(['A',]+['I' for x in range(4000)])
>>> seq2 = ''.join(['V',]+['I' for x in range(4000)])
>>> aln = pairwise2.align.globalxx(seq1,seq2)
^CKilled: 9
```

Again sat at high CPU usage, with GB memory usage - particularly on the "Memory" column, not so bad under "Real Mem" column (e.g. 55GB vs under 3GB after 1.5 mins).

At this point I'm not sure if there is a memory leak or just poor scaling.

You may be better of looking for a heuristic algorithm which can scale to this length sequence - this module is an exhaustive brute force one.

**Comment by sergpolly** [comment] 2015-09-01 18:36
Yep, my `pairwise2` is using C implementation (`pairwise2._make_score_matrix_fast is cpairwise2._make_score_matrix_fast` came out `True`).

The difference between your 1st and 2nd run is forced Python implementation for `~/repo.../bio...` and default C-code for `~`, isn't it?

So, just to make sure I get it right: you are suggesting that it might be the implementation issue, rather than a bug, and using pairwise2 for smaller sequences is just fine, right? 

Does the fact that `pairwise2` actually finishes calculations for `score_only=1` case, means that it is traceback that's causing troubles? looks like traceback is pure Python-only, isn't it?

**Comment by peterjc** [comment] 2015-09-02 09:57
Yes - by moving to the source code directory, ``import Bio``will look in the local ``Bio/`` folder which does not contain the compiled C code. This was a simple way for me to deliberately run the Pure Python version of ``pairwise2`` for comparison.

At this point I don't know if there is a memory leak bug, or if this is just a limitation of the algorithm/implementation. Sadly this module does not have an active maintainer at the moment, but I would guess ``_make_score_matrix_generic`` could be sped up by using NumPy arrays rather than lists of lists (this would probably save RAM too)?

**Comment by johnbradley** [comment] 2015-09-16 23:42
I think this is an algorithmic limitation.
There is a 3 dimensional list of tuples based on the size of the sequences(named trace_matrix).
So for the example above it creates a 4000 x 4000 x 4000 x 2 data structure.
The third dimension is the list of best matching indexes for a given sequence a/b letter.
Since everything is 'I' there are many best matching indexes when allowing for gaps. 
Even using temp files doesn't seem like a good fix(it would probably be about 64 Gig).

**Comment by peterjc** [comment] 2015-09-17 10:01
Thanks @johnbradley - those numbers sound believable. With large arrays like that I would expect NumPy to save a lot of RAM compared to the current lists-of-lists approach, but either way this is always going to have a practical limit due to the scaling.

Probably if we switched to NumPy we could get a clear out-of-memory exception when allocating the large data structure - which would be better than the current behaviour with lists-of-list which are built up gradually and thus use up all the RAM incrementally effectively bringing the program to a stall.

**Comment by johnbradley** [comment] 2015-09-17 17:52
Welcome @peterjc.  Glad to help.  This is a really interesting project.
So the third dimension of trace_matrix is a jagged array. Some cells have very few items in the list.
How many best matching indexes there are seems to be dependent upon the data used.
So there may be a case where a the giant numpy 4D array would end up being larger(in cases where each cell as only a few best matches.  I'll make the changes to try out NumPy array and see how it goes.

Here is something that frustrates me, but may be specific to this particular unusual data set.
Out of the 64G of data we put in trace_matrix we only read the top left to bottom right to bottom right diagonally. These cells only have one item in them and are quite tiny(4000 x 2 reads).  
I thought about trying to calculate just the cells needed on demand, but this might  be pandering to this particular example.

**Comment by johnbradley** [comment] 2015-10-07 17:08
The third dimension for array can grow up to double it's size(for example 8000 in above case).
Switching to single giant numpy array runs out of memory for some cases where the list version can succeed. Also it looks like inserting values one by one into a numpy array is a little slower than a list.
So this is what I have done:
Create a dictionary to hold each row. Each row is stored as a numpy array.
The length of each list is variable so I create a lookup numpy array to index into it.
It may be simplest to just look at _TraceMatrix and _TraceMatrixRow in Bio/pairwise2 in my commit above.
  
Additionally there was a memory leak where row_cache_index grows with data we no longer use.
I made changes to empty this when it is no longer being used.

**Comment by johnbradley** [comment] 2015-10-07 23:14
I created a pull request: https://github.com/biopython/biopython/pull/631
I didn't change the C version of pairwise2.
If I need to duplicate the changes there let me know.
Thanks.

**Comment by MarkusPiotrowski** [comment] 2015-12-20 00:15
At least under Windows (Win7, Win8.1, both 64bit, with Python 2.11 and Biopython 1.66) the problem is clearly with the C module:

    import time
    from Bio import pairwise2
    from Bio import pairwise2_woC  # pairwise2 with 'C switch' commented out

    length_of_sequence = 500
    seq1 = ''.join(['A',]+['I' for x in range(length_of_sequence)])
    seq2 = ''.join(['V',]+['I' for x in range(length_of_sequence)])

    print 'Running pairwise2 with C module. Sequence length: ', length_of_sequence
    start = time.time()
    aln = pairwise2.align.globalxx(seq1,seq2)
    print 'Time required: %.2f sec' %(time.time()-start)

    print '\nRunning pairwise2 without C module. Sequence length: ', length_of_sequence
    start = time.time()
    aln = pairwise2_woC.align.globalxx(seq1,seq2)
    print 'Time required: %.2f sec' %(time.time()-start)

This shows that the pure Python code is indeed faster(!) then the C implementation:

    ============= RESTART: C:\Users\Markus\Desktop\pairwise_test.py =============
    Running pairwise2 with C module. Sequence length:  100
    Time required: 0.27 sec
    
    Running pairwise2 without C module. Sequence length:  100
    Time required: 0.33 sec
    >>> 
    ============= RESTART: C:\Users\Markus\Desktop\pairwise_test.py =============
    Running pairwise2 with C module. Sequence length:  200
    Time required: 1.97 sec
    
    Running pairwise2 without C module. Sequence length:  200
    Time required: 1.61 sec
    >>> 
    ============= RESTART: C:\Users\Markus\Desktop\pairwise_test.py =============
    Running pairwise2 with C module. Sequence length:  400
    Time required: 16.44 sec

    Running pairwise2 without C module. Sequence length:  400
    Time required: 11.89 sec
    >>>
In addition, the C module requires about 10x more memory: With two 500 letter sequences, it peaks at about 4.3 GByte, while the pure Python function only needs about 480 MByte.
I'm very keen to see this comparison for other systems. 

Actually I'm working on the "an insertion can not follow a deletion" problem in pairwise2, which was mentioned in a recent paper from Alexandros Stamatakis' group (http://biorxiv.org/content/early/2015/11/12/031500, e-mailed by Peter). I think I have solved the problem for the Python code. Next, I want to look at the C code. Although I don't speak C, my changes are relatively minor and I think I will manage to do this. Possibly I will then find the problem in the C code.

BTW, row_cache and row_cache_index don't need to be lists, each of them can be implemented as a single variable, since only one element of each is needed per iteration.

**Comment by peterjc** [comment] 2015-12-20 14:16
If the C code can be fixed, great. Otherwise you're making a good case for removing it, and focusing on the Pure Python only. The module does need a maintainer (or co-maintainers) if that's something you'd be willing to take on.

**Comment by MarkusPiotrowski** [comment] 2019-03-14 21:13
The performance of ```pairwise2``` has much improved with PR #782 and there is the new, faster ```PairwiseAligner``` within the ```Align``` module.

So I'm closing this now.

**Closed by MarkusPiotrowski** 2019-03-14 21:13 UTC
