### ISSUE TITLE
Opening Fasta file with gzip.open fails in Python 3

### ISSUE THREAD

**Issue by hannes-brt** [biopython/biopython#2150] opened 2019-06-24 15:06 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-18.6.0-x86_64-i386-64bit
1.70
```

### Expected behaviour

The following should work to open a gzipped Fasta file
```python
genome = SeqIO.to_dict(SeqIO.parse(gzip.open("data/hg38.fa.gz"),
                       'fasta', alphabet=IUPAC.IUPACAmbiguousDNA()))
```

### Actual behaviour

Fails with the following error:

```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/Users/hannes/anaconda3/envs/microexon-code/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 744, in to_dict
    for record in sequences:
  File "/Users/hannes/anaconda3/envs/microexon-code/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 611, in parse
    for r in i:
  File "/Users/hannes/anaconda3/envs/microexon-code/lib/python3.6/site-packages/Bio/SeqIO/FastaIO.py", line 122, in FastaIterator
    for title, sequence in SimpleFastaParser(handle):
  File "/Users/hannes/anaconda3/envs/microexon-code/lib/python3.6/site-packages/Bio/SeqIO/FastaIO.py", line 47, in SimpleFastaParser
    if line[0] == ">":
IndexError: index out of range
```

### Steps to reproduce

Open a Fasta file with gzip.open on Python 3. Same snippet works as expected on Python 2.7.

**Comment by peterjc** [comment] 2019-06-24 15:12
Have you tried Biopython 1.73 (current release)

Could you try this instead, see #1134,

```python
genome = SeqIO.to_dict(SeqIO.parse(gzip.open("data/hg38.fa.gz", "rt"),
                       'fasta', alphabet=IUPAC.IUPACAmbiguousDNA()))
```

If not, do you have a URL for ``hg38.fa.gz`` handy? I assume that's the human genome v38 but I don't use that often. Or better, a smaller file where you've seen this error?

As an aside, do you really really want to use ``SeqIO.to_dict(...)`` here? Would ``SeqIO.index(...)`` or ``SeqIO.index_db(...)`` not be suitable?

**Comment by hannes-brt** [comment] 2019-06-24 15:19
Thanks for the quick reply. Yes, opening in text mode works, but it would be nice if the error mesassage could be more helpful in this situation.

The hg38 Fasta file is available from http://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/hg38.fa.gz, but you can also try a single small chromosome like http://hgdownload.cse.ucsc.edu/goldenpath/hg38/chromosomes/chr22.fa.gz.

**Comment by peterjc** [comment] 2019-06-24 15:28
Confirming, duplicate of #1134:

```
>>> import gzip
>>> from Bio import SeqIO
>>> print(len(list(SeqIO.parse(gzip.open("chr22.fa.gz", "rt"), "fasta"))))
1
>>> print(len(list(SeqIO.parse(gzip.open("chr22.fa.gz"), "fasta"))))
0
```

It is I agree very misleading - the problem is the low level FASTA parser not expecting bytes, only strings. I would expect similar problems on all our text-based parsers, but FASTA and FASTQ are problem most likely to be used compressed like this.

**Comment by peterjc** [comment] 2019-06-24 15:32
Note I don't get the exception that you do (later version of Biopthon), rather a silent failure:

```
>>> import gzip
>>> from Bio import SeqIO
>>> from Bio.Alphabet import IUPAC
>>> genome = SeqIO.to_dict(SeqIO.parse(gzip.open("chr22.fa.gz"),
...                        "fasta", alphabet=IUPAC.IUPACAmbiguousDNA()))
...
>>> genome
{}
```

The code is literally say there are no lines of text starting with the string ``">"`` (but there are lines starting ``b">"`` but we're not looking for bytes).

**Comment by hannes-brt** [comment] 2019-06-24 15:35
Would it be possible add a typecheck that ensures that the file handle returns strings, not bytes?

**Comment by peterjc** [comment] 2019-06-24 15:46
Yes, looking at it now - we already handle this in FASTQ

**Comment by peterjc** [comment] 2019-06-28 08:48
You should get an explicit failure in our next release for FASTA and GenBank/EMBL. Thanks for logging this, the silent failure was most deceptive.

**Closed by peterjc** 2019-06-28 08:48 UTC

**Comment by vinisalazar** [comment] 2023-05-16 04:29
Hi @peterjc,

Recently I've been having trouble in parsing gzip files with `SeqIO.parse`. Would you consider/is there a proposal to add native gzip support to that method? That is, without calling `gzip.open`? Would it be too difficult to add that?

I didn't think this required a new issue altogether (although I'm happy to create one if you prefer), so I thought I would comment here.

Thank you for any assistance you can provide.

Best,
Vini

**Comment by peterjc** [comment] 2023-05-16 08:26
@vinisalazar that would be a new feature request, separate from this old issue. You'd need to think about how it would work - automatically try gzip if given a filename ending ``.gz`` would cover most but not all use cases. Peeking at an input handle is not ideal given it might be a single use stream like stdin.

**Comment by vinisalazar** [comment] 2023-05-16 08:42
Thank you for your reply @peterjc.

I'm strapped for time right now, but I would be happy to give this a go in a couple of weeks' time. Shall I create an issue then to document the (potential) new feature?

Best,
V
