### ISSUE TITLE
problems installing biopython on MacOS 14.7.1 running on Apple M3 chip

### ISSUE THREAD

**Issue by joel-a-hirsch** [biopython/biopython#4880] opened 2024-11-07 08:55 UTC
i have installed python using homebrew:

Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin

upon trying to install biopython as below:
python3 -m pip install biopython
Collecting biopython
  Using cached biopython-1.84.tar.gz (25.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from biopython)
  Using cached numpy-2.1.3-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.1.3-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
Building wheels for collected packages: biopython
  Building wheel for biopython (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for biopython (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [893 lines of output]
      running bdist_wheel
      running build
      running build_py

the process continued nonetheless:

creating build/lib.macosx-14.0-arm64-cpython-313/Bio
      copying Bio/MaxEntropy.py -> build/lib.macosx-14.0-arm64-cpython-313/Bio
      copying Bio/LogisticRegression.py -> build/lib.macosx-14.0-arm64-cpython-313/Bio
      copying Bio/SeqFeature.py -> build/lib.macosx-14.0-arm64-cpython-313/Bio

etc, etc

and then the process terminated with the following errors:

creating build/temp.macosx-14.0-arm64-cpython-313/Bio/Align
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/admin/env-aide/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c Bio/Align/_codonaligner.c -o build/temp.macosx-14.0-arm64-cpython-313/Bio/Align/_codonaligner.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-313/Bio/Align/_codonaligner.o -o build/lib.macosx-14.0-arm64-cpython-313/Bio/Align/_codonaligner.cpython-313-darwin.so
      building 'Bio.Align._pairwisealigner' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/admin/env-aide/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c Bio/Align/_pairwisealigner.c -o build/temp.macosx-14.0-arm64-cpython-313/Bio/Align/_pairwisealigner.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-313/Bio/Align/_pairwisealigner.o -o build/lib.macosx-14.0-arm64-cpython-313/Bio/Align/_pairwisealigner.cpython-313-darwin.so
      building 'Bio.Align._aligncore' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/admin/env-aide/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c Bio/Align/_aligncore.c -o build/temp.macosx-14.0-arm64-cpython-313/Bio/Align/_aligncore.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-313/Bio/Align/_aligncore.o -o build/lib.macosx-14.0-arm64-cpython-313/Bio/Align/_aligncore.cpython-313-darwin.so
      building 'Bio.cpairwise2' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/admin/env-aide/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c Bio/cpairwise2module.c -o build/temp.macosx-14.0-arm64-cpython-313/Bio/cpairwise2module.o
      Bio/cpairwise2module.c:60:22: error: call to undeclared function 'PyEval_CallObject'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
         60 |     if(!(py_result = PyEval_CallObject(py_match_fn, py_arglist)))
            |                      ^
      Bio/cpairwise2module.c:60:20: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
         60 |     if(!(py_result = PyEval_CallObject(py_match_fn, py_arglist)))
            |                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for biopython

any help troubleshooting this would be appreciated. thanks in advance. 
joel hirsch

**Comment by peterjc** [comment] 2024-11-07 11:37
Unfortunately we don't yet have pre-compiled wheels released for Python 3.13, so your system has tried to install from source.

However, as you saw, for Biopython 1.84 there is an incompatibility in our C code for Python 3.13, so it failed.

You can either build the latest source from github where this is fixed, or wait for the next release (which I hope will be this month). Or you could use Python 3.12 in the short term?

Closing as a duplicate of #4706.

**Closed by peterjc** 2024-11-07 11:37 UTC

**Comment by mdehoon** [comment] 2024-11-07 23:47
You can also modify setup.py and remove cpairwise2module from the extensions to be built.
