### ISSUE TITLE
error parsing particular genbank file

### ISSUE THREAD

**Issue by ohthetrees** [biopython/biopython#937] opened 2016-09-14 23:17 UTC
I'm getting a SeqIO parse error on a genbank file downloaded straight from genbank. Please let me know if I can provide any more information. 

[bad.gb.txt](https://github.com/biopython/biopython/files/473638/bad.gb.txt)

```
$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> Bio.__version__
'1.68'
>>> from Bio import SeqIO
>>> record = SeqIO.read(open('bad.gb'), 'genbank')
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(1071..1076,1188..1193,1371..1376,1380..1385,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(618..626,858..866,870..878,882..887,918..923,927..932,1005..1010,1017..1022,1026..1034,1095..1100,1122..1127,1188..1202,1359..1364,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(1161..1166,1338..1343,1350..1355,1362..1367,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(837..842,849..854,1038..1043,1344..1349,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(474..479,1155..1160,1167..1172,1182..1187,1284..1289,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(480..485,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(684..692,723..728,834..839,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(540..557,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(462..470,480..485,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(537..545,549..557,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(762..767,1248..1256,1263..1268,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(11221..11226,11500..11505,11755..11763,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(20757..20762,20820..20831,20835..20840,20844..20858,20883..20894,20934..20939,20979..20984,21144..21149,21156..21167,21192..21200,21213..21236,21279..21284,21531..21536,22809..22817,23046..23051,)'
  % (location_line)))
/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py:1111: BiopythonParserWarning: Couldn't parse feature location: 'order(20991..20999,)'
  % (location_line)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Bio/SeqIO/__init__.py", line 664, in read
    first = next(iterator)
  File "/usr/local/lib/python2.7/dist-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/usr/local/lib/python2.7/dist-packages/Bio/GenBank/Scanner.py", line 478, in parse_records
    record = self.parse(handle, do_features)
  File "/usr/local/lib/python2.7/dist-packages/Bio/GenBank/Scanner.py", line 462, in parse
    if self.feed(handle, consumer, do_features):
  File "/usr/local/lib/python2.7/dist-packages/Bio/GenBank/Scanner.py", line 434, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/usr/local/lib/python2.7/dist-packages/Bio/GenBank/Scanner.py", line 383, in _feed_feature_table
    consumer.location(location_string)
  File "/usr/local/lib/python2.7/dist-packages/Bio/GenBank/__init__.py", line 1053, in location
    operator=location_line[:i])
  File "/usr/local/lib/python2.7/dist-packages/Bio/SeqFeature.py", line 1019, in __init__
    "CompoundLocation should have at least 2 parts, not %r" % parts)
ValueError: CompoundLocation should have at least 2 parts, not [FeatureLocation(ExactPosition(34504), ExactPosition(34510), strand=1)]
```

**Comment by peterjc** [comment] 2016-09-16 16:19
I'm sure we have/had an issue on this, but right now I can't find it. Certainly I remember investigating a similar report.

This is a malformed GenBank file (as per all the Biopython warnings), it looks like bits of the location are missing with extra comma's remaining. It would help if you could provide the URL this record came from, and/or how exactly you downloaded it.

(Similar problems have happened on the NCBI side before, e.g. http://blastedbio.blogspot.co.uk/2012/03/missing-external-exons-in-genbank-with.html although that was a little different)

**Comment by ohthetrees** [comment] 2016-09-20 21:48
The record is embedded in this file: ftp://ftp.ncbi.nih.gov/refseq/release/plastid/plastid.1.genomic.gbff.gz

**Comment by peterjc** [comment] 2016-09-21 13:19
That's great - FTP files are simpler that then web-interfaces as often those files are generated dynamically. Good news, I can reproduce this:

```
>>> from Bio import SeqIO
>>> for r in SeqIO.parse("plastid.1.genomic.gbff", "gb"): print(r.id)
... 
NC_018523.1
NC_022431.1
...
NC_024106.1
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(1071..1076,1188..1193,1371..1376,1380..1385,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(618..626,858..866,870..878,882..887,918..923,927..932,1005..1010,1017..1022,1026..1034,1095..1100,1122..1127,1188..1202,1359..1364,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(1161..1166,1338..1343,1350..1355,1362..1367,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(837..842,849..854,1038..1043,1344..1349,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(474..479,1155..1160,1167..1172,1182..1187,1284..1289,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(480..485,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(684..692,723..728,834..839,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(540..557,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(462..470,480..485,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(537..545,549..557,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(762..767,1248..1256,1263..1268,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(11221..11226,11500..11505,11755..11763,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(20757..20762,20820..20831,20835..20840,20844..20858,20883..20894,20934..20939,20979..20984,21144..21149,21156..21167,21192..21200,21213..21236,21279..21284,21531..21536,22809..22817,23046..23051,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(20991..20999,)'
  % (location_line)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 597, in parse
    for r in i:
  File "/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py", line 478, in parse_records
    record = self.parse(handle, do_features)
  File "/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py", line 462, in parse
    if self.feed(handle, consumer, do_features):
  File "/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py", line 434, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/Library/Python/2.7/site-packages/Bio/GenBank/Scanner.py", line 383, in _feed_feature_table
    consumer.location(location_string)
  File "/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py", line 1050, in location
    operator=location_line[:i])
  File "/Library/Python/2.7/site-packages/Bio/SeqFeature.py", line 1051, in __init__
    "CompoundLocation should have at least 2 parts, not %r" % parts)
ValueError: CompoundLocation should have at least 2 parts, not [FeatureLocation(ExactPosition(34504), ExactPosition(34510), strand=1)]
```

I'll report this to the NCBI, but will try to get Biopython to tolerate these locations with a warning (rather than an exception).

**Comment by peterjc** [comment] 2016-09-21 13:52
Indexing can be used to avoid any records which won't parse:

```
>>> from Bio import SeqIO
>>> d = SeqIO.index('plastid.1.genomic.gbff', 'gb')
>>> for key in sorted(d):
...     print(key)
...     try:
...         r = d[key]
...     except ValueError, e:
...         print(e)
... 
AC_000188.1
NC_000925.1
...
NC_024258.1
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(1071..1076,1188..1193,1371..1376,1380..1385,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(618..626,858..866,870..878,882..887,918..923,927..932,1005..1010,1017..1022,1026..1034,1095..1100,1122..1127,1188..1202,1359..1364,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(1161..1166,1338..1343,1350..1355,1362..1367,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(837..842,849..854,1038..1043,1344..1349,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(474..479,1155..1160,1167..1172,1182..1187,1284..1289,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(480..485,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(684..692,723..728,834..839,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(540..557,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(462..470,480..485,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(537..545,549..557,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(762..767,1248..1256,1263..1268,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(11221..11226,11500..11505,11755..11763,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(20757..20762,20820..20831,20835..20840,20844..20858,20883..20894,20934..20939,20979..20984,21144..21149,21156..21167,21192..21200,21213..21236,21279..21284,21531..21536,22809..22817,23046..23051,)'
  % (location_line)))
/Library/Python/2.7/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(20991..20999,)'
  % (location_line)))
CompoundLocation should have at least 2 parts, not [FeatureLocation(ExactPosition(34504), ExactPosition(34510), strand=1)]
NC_024261.1
...
NC_030789.1
```

Same idea for a one-line test parsing the (first and only) troublesome record:

```
$ python -c "from Bio import SeqIO; d = SeqIO.index('plastid.1.genomic.gbff', 'gb'); print(d['NC_024258.1'])"
```

**Comment by peterjc** [comment] 2016-09-21 15:58
What do you think for the proposal on pull request #941? Would that work nicely for you?

**Comment by ohthetrees** [comment] 2016-09-21 16:03
Yes, I'd be very happy with that. Thanks.

**Comment by peterjc** [comment] 2016-10-05 16:27
OK, this has been merged and should be included in the next release of Biopython (possibly with further adjustment to the warning messages). Thank you!

**Closed by peterjc** 2016-10-05 16:27 UTC

**Comment by ohthetrees** [comment] 2016-10-05 16:49
Awesome, thank you!

**Comment by lisabang** [comment] 2020-01-17 22:23
I am still getting this error when parsing a genbank entry with this problem but on the -1 strand.  I believe that the commit last referenced here fixes the problem but not when the ExactPosition occurs on -1 strand.  I can write a pull request for this although perhaps some others would be more ready + able to do it.

error:
`ValueError: CompoundLocation should have at least 2 parts, not [FeatureLocation(ExactPosition(396909), AfterPosition(396932), strand=-1)]`

https://github.com/MarkusPiotrowski/biopython/commit/79ca8621124463df15bcf1b7b5956fe03932c271
