### ISSUE TITLE
Pip throws error when installing.

### ISSUE THREAD

**Issue by Cediddi** [biopython/biopython#978] opened 2016-10-28 19:40 UTC
I'm a simple man with simple needs. I need to install my requirements with pip. 

But whenever I try to do that I get an error that says I haven't installed numpy. I don't need numpy but biopython does and In python wonderland ,unless it's a system level dependency, packages should not throw errors about dependencies, instead they should define them inside "install_requires" option of setup.py.

Why do I have to do pip install numpy before do pip install -r requirements.txt ? Yes that's a first world problem but It's irritating to explicitly install numpy before installing biopython in my requirements.txt... Just, why... 😞 I install 70+ dependencies without problem, except biopython's "unusual desire" for numpy being preinstalled.

I might look like a jerk to you but this is very irritating and I believe you had serious discussions before coding this out-of-standard behavior. Just please try to fix this. Packages should not depend on user behavior, but should depend on setup.py's defined behavior... 😞

**Comment by mdehoon** [comment] 2016-10-31 01:08
@Cediddi  Can you provide a patch?

**Comment by peterjc** [comment] 2016-10-31 11:24
IIRC, this dependency mechanism requirements mechanism requires ``setuptools`` and (thus far) we've worked out the box with the standard library ``distutils`` when only that is available.

This is probably possible by adding the dependency to ``setup_args`` conditional on (a) setuptools, (b) C Python or very recent PyPy, but not Jython or IronPython etc. However last time we tried it, this didn't work, and we reverted the changes, see e.g. https://github.com/biopython/biopython/commit/bc828342716218b84908c1a4435163e564f31445 https://github.com/biopython/biopython/commit/742e6ff455cdabf81dee8e1cbc74bb369def4d84

CC @chapmanb

**Comment by abdounasser202** [comment] 2016-11-04 14:14
I think it would be better to put all the dependencies in a file `requirements.txt` so we can install them by making a `pip install -r requiremens.txt`

**Comment by peterjc** [comment] 2016-11-04 14:37
OK, if someone can prepare and test a ``requirements.txt`` with the relevant conditionals (i.e. do not require NumPy on Jython), that would be great.

**Comment by peterjc** [comment] 2017-01-20 16:34
Here is a minimal ``requirements.txt`` file which only request NumPy under CPython (not Jython, not PyPy):

```
# We want NumPy under CPython, but not under Jython.
# Currently need to test latest version of PyPy...
numpy; platform_python_implementation == 'CPython'
```

See https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers and https://www.python.org/dev/peps/pep-0496/

I have only tested this minimally on Linux...

**Comment by m-charlton** [comment] 2017-02-01 15:24
I've tested following on both Linux & OSX

```
numpy; platform_version >= '2.7'
numpy; platform_python_version == 'CPython'
```

Included the `platform_version` restriction as biopython no longer supports 
python version 2.6

**Comment by peterjc** [comment] 2017-02-01 15:28
@m-charlton Shouldn't there be a single line for numpy combining all relevant conditions?

And did you make a copy/paste error because the second example won't work - ``platform_python_version`` returns a version number, not an implementation string, e.g.

```
$ python3 -c "import platform; print(platform.python_version())"
3.5.0
```

i.e. We need ``platform_python_implementation`` as in my example earlier.

**Comment by m-charlton** [comment] 2017-02-01 16:43
Good catch, `platform_python_version` should read `platform_python_implementation`.

I tried to specify the constraints on one line, like so:

```
numpy; platform_version >= '2.7'; platform_python_implementation == 'CPython'
```

And I got a parsing error. Noticed the following example [here](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format):

```
SomeProject ==5.4 ; python_version < '2.7'
SomeProject; sys_platform == 'win32'
```
And this format works. Seems bit verbose to specify the constraints over multiple lines.

I'm using pip version `9.0.1`

**Comment by peterjc** [comment] 2017-02-01 16:55
I don't think the documentation means to suggest using multiple lines - I thought they were just multiple examples.

In any case, we don't really need to put a Python version restriction on the dependency for NumPy - the entirety of Biopython now requires Python 2.7 or later.

**Comment by peterjc** [comment] 2017-04-06 11:06
Hopefully fixed with 363bc0c8c080a1546271bf42e2cd8a456766a9b0 which adds a minimal ``requirements.txt`` as follows:

```
# We want NumPy under CPython or PyPy, but not Jython
numpy; platform_python_implementation != 'Jython'
```

Note since the above discussion we've confirmed our NumPy dependent code works under the latest PyPy release, see #953 

There is scope to add a ``requirements-dev.txt`` file which includes all the optional/soft dependencies (eg ``reportlab``) and other things we currently use for testing like ``flake8``.

**Closed by peterjc** 2017-04-06 11:06 UTC

**Comment by Cediddi** [comment] 2017-04-06 13:09
Oh, thank you. I believe with this last commit I can create a virtual environment and just run this command and it'll work.

    pip install biopython

**Comment by peterjc** [comment] 2017-04-06 13:13
This change hasn't yet been uploaded to PyPI (but it would be as part of Biopython 1.69), so for now you must probably still use:

```
pip install numpy
pip install biopython
```

**Comment by Cediddi** [comment] 2017-04-06 13:15
Thank you so so much. This'll really solve a big problem for me.

**Comment by peterjc** [comment] 2017-04-10 15:39
Now that Biopython 1.69 is out with a simple ``requirements.txt`` file, did it help?

**Comment by abdounasser202** [comment] 2017-04-10 15:56
cool!

**Comment by baraaorabi** [comment] 2017-06-29 13:47
So I just installed biopython without having numpy first, and I don't quite get how it fails midway then concludes by saying biopython installed successfully. I mean why do I need to reinstall it? I feel like many users would just ignore the failure message if the last message is "Successfully installed biopython-1.69
" only to have inexplicable running issues later:

```
orabi@orabi-Lemur:~$ pip3 install biopython
Collecting biopython
  Downloading biopython-1.69.tar.gz (15.4MB)
    100% |████████████████████████████████| 15.4MB 111kB/s 
Building wheels for collected packages: biopython
  Running setup.py bdist_wheel for biopython ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-aa7gspce/biopython/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpp4yruvm0pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  
  Numerical Python (NumPy) is not installed.
  
  This package is required for many Biopython features.  Please install
  it before you install Biopython. You can install Biopython anyway, but
  anything dependent on NumPy will not work. If you do this, and later
  install NumPy, you should then re-install Biopython.
  
  You can find NumPy at http://www.numpy.org
  
  
  ----------------------------------------
  Failed building wheel for biopython
  Running setup.py clean for biopython
Failed to build biopython
Installing collected packages: biopython
  Running setup.py install for biopython ... done
Successfully installed biopython-1.69
```

**Comment by peterjc** [comment] 2017-06-30 11:35
@baraaorabi It didn't fail - you have installed most of Biopython, just not the bits which need numpy. We should revisit this in light of recent changes in Biopython, see #1302.
