### ISSUE TITLE
How to use SeqIO's seqres-pdb parser for RNA

### ISSUE THREAD

**Issue by fteufel** [biopython/biopython#3788] opened 2021-11-09 21:39 UTC
I have a problem with extracting RNA sequences from PDB files. I do the following:

```
chains= SeqIO.parse('data/RNA/SPOT-RNA-1D/raw/1DDY.pdb', 'pdb-seqres')
for chain in chains:
    pass

chain
#SeqRecord(seq=Seq('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), id='1DDY:G', name='1DDY:G', description='PDB:1DDY 1DDY', dbxrefs=['PDB:1DDY', 'PDB:1DDY'])
```
The type also seems to have defaulted to protein.
```
chain.annotations
{'chain': 'G', 'molecule_type': 'protein'}

```

In the PDB file, things look ok.
```
SEQRES   1 A   35    G   G   A   A   C   C   G   G   U   G   C   G   C
SEQRES   2 A   35    A   U   A   A   C   C   A   C   C   U   C   A   G
SEQRES   3 A   35    U   G   C   G   A   G   C   A   A
SEQRES   1 C   35    G   G   A   A   C   C   G   G   U   G   C   G   C
SEQRES   2 C   35    A   U   A   A   C   C   A   C   C   U   C   A   G
SEQRES   3 C   35    U   G   C   G   A   G   C   A   A
SEQRES   1 E   35    G   G   A   A   C   C   G   G   U   G   C   G   C
SEQRES   2 E   35    A   U   A   A   C   C   A   C   C   U   C   A   G
SEQRES   3 E   35    U   G   C   G   A   G   C   A   A
```
How can I make this work for RNA sequences? I could not find any argument to control this.

**Comment by mdehoon** [comment] 2021-11-10 00:38
attn @peterjc 
It looks indeed like this is hardcoded for now in `Bio.SeqIO.PdbIO`:
```python
        # TODO: Test PDB files with DNA and RNA too:
        record.annotations["molecule_type"] = "protein"
```
Perhaps `1DDY` could be a good test case for RNA.

**Comment by peterjc** [comment] 2021-11-10 10:38
Yes, a known limitation - closing as a duplicate of #3125.

**Closed by peterjc** 2021-11-10 10:39 UTC
