### ISSUE TITLE
[Inquiry to retrieve the SEQRES from PDB file]

### ISSUE THREAD

**Issue by baehaeli** [biopython/biopython#4688] opened 2024-04-01 08:52 UTC
### Setup

I am reporting a problem with Biopython version 1.79, Python version 3.10, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

![image](https://github.com/biopython/biopython/assets/11719464/0c7b1b9d-2057-4662-bad1-72e6cea6347f)

### Expected behaviour

 I am attempting to retrieve the SEQRES from a PDB file using Biopython.

### Actual behaviour

 However, when I run the code, I am getting an incorrect sequence.

![image](https://github.com/biopython/biopython/assets/11719464/4401e66c-d006-4559-b308-a7752a204996)

I would greatly appreciate your assistance in resolving this issue and obtaining the correct sequence. Any guidance or support you can provide would be immensely helpful.

Thank you for your attention to this matter.

**Comment by peterjc** [comment] 2024-04-01 09:24
PDB code ``2lwk`` can be viewed at https://files.rcsb.org/view/2LWK.pdb and contains:

```
HEADER    RNA                                     01-AUG-12   2LWK              
TITLE     SOLUTION STRUCTURE OF SMALL MOLECULE-INFLUENZA RNA COMPLEX            
COMPND    MOL_ID: 1;                                                            
COMPND   2 MOLECULE: RNA (32-MER);                                              
COMPND   3 CHAIN: A;                                                            
COMPND   4 ENGINEERED: YES 
...
DBREF  2LWK A    1    32  PDB    2LWK     2LWK             1     32             
SEQRES   1 A   32    G   A   G   U   A   G   A   A   A   C   A   A   G          
SEQRES   2 A   32    G   C   U   U   C   G   G   C   C   U   G   C   U          
SEQRES   3 A   32    U   U   U   G   C   U                                      
HET    0EC  A 101      40               
...
```

Confirming behaviour:

```
$ wget https://files.rcsb.org/view/2LWK.pdb
$ python -c "import sys; from Bio import SeqIO; SeqIO.convert('2LWK.pdb','pdb-seqres', sys.stdout, 'fasta')"
>2LWK:A PDB:2LWK 2LWK
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

The ``SEQRES`` lines are not residues, but nucleotides. As per the ``COMPND`` lines, this is an RNA chain, not protein.

This is as documented, although perhaps an error or warning would help for non-protein chains:

```
    - pdb-seqres -  Reads a Protein Data Bank (PDB) file to determine the
      complete protein sequence as it appears in the header (no dependencies).
```

Closing as a duplicate of #3125.

**Comment by baehaeli** [comment] 2024-04-01 11:39
Thank you for your clarification.

Indeed, I am seeking to retrieve the complete RNA sequence utilized in the experiment. Given that the structure consists of nucleotides and represents an RNA chain, I am interested in exploring if there is a method within Biopython or any alternative approach to obtain the complete RNA sequence from the PDB file.

Your guidance on how to accomplish this using Biopython or any other relevant tools would be greatly appreciated.

Thank you for your assistance.

**Comment by peterjc** [comment] 2024-04-01 12:12
Well you could parse the SEQRES lines from the header (via the PDB parser), either DIY code or you might consider extending the code here to handle DNA and RNA:

https://github.com/biopython/biopython/blob/biopython-183/Bio/SeqIO/PdbIO.py#L113

I think it should look at the ``COMPND`` lines to tell if a chain is expected to be protein, RNA or RNA...

Or, you can look at the 3D structure but that would be more complicated.

**Comment by peterjc** [comment] 2024-04-11 12:33
Closing as a duplicate of #3125 (I evidently clicked the wrong button last time)

**Closed by peterjc** 2024-04-11 12:33 UTC
