### ISSUE TITLE
'CO' lines in EMBL files break SeqIO.convert

### ISSUE THREAD

**Issue by dbrami** [biopython/biopython#341] opened 2014-06-19 23:11 UTC
The following error is raised:
  File "/sgi/asmopt/python27/lib/python2.7/site-packages/Bio/GenBank/Scanner.py", line 405, in feed
    misc_lines, sequence_string = self.parse_footer()
  File "/sgi/asmopt/python27/lib/python2.7/site-packages/Bio/GenBank/Scanner.py", line 558, in parse_footer
    or self.line.strip() == '//', repr(self.line)
AssertionError: 'XX'

Currently, work-around is to remove these lines from EMBL files

**Comment by kblin** [comment] 2015-07-09 10:31
As far as I can see in ftp://ftp.ebi.ac.uk/pub/databases/embl/doc/usrman.txt there is no "CO" line defined in the EMBL format. So this EMBL file seems invalid. I'll try and make the error message more obvious about this.

**Comment by kblin** [comment] 2015-07-09 10:42
Ah, or my Ctrl-F-skill are failing me. There it is, of course. :)

**Comment by kblin** [comment] 2015-07-09 12:57
So the error message does happen if a CO line appears before the FT table.  So still room for improving the error message.

**Comment by peterjc** [comment] 2018-07-04 15:12
Unless someone can provide a test case (e.g. an EMBL accession), I think we can close this old issue...

**Comment by reederz** [comment] 2018-07-10 12:00
@peterjc can we re-open the issue? accession CM004508 (first record in ftp://ftp.ebi.ac.uk/pub/databases/embl/expanded_con/new/cum_exp_con_fun_01_r137.dat.gz) has CO line.

Stacktrace trying to parse:
```
  File "/virtual_envs/20180710T104810/Ubuntu16.04/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 447, in feed
    misc_lines, sequence_string = self.parse_footer()
  File "/virtual_envs/20180710T104810/Ubuntu16.04/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 609, in parse_footer
    or self.line.strip() == '//', "Unexpected content after SQ or CO line: %r" % self.line
AssertionError: Unexpected content after SQ or CO line: 'XX'
```

BioPython version: 1.7.0

**Comment by peterjc** [comment] 2018-07-10 12:12
Certainly - especially as you provided a test case 👍

**Comment by kblin** [comment] 2018-07-10 13:14
Can't reproduce with https://www.ebi.ac.uk/Tools/dbfetch/dbfetch?db=embl&id=CM004508&style=raw

**Comment by reederz** [comment] 2018-07-10 13:17
The link you've provided contains different data to that in the dat file I linked. Here's what I have: 
[CM004508.dat.gz](https://github.com/biopython/biopython/files/2180482/CM004508.dat.gz)

**Comment by reederz** [comment] 2018-07-10 13:23
I'll paste it in here too (without sequence):
```
ID   CM004508; SV 1; circular; genomic DNA; CON; FUN; 77649 BP.
XX
AC   CM004508; MAQV01000000;
XX
PR   Project:PRJNA326057;
XX
DT   02-JUL-2018 (Rel. 137, Created)
DT   02-JUL-2018 (Rel. 137, Last updated, Version 0)
XX
DE   Aspergillus cristatus strain YKY807 mitochondrion, complete sequence, whole
DE   genome shotgun sequence.
XX
KW   .
XX
OS   Aspergillus cristatus
OC   Eukaryota; Fungi; Dikarya; Ascomycota; Pezizomycotina; Eurotiomycetes;
OC   Eurotiomycetidae; Eurotiales; Aspergillaceae; Aspergillus.
OG   Mitochondrion
XX
RN   [1]
RP   1-77649
RA   Liu F., Yuan C., Yuan D., Zhang J., Wang M., Zhu X.;
RT   "Extraction, sequencing and analysis of the whole genome of Eurotium
RT   cristatum";
RL   Unpublished.
XX
RN   [2]
RP   1-77649
RA   Liu F.;
RT   ;
RL   Submitted (21-JUN-2016) to the INSDC.
RL   Shandong Academy of Pharmaceutical Sciences, Xinluodajie, Jinan, Shandong
RL   250101, China
XX
DR   MD5; 603627cd527641159771921d7c1c2f51.
DR   ENA; MAQV01000000; SET.
DR   ENA; MAQV00000000; SET.
DR   BioSample; SAMN05257104.
XX
CC   ##Genome-Assembly-Data-START##
CC   Assembly Method        :: PBcR v. 8.3; Newbler v. 2.8
CC   Genome Representation  :: Full
CC   Expected Final Version :: Yes
CC   Genome Coverage        :: 100.0x
CC   Sequencing Technology  :: PacBio RS II; Illumina MiSeq
CC   ##Genome-Assembly-Data-END##
XX
CO   join(MAQV01000012.1:1..77649)
XX
FH   Key             Location/Qualifiers
FH
FT   source          1..77649
FT                   /organism="Aspergillus cristatus"
FT                   /organelle="mitochondrion"
FT                   /strain="YKY807"
FT                   /mol_type="genomic DNA"
FT                   /country="China:Hunan Province"
FT                   /isolation_source="dark tea produced by Hunan Weichu Freda
FT                   Bio-Technology Co., Ltd."
FT                   /collection_date="2015-05-06"
FT                   /db_xref="taxon:573508"
XX
SQ ...
```

**Comment by kblin** [comment] 2018-07-10 13:30
Note that this is the diff between the record I linked and the record from @reederz:

```diff
--- CM004508.embl       2018-07-10 15:12:34.196437184 +0200
+++ CM004508.dat        2018-07-10 15:22:06.466682081 +0200
@@ -4,8 +4,8 @@
 XX
 PR   Project:PRJNA326057;
 XX
-DT   06-JUL-2018 (Rel. 137, Created)
-DT   06-JUL-2018 (Rel. 137, Last updated, Version 1)
+DT   02-JUL-2018 (Rel. 137, Created)
+DT   02-JUL-2018 (Rel. 137, Last updated, Version 0)
 XX
 DE   Aspergillus cristatus strain YKY807 mitochondrion, complete sequence, whole
 DE   genome shotgun sequence.
@@ -45,6 +45,8 @@
 CC   Sequencing Technology  :: PacBio RS II; Illumina MiSeq
 CC   ##Genome-Assembly-Data-END##
 XX
+CO   join(MAQV01000012.1:1..77649)
+XX
 FH   Key             Location/Qualifiers
 FH
 FT   source          1..77649
@@ -58,5 +60,1300 @@
 FT                   /collection_date="2015-05-06"
 FT                   /db_xref="taxon:573508"
 XX
-CO   join(MAQV01000012.1:1..77649)
+SQ   Sequence 77649 BP; 26510 A; 12119 C; 9791 G; 29229 T; 0 other;
```
Notably, the `CO` line moved to after the feature table in the newer version.

**Comment by reederz** [comment] 2018-07-10 13:31
Maybe true but for what it's worth, I can find quite a few examples of feature table coming after CO.

**Comment by peterjc** [comment] 2018-07-10 13:31
So the FTP site version breaks, but dbfetch via the website is fine?

**Comment by kblin** [comment] 2018-07-10 13:31
Having said that, it looks like we're not treating `XX` lines like we should according to the manual.

**Comment by kblin** [comment] 2018-07-10 13:33
Yeah. I think they noticed they broke stuff, seeing how they released a version 1 four days after the version 0 that is on the FTP site.

**Comment by peterjc** [comment] 2018-07-10 13:35
That would make sense, in  ftp://ftp.ebi.ac.uk/pub/databases/embl/doc/usrman.txt  section *"3.4.14 The CO Line (in CON records only)"* clearly has the ``CO`` line after the feature table.

Does it seem like there was a glitch at the EBI releasing some files with CO before the FH and FT lines?

**Comment by kblin** [comment] 2018-07-10 13:43
Yes. And fixing this on our side is really non-trivial, as hitting a sequence start marker like `CO` or `SQ` sends our state machine into the "parse the sequence now" mode.

**Comment by peterjc** [comment] 2018-07-10 13:46
I would agree, the nature of the parser structure makes this a bit awkward to deal with.

I'm hoping the EBI sort this out, and the problem goes away - but if anyone can see an elegant fix I'll look at it for potential merging.

**Comment by peterjc** [comment] 2020-03-25 09:43
Closing on the assumption that the EBI did indeed resolve this.

**Closed by peterjc** 2020-03-25 09:43 UTC
Labels: Bug
