### ISSUE TITLE
Blastxml parser ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by breviata** [biopython/biopython#556] opened 2015-06-03 14:19 UTC
I'm running into a problem with the SearchIO xml blast parser. I'm analyzing thousands of files with 50 blast results per file. The script works on about 10k sequences and then I get an error on this one file. If I pass the error, I get about 1000 similar cases of the script failing. (CC @peterjc @bow ) 

**ERROR**

```Traceback (most recent call last):
  File "/home/cstairs/SOFTWARE/MitoPipe_Apr2015_faster2.py", line 464, in <module>
    for blast_record in blast_records:
  File "/opt/perun/python_packages/lib/python2.7/site-packages/Bio/SearchIO/__init__.py", line 316, in parse
    for qresult in generator:
  File "/opt/perun/python_packages/lib/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 198, in __iter__
    for qresult in self._parse_qresult():
  File "/opt/perun/python_packages/lib/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 294, in _parse_qresult
    query_id):
  File "/opt/perun/python_packages/lib/python2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 395, in _parse_hit
    [a.split(' ', 1) for a in full_id_desc.split(' >')]]
ValueError: need more than 1 value to unpack```

**BIOPYTHON MODULE LINE THAT IS FAILING**

```id_descs = [(x.strip(), y.strip()) for x, y in
            		[a.split(' ', 1) for a in full_id_desc.split(' >')]]```

**LINK TO BLAST OUTPUT FILE**

[OUTPUT file] (https://drive.google.com/file/d/0B8CzGBmKCzfgS2F5eWZKYXJyVDg/view)
Offending sequence: TR7258zzzc0_g2_i1_4

**Comment by peterjc** [comment] 2015-06-03 14:26
Thanks @breviata - the sample XML file should be really useful here.

@bow - are you able to take a look at this?

**Comment by breviata** [comment] 2015-06-03 14:29
Hi Peter, There's a URL in that post, since it was too big. [Here again] (https://drive.google.com/file/d/0B8CzGBmKCzfgS2F5eWZKYXJyVDg/view) Let me know if permissions are not working.

**Comment by peterjc** [comment] 2015-06-03 14:40
Good news, I could download the file ``q48651.xml``, and reproduce the exception.

I could parse it using the older ``NCBIXML`` module:

```
from Bio.Blast import NCBIXML
with open("q48651.xml") as handle:
    for record in NCBIXML.parse(handle):
        print(record.query_id)
```

Giving:

```
$ python bug556_ncbixml.py 
Query_1
Query_2
Query_3
...
Query_50
```

Of course, from the exception, we are looking for a problem in @bow's newer ``SearchIO`` module:

```
from Bio import SearchIO
for record in SearchIO.parse("q48651.xml", "blast-xml"):
    print(record.id)
```

```
$ python bug556_searchio.py 
/Library/Python/2.7/site-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
a211997zzz9_0
TR272zzzc0_g2_i1_4
TR17385zzzc0_g1_i1_4
TR17385zzzc0_g1_i1_5
TR23479zzzc0_g2_i1_4
TR13567zzzc0_g1_i1_0
TR13567zzzc0_g1_i1_1
TR2796zzzc0_g2_i1_0
TR7258zzzc0_g2_i1_2
TR7258zzzc0_g2_i1_3
a1208zzz5_3
Traceback (most recent call last):
  File "bug556_searchio.py", line 2, in <module>
    for record in SearchIO.parse("q48651.xml", "blast-xml"):
  File "/Library/Python/2.7/site-packages/Bio/SearchIO/__init__.py", line 316, in parse
    for qresult in generator:
  File "/Library/Python/2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 198, in __iter__
    for qresult in self._parse_qresult():
  File "/Library/Python/2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 294, in _parse_qresult
    query_id):
  File "/Library/Python/2.7/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 395, in _parse_hit
    [a.split(' ', 1) for a in full_id_desc.split(' >')]]
ValueError: need more than 1 value to unpack
```

Something is breaking with the clever query name detection...

**Comment by breviata** [comment] 2015-06-03 14:47
Yep, thats the error I get too.. I did do some tweaking of the blastxml.py and added an 'try'/'except' - I'm in the processes up installing this on our cluster so i can see if it messes up later functions of my blast parsing pipeline  - I'll report back if it works.

Alternatively I can just go back to the old parser! But I really would like to use the ```SearchIO``` module.

**Comment by bow** [comment] 2015-06-06 09:58
Hi @breviata and @peterjc,

Thanks for reporting the error. I'm looking at this now, I could reproduce the bug when using Python 2.7.9, and 3.3.5 as well.

Looking deeper into the file, I found that the error is caused the parser is trying to parse hit `gi|4966357|gb|AAD34688.1|AC006341_16`. because the hit description starts with (an unexpected) `>`: `>F3O9.16 [Arabidopsis thaliana]`.

The fix itself is simple to make, but I need to check first why the parser splits on ` >`. I did make one change earlier on this part as well (27b3cfd9cc3ddcbc), though apparently some files still breaks this now..

**Comment by peterjc** [comment] 2015-06-06 15:41
Regarding 27b3cfd9cc3ddcbc6d8599d6edb49e858d71c490 splitting on the ``>`` in the description has always been fragile, `` >`` (space, greater than) is better but still not perfect. This has always been fragile, I'm sure we had an in-depth discussion on a GitHub issue, I'll post back with the link if i find it - see also https://github.com/peterjc/galaxy_blast/commit/5210af6622bf905ecb09ffbf6d7d348cfe015dc3

Looking at the snippet:

```
<Hit>
  <Hit_num>215</Hit_num>
  <Hit_id>gi|4966357|gb|AAD34688.1|AC006341_16</Hit_id>
  <Hit_def>&gt;F3O9.16 [Arabidopsis thaliana]</Hit_def>
  <Hit_accession>AAD34688</Hit_accession>
  <Hit_len>353</Hit_len>
  <Hit_hsps>
...
```

I think this this a corner case where the first ID does not have any description following it?

**Comment by bow** [comment] 2015-07-08 11:50
@peterjc Yes, this is that corner case.

I think I have a sensible fix (referenced here soon), which changes the simple string splitting logic to using regexes (so we can accomodate multiple whitespaces). The one thing it relies on now is that each ID (primary or otherwise) must start with a `>` character. I think this should be more robust compared to what we have now.

P.S. Apologies for the delay by the way, I was getting caught up with other obligations and since I now have two days full for working on this, I can start taking care of all backlogs :).

**Comment by bow** [comment] 2015-07-08 12:58
Ok, fix is up and all unit tests are passing.

**Comment by breviata** [comment] 2015-07-08 13:22
Awesome thanks!!!!

**Comment by peterjc** [comment] 2015-07-08 13:33
That's on the master branch now - @breviata are you able to install Biopython from source to double check this solved your original problem?

**Comment by bow** [comment] 2015-12-21 17:07
Shall we close this issue? Unless @breviata still encounters problems with the current fix :).

**Comment by peterjc** [comment] 2015-12-21 19:04
OK - closing but feel free to reopen if there is still a problem. Thanks all.

**Closed by peterjc** 2015-12-21 19:04 UTC
