### ISSUE TITLE
Failed to install biopython on Windows

### ISSUE THREAD

**Issue by NetizenCCS** [biopython/biopython#4896] opened 2024-12-16 02:54 UTC
Collecting biopython==1.84
  Using cached biopython-1.84.tar.gz (25.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in c:\python\python 3.13.0\lib\site-packages (from biopython==1.84) (2.1.3)
Building wheels for collected packages: biopython
  Building wheel for biopython (setup.py): started
  Building wheel for biopython (setup.py): finished with status 'error'
  Running setup.py clean for biopython
Failed to build biopython

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1

python version:3.13.0

**Comment by peterjc** [comment] 2024-12-16 09:19
I don't know why your build failed, but it only attempted to build from source because we don't yet have a pre-compiled wheel for Biopython on Python 3.13.

For the short term, stick with an older Python. I hope to do a release next week (while my employee is shut for the Christmas break).

Closing as a duplicate of #4883

**Closed by peterjc** 2024-12-16 09:19 UTC
