### ISSUE TITLE
ResidueDepth fails on Windows

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#1140] opened 2017-04-08 18:36 UTC
Related to a question posted on the users mailing list, quoted below:

>AssertionError: Failed to generate surface file using command:msms -probe_radius 1.5 -

Running the code on Windows 10 with the latest available MSMS executable fails because of the code calls a BASH script. This script - `pdb_to_xyzr` - seems to be mapping atom names to radii, so we might be able to add those as a table to the ResidueDepth module and have full Windows compatibility.

**Comment by peterjc** [comment] 2017-04-08 18:51
I wonder if the Linux subsystem for Windows 10 would fix this for us?

**Comment by JoaoRodrigues** [comment] 2017-04-08 18:56
The msms executable wouldn't run there then, nor we would have access to
the Windows' Biopython installation. I'm looking at the files, seems to be
a simple fix if I write a parsing function that replaces the BASH script.

**Comment by underOATH777** [comment] 2017-04-15 20:18
Hi, when is this going to be fixed?

**Comment by peterjc** [comment] 2017-04-15 21:00
@underOATH777 we don't know. Would you like to help? Do you have access to a Windows machine and any experience with the MSMS tool?

**Comment by underOATH777** [comment] 2017-04-15 21:06
I definitely would, if I could. My work depends on this. I'm even thinking of installing Ubuntu just to get it done. However not being very familiar with Linux systems is holding me back a little. Do you think I'm better off waiting for a fix, or should I just take the red pill and embark on a Linux adventure?

**Comment by JoaoRodrigues** [comment] 2017-04-16 00:03
On this today, expect a PR in a couple of hours. I changed machines
recently and had to go through the trouble of getting my compiler chain/git
working correctly before doing any work!

On the other hand, getting a Virtual Machine with Linux wouldn't hurt,
since a lot of programs just bail when it comes to supporting Windows.. Or,
try the new WSL (Bash on Windows). I've had mixed success with compilations
there, but I could get CNS (old FORTRAN code) running there so anything
written after 1995 *might* work :)

**Comment by underOATH777** [comment] 2017-04-16 04:42
Thanks a lot for your input and efforts. I'm waiting eagerly for the "patch release", if that's what PR means. Cheers. :D

**Comment by JoaoRodrigues** [comment] 2017-04-16 05:35
@underOATH777 I successfully ran MSMS here on my Win 64 machine and it seems to give proper values for radii (compared to the original BASH script). When the pull gets accepted and merged, can you download the latest version of Biopython (from Git) and test if it works on your end as well?

**Comment by underOATH777** [comment] 2017-04-16 05:37
Of course, I'd be happy to. :)

**Comment by underOATH777** [comment] 2017-04-16 08:10
Joao passed me the code, and I conform it works for me as well. He did a fantastic job. Thanks a lot. Great work. Keep it up guys.

**Comment by chebizarro** [comment] 2020-07-21 23:41
The patch has been merged and confirmed to work under Win64, can we go ahead and close this issue or does it need more testing?

**Comment by peterjc** [comment] 2020-07-22 07:26
It sounds like it has been independently tested, so yes - let's close it. Thank you all!

**Closed by peterjc** 2020-07-22 07:26 UTC
Labels: Bug
