### ISSUE TITLE
Fails to build with python3.6 on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [biopython/biopython#1649] opened 2018-05-13 22:03 UTC
```
===>  Configuring for py36-biopython-1.71_1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 435, in <module>
    readme_rst = handle.read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7116: ordinal not in range(128)
```

**Comment by peterjc** [comment] 2018-05-13 23:07
There were some funny quotes in the README.rst file, the simple fix is to remove them as in https://github.com/biopython/biopython/commit/6421d365a511c0de71748737ba6e1cd8518658ac (or just replace it with an empty file).

Closing as a duplicate of #1600, see also long term fix in #1607. Sorry about this.

**Closed by peterjc** 2018-05-13 23:07 UTC
