### ISSUE TITLE
Alphabets issue with Bio.motifs.create

### ISSUE THREAD

**Issue by tbrailov** [biopython/biopython#1381] opened 2017-08-30 19:16 UTC
### Setup

3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, 12:15:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
CPython
Darwin-15.6.0-x86_64-i386-64bit
1.68

### Expected behavior

I expect my code to generate a Motif() object with specified instances. 

### Actual behavior

When trying to create a motif object from amino acid sequences with Bio.Alphabets.ProteinAlphabet() alphabet, I get 

```
        32         # create a new motif object
---> 33         new_m = Bio.motifs.create(new_seqs, Bio.Alphabet.ProteinAlphabet())

/Users/Smidge/anaconda/lib/python3.5/site-packages/Bio/motifs/__init__.py in create(instances, alphabet)
     22 
     23 def create(instances, alphabet=None):
---> 24     instances = Instances(instances, alphabet)
     25     return Motif(instances=instances, alphabet=alphabet)
     26 
```

```
/Users/Smidge/anaconda/lib/python3.5/site-packages/Bio/motifs/__init__.py in __init__(self, instances, alphabet)
    171                 alphabet = a
    172             elif alphabet != a:
--> 173                 raise ValueError("Alphabets are inconsistent")
    174         if alphabet is None or alphabet.letters is None:
    175             # If we didn't get a meaningful alphabet from the instances,

ValueError: Alphabets are inconsistent
```

### Steps to reproduce

I am trying to construct motif objects from amino acid sequences. I do so by first creating a list new_seqs of Seq objects with the appropriate sequence and Bio.Alphabet.ProteinAlphabet() alphabet. Then I call Bio.motifs.create(new_seqs, Bio.ProteinAlphabet())  to create the motif object. 

From the error messages, I believe the problem arises in a for-loop within the constructor of the Bio.motifs.Instances() class in lines 155-169. This chunk of code verifies that all instances provided are the same length and have the same alphabet. The issue is that alphabet equality is tested as follows:

if alphabet is None: 
167                  alphabet = a 
168              elif alphabet != a: 
169                  raise ValueError("Alphabets are inconsistent") 

where 
162  a = instance.alphabet 
is done at each iteration of the for loop and alphabet (as in line 167) is just an argument supplied to the constructor of Instances() class. In my case, a is always Bio.Alphabet.ProteinAlphabet() and alphabet is Bio.Alphabet.ProteinAlphabet(). So clearly my alphabets are consistent. I have a suggestion for how this may be fixed - in line 168 write:
168 elif alphabet.__repr__() != a.__repr__() 

Thanks, 
Tatiana

**Comment by peterjc** [comment] 2017-08-30 20:51
Can you share more of your code? i.e. what is ``new_seqs`` here?

One suggested workaround is to pass the exact same instance of the alphabet as you used in the sequence construction. In this case, probably all you need to do is replace every use of ``Bio.Alphabet.ProteinAlphabet()`` with ``Bio.Alphabet.generic_protein`` which is a pre-instantiated instance of that class.

But yes, the alphabet comparison in this code does seem overly restrictive. Probably all it needs to check is everything is DNA/RNA/Protein, and that the letters match. Cross reference #566.

It would be nice if when providing sequences the alphabet was deduced from them (much like how our multiple sequence alignment object does it, which may be a good model to follow here).

**Comment by servalli** [comment] 2019-07-31 17:30
I have edited your example to simulate protein sequences, no other changes:
```
from Bio.Alphabet import generic_protein
from Bio.Seq import Seq
from Bio import motifs
s1 = Seq("ALSY", generic_protein)
s2 = Seq("AISY", generic_protein)
m=motifs.create(instances=[s1,s2], alphabet=generic_protein)
```
It throws the same error as not stating an alphabet:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-1e1773ca4ea4> in <module>
      4 s1 = Seq("ALSY", generic_protein)
      5 s2 = Seq("AISY", generic_protein)
----> 6 m=motifs.create(instances=[s1,s2], alphabet=generic_protein)

~/anaconda3/lib/python3.6/site-packages/Bio/motifs/__init__.py in create(instances, alphabet)
     21 def create(instances, alphabet=None):
     22     instances = Instances(instances, alphabet)
---> 23     return Motif(instances=instances, alphabet=alphabet)
     24 
     25 

~/anaconda3/lib/python3.6/site-packages/Bio/motifs/__init__.py in __init__(self, alphabet, instances, counts)
    242             self.instances = instances
    243             alphabet = self.instances.alphabet
--> 244             counts = self.instances.count()
    245             self.counts = matrix.FrequencyPositionMatrix(alphabet, counts)
    246             self.length = self.counts.length

~/anaconda3/lib/python3.6/site-packages/Bio/motifs/__init__.py in count(self)
    197         for instance in self:
    198             for position, letter in enumerate(instance):
--> 199                 counts[letter][position] += 1
    200         return counts
    201 

KeyError: 'L'
```
If the alphabet is stated as generic_protein, but sequences only contain A|T|G|C, it works. Generic_rna with "U" symbols fails.
**Looks like DNA alphabet is hardcoded somewhere in the count() function**
if I replace alphabet=generic_protein with ProteinAlphabet the comparison fails.
Is there any way to get motifs working with proteins?

**Comment by mdehoon** [comment] 2019-08-01 01:25
Let's get back to this issue once we drop alphabets from Biopython (in 2020).

**Comment by peterjc** [comment] 2019-08-01 08:52
So do you recommend RNA users explicitly convert to DNA as a work around?

**Comment by mdehoon** [comment] 2019-08-01 09:22
The problem, as always, is in `Bio.Alphabet`:
```
>>> from Bio.Alphabet import generic_protein
>>> print(generic_protein.letters)
None
>>> from Bio.Alphabet import ProteinAlphabet
>>> print(ProteinAlphabet().letters)
None
```

**Comment by servalli** [comment] 2019-08-01 09:36
```
>>> from Bio.Alphabet import generic_dna, generic_alphabet
>>> print(generic_protein.letters)
None
>>> print(generic_alphabet.letters)
None
```
Ok, now I am definitely puzzled with this, `generic_dna` shouldn't be working with motifs, but it works

**Comment by mdehoon** [comment] 2019-08-01 09:41
@servalli  It works because Bio.motifs defaults to DNA if no usable alphabet is provided.

**Comment by peterjc** [comment] 2019-08-01 10:48
All the generic Alphabet objects have ``.letters = None``, the IUPAC Alphabet objects set this attribute.

**Comment by peterjc** [comment] 2020-07-24 21:02
Given the work already done for removing internal use of ``Bio.Alphabet``, is this resolved on the master branch now? i.e. Can we close this issue?

**Comment by mdehoon** [comment] 2020-07-25 01:52
This particular issue can be closed. The following works:
```
from Bio.Data import IUPACData
from Bio.Seq import Seq
from Bio import motifs
s1 = Seq("ALSY")
s2 = Seq("AISY")
m=motifs.create(instances=[s1,s2], alphabet=IUPACData.protein_letters)
>>> print(m)
ALSY
AISY

```
but I am not sure now how useful the `Bio.motifs` module will be for protein sequences as it was designed for DNA.

**Closed** 2020-07-25 01:52 UTC
