### ISSUE TITLE
SwissProt.parse method cannot handle UniProt *dat files after the Aug 3 2022 UniProt update

### ISSUE THREAD

**Issue by gildossantos** [biopython/biopython#4078] opened 2022-09-09 15:47 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

>>> import Bio; print(Bio.__version__)
1.79

>>> import platform; print(platform.python_implementation()); print(platform.platform())
3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]

>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.15.0-47-generic-x86_64-with-glibc2.35

### Expected behaviour

I'm using the SwissProt module to parse *.dat download files from UniProt. For example:
https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/uniprot_sprot_invertebrates.dat.gz

I typically use this code to get a list of SwissProt records:
```
uniprot_entries = list(SwissProt.parse(filename))
```
It all works fine and I can access content from each individual record. For example, I run this:
```
print(uniprot_entries[0].cross_references)
```
That gives me something like this:
```
[('EMBL', 'CR940353', 'CAI76474.1', '-', 'Genomic_DNA'), ('RefSeq', 'XP_953099.1', 'XM_948006.1'), ('AlphaFoldDB', 'Q4U9M9', '-'), ('GeneID', '3863060', '-'), ('KEGG', 'tan:TA08425', '-'), ('VEuPathDB', 'PiroplasmaDB:TA08425', '-'), ('eggNOG', 'ENOG502RY34', 'Eukaryota'), ('InParanoid', 'Q4U9M9', '-'), ('OMA', 'NGHICKM', '-'), ('OrthoDB', '1492494at2759', '-'), ('Proteomes', 'UP000001950', 'Chromosome 4'), ('GO', 'GO:0031225', 'C:anchored component of membrane', 'IEA:UniProtKB-KW'), ('GO', 'GO:0005886', 'C:plasma membrane', 'IEA:UniProtKB-SubCell')]
```

### Actual behaviour

I now get this error, which suggests to me that there are no records parsed.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gil/.local/lib/python3.10/site-packages/Bio/SwissProt/__init__.py", line 239, in parse
    record = _read(handle)
  File "/home/gil/.local/lib/python3.10/site-packages/Bio/SwissProt/__init__.py", line 371, in _read
    _read_ft(record, line)
  File "/home/gil/.local/lib/python3.10/site-packages/Bio/SwissProt/__init__.py", line 830, in _read_ft
    key = keys[-1]
IndexError: list index out of range
```
### Steps to reproduce

Download this file:
https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/uniprot_sprot_invertebrates.dat.gz

```
python3
from Bio import SwissProt
uniprot_entries = list(SwissProt.modules(<filename>)
```

### Causes
Writing to UniProt, they mentioned that they updated their protein binding annotations in the *dat files.
https://www.uniprot.org/release-notes/2022-08-03-release
"Annotation of biologically relevant ligands in UniProtKB using ChEBI" - maybe this is the problem?

When I remove the lines that begin with `FT   ` from the input files, the SwissProt module works again.

**Comment by JoaoRodrigues** [comment] 2022-09-09 16:09
This is very likely related to #4021 and has been fixed in the master branch. @peterjc, we should maybe consider doing a release? (and maybe revisiting the release schedule?)

**Comment by gildossantos** [comment] 2022-09-09 16:32
Thanks!

**Comment by peterjc** [comment] 2022-09-09 16:49
Yes, I agree its probably a duplicate of #4021. And yes, a release would be good - we need to check the Bio.Align work has settled down.

If the latest code from GitHub doesn't fix this, please comment or reopen the issue. Thanks!

**Closed by peterjc** 2022-09-09 16:49 UTC

**Comment by mdehoon** [comment] 2022-09-10 00:02
> And yes, a release would be good - we need to check the Bio.Align work has settled down.

While there will be more updates to `Bio.Align` in the future, I don't think the release will have to wait for it.
