### ISSUE TITLE
"No such file or directory" error by Bio.PDB.DSSP

### ISSUE THREAD

**Issue by rraadd88** [biopython/biopython#757] opened 2016-01-25 20:23 UTC
I have 1MOT.pdb in the working directory. When I run the example bit taken from [here](http://biopython.org/DIST/docs/api/Bio.PDB.DSSP%27.DSSP-class.html). 

<pre><code>
p = PDBParser()
structure = p.get_structure("1MOT", "1MOT.pdb")
model = structure[0]
dssp = DSSP(model, "1MOT.pdb")
</code></pre>

I get this error :

<pre><code>
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-12-e056ad12049f> in <module>()
----> 1 dssp = DSSP(model, "1MOT.pdb")

/lib/python2.7/site-packages/Bio/PDB/DSSP.pyc in __init__(self, model, pdb_file, dssp)
    252         """
    253         # create DSSP dictionary
--> 254         dssp_dict, dssp_keys = dssp_dict_from_pdb_file(pdb_file, dssp)
    255         dssp_map = {}
    256         dssp_list = []

/lib/python2.7/site-packages/Bio/PDB/DSSP.pyc in dssp_dict_from_pdb_file(in_file, DSSP)
    107     # gives unicode handles rather than bytes handles.
    108     p = subprocess.Popen([DSSP, in_file], universal_newlines=True,
--> 109                          stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    110     out, err = p.communicate()
    111 

/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    708                                 p2cread, p2cwrite,
    709                                 c2pread, c2pwrite,
--> 710                                 errread, errwrite)
    711         except Exception:
    712             # Preserve original exception in case os.close raises.

/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1333                         raise
   1334                 child_exception = pickle.loads(data)
-> 1335                 raise child_exception
   1336 
   1337 

OSError: [Errno 2] No such file or directory 
</code></pre>

Any help?
My guess is this bit in DSSP.py 
</code></pre>
    # Using universal newlines is important on Python 3, this
    # gives unicode handles rather than bytes handles.
</code></pre>
which is causing the problem but not sure why.

**Comment by peterjc** [comment] 2016-01-25 22:13
Good guess, but I think that here ``No such file or directory`` is referring to the DSSP command line tool. You probably need to install DSSP.

Do you have the command line tool DSSP installed and on the ``$PATH``? You can check at the command line prompt with:

```
$ which dssp
```

If the binary is not on your ``$PATH`` then you have to tell Biopython how to find the tool using the third optional argument ot the ``DSSP(....)`` class, be giving the path to the binary, e.g.

```
dssp = DSSP(model, "1MOT.pdb", dssp="/home/rradd/bin/dssp")
```

**Comment by JoaoRodrigues** [comment] 2016-01-25 22:19
@peterjc is (most probably) right. This is most likely caused by the DSSP executable not being present in the PATH. You can download DSSP from [here](http://swift.cmbi.ru.nl/gv/dssp/) and then point to the executable using the third optional argument.

**Comment by rraadd88** [comment] 2016-01-26 07:08
@peterjc, @JoaoRodrigues
As you said, I downloaded [dssp-2.0.4-linux-amd64](http://swift.cmbi.ru.nl/gv/dssp/) executables and used the third optional argument.

<pre><code>
dssp = DSSP(model, "1MOT.pdb", dssp="/path/dssp-2.0.4-linux-amd64")
</code></pre>

May be if possible, modifying the error message would be very helpful before somebody else also stucks there.
Thanks a lot for the help.

**Comment by JoaoRodrigues** [comment] 2016-01-26 07:14
Glad it worked. I'll add a small patch to make this error more verbose.
Thanks!

2016-01-25 23:09 GMT-08:00 Rohan Dandage <notifications@github.com>:

**Comment by peterjc** [comment] 2016-01-26 09:35
Its a shame ``OSError: [Errno 2] No such file or directory`` itself doesn't include the filename, but that is likely Linux / Mac OS / POSIX / etc to blame rather than Python.

Anyway, glad this is working for you now, closing issue.

**Closed by peterjc** 2016-01-26 09:35 UTC

**Comment by hacertilbec** [comment] 2018-08-20 20:26
Hi, I have the same problem. I downloaded dssp and added path variable.
`➜ which dssp
/usr/local/bin/dssp`

`➜  echo $PATH
/usr/local/bin/dssp:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`


Still I'm getting this error:
`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-26-2f86b0592228> in <module>()
      1 from Bio.PDB import DSSP
----> 2 dssp = DSSP(model, "1a02.pdb", dssp="/usr/local/bin/dssp")

/usr/local/lib/python2.7/site-packages/Bio/PDB/DSSP.pyc in __init__(self, model, in_file, dssp, acc_array, file_type)
    352             # (Debian distribution of DSSP includes a symlink for 'dssp' argument)
    353             try:
--> 354                 dssp_dict, dssp_keys = dssp_dict_from_pdb_file(in_file, dssp)
    355             except OSError:  # TODO: Use FileNotFoundError once drop Python 2
    356                 if dssp == 'dssp':

/usr/local/lib/python2.7/site-packages/Bio/PDB/DSSP.pyc in dssp_dict_from_pdb_file(in_file, DSSP)
    185             raise
    186         p = subprocess.Popen(["mkdssp", in_file], universal_newlines=True,
--> 187                              stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    188     out, err = p.communicate()
    189 

/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    392                                 p2cread, p2cwrite,
    393                                 c2pread, c2pwrite,
--> 394                                 errread, errwrite)
    395         except Exception:
    396             # Preserve original exception in case os.close raises.

/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1045                         raise
   1046                 child_exception = pickle.loads(data)
-> 1047                 raise child_exception
   1048 
   1049 

OSError: [Errno 20] Not a directory`

**Comment by peterjc** [comment] 2018-08-21 15:34
Your error looks different, a new issue report might have been better.

Is ``mkdssp`` installed and on your path, or just ``dssp``? This is tried as a fall back if the suggested name did not work (to cope with the tool being renamed). One might be a symlink to the other...
