### ISSUE TITLE
Enhanced SeqRecord slicing to optionally give truncated partial features?

### ISSUE THREAD

**Issue by linuxonly801** [biopython/biopython#3194] opened 2020-08-03 09:30 UTC
### Setup

I am reporting a problem with Biopython version 1.77, Python version 3.6.4, and operating
system Win10 as follows:

```python
from Bio import SeqIO

Cd6_gene = SeqIO.read('Cd6 gene.gb', 'genbank')
Cd6_gene_exon2_6 = Cd6_gene[29683:33721]

Cd6_gene_exon2_6.features = Cd6_gene.features.copy()
SeqIO.write(Cd6_gene_exon2_6, 'Cd6_gene_exon2_6.gb', 'genbank')
```
[Cd6 gene.txt](https://github.com/biopython/biopython/files/5015041/Cd6.gene.txt)
(Because gb file is not supported, I renamed the file to txt) 

### Expected behaviour

I am expecting the output file to contain correct labeled exons.

### Actual behaviour

But the file generated contains wrongly labeled features.
[Cd6_gene_exon2_6.txt](https://github.com/biopython/biopython/files/5015057/Cd6_gene_exon2_6.txt)

### Steps to reproduce

(*Please fill this in *)

**Comment by peterjc** [comment] 2020-08-03 09:44
You loaded a record with ``Cd6_gene = SeqIO.read('Cd6 gene.gb', 'genbank')``, the file starts:

```
LOCUS       Exported               40724 bp ds-DNA     linear   UNA 03-AUG-2020
DEFINITION  natural linear DNA
ACCESSION   .
VERSION     .
KEYWORDS    Cd6
SOURCE      natural DNA sequence
  ORGANISM  unspecified
REFERENCE   1  (bases 1 to 40724)
  AUTHORS   Chang Liu
  TITLE     Direct Submission
  JOURNAL   Exported Monday, August 3, 2020 from SnapGene 3.1.4
            http://www.snapgene.com
FEATURES             Location/Qualifiers
     source          1..40724
                     /organism="Mus musculus"
                     /chromosome="19"
                     /strain="C57BL/6J"
                     /mol_type="genomic DNA"
                     /db_xref="taxon:10090"
     gene            1..40724
                     /gene="Cd6"
                     /note="Cd6"
                     /note="CD6 antigen; Derived by automated computational 
                     analysis using gene prediction method: BestRefSeq,Gnomon."
                     /db_xref="GeneID:12511"
                     /db_xref="MGI:MGI:103566"
     mRNA            join(1..255,29651..29719,30522..30869,31436..31747,
                     33675..33737,35359..35499,35826..35921,37119..37235,
                     38610..38681,38893..39147,39393..39494,39820..40722)
                     /gene="Cd6"
                     /product="CD6 antigen, transcript variant X1"
                     /note="Cd6 mRNA"
                     /note="Derived by automated computational analysis using 
                     gene prediction method: Gnomon. Supporting evidence 
                     includes similarity to: 54 ESTs, 106 long SRA reads, 1 
                     Protein, and 100% coverage of the annotated genomic feature
                     by RNAseq alignments, including 5 samples with support for 
                     all annotated introns"
                     /db_xref="GeneID:12511"
                     /db_xref="MGI:MGI:103566"
```

i.e. This is 40724bp long, and has a gene spanning all of it. There are several different mRNA feature described as joins covering chunks of the sequence.

When you do this:

```
Cd6_gene_exon2_6 = Cd6_gene[29683:33721]
```

It makes a new ``SeqRecord`` with the sub-sequence for the region, and any *complete* features within it. In this case, there are none.

This line is wrong:

```
Cd6_gene_exon2_6.features = Cd6_gene.features.copy()
```

All the features on the original record are using coordinates for the 40724bp parent, they don't make sense on your new smaller sequence.

What are you expecting as output? Would you want anything from those first three features quoted above?

I am guessing you want the features cut to match the region requested, but Biopython does not do that for you. A more straightforward choice might be to pull out entire exons?

e.g. for the mRNA do you want something based on ``join(29651..29719,30522..30869,31436..31747,33675..>33721)`` describing three complete exons and one partial exon?

**Comment by linuxonly801** [comment] 2020-08-03 12:40
Dear Peter, Thanks for your reply. 
I expect the features to cut to match the region I selected. As shown below.
[Cd6_gene_exon2_6_expected_file.txt](https://github.com/biopython/biopython/files/5015970/Cd6_gene_exon2_6_expected_file.txt)

I am trying to clone this fragment to a backbone. How can I achieve this? Thx

**Comment by peterjc** [comment] 2020-08-03 14:55
That helps - looking at the first example mRNA, you want:

```
     mRNA            join(1..37,840..1187,1754..2065,3993..4039)
```

Applying the 29683 offset that would be like this on the parent sequence:

```
     mRNA            join(29683..29719,30522..30869,31436..31747,33675..33721)
```

I was suggesting this as a possible interpretation (having fixed the left value from my original example):

```
     mRNA            join(<29683..29719,30522..30869,31436..31747,33675..>33721)
```

They differ in my use of ``<`` (before) and ``>`` (after) attempting to indicate this was truncated and the start/ending is actually later.

Currently the Biopython feature location objects do not facilitate this cropping approach, but it could be done. You could do it in your own script, but it would mean a fair amount of custom code.

**Comment by linuxonly801** [comment] 2020-08-04 01:15
Dear Peter, Thanks for the reply.
I am a beginner to python and biopython, so, it is really difficult for me to do this in my own script.
Hope you guys can add this function to biopython soon. Looking forward to it ^_^.

**Comment by peterjc** [comment] 2021-06-11 23:03
Closing as a duplicate of #1755 (certainly very close if not fully overlapping)

**Closed by peterjc** 2021-06-11 23:03 UTC
Labels: Enhancement
