### ISSUE TITLE
Missing Phylip/interlaced2.phy_phyml_tree.txt in test_phyml_tool.py

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#623] opened 2015-09-23 13:56 UTC
RE: Debian issue http://bugs.debian.org/799820

```
Bio.PDB.Selection docstring test ... ok
======================================================================
ERROR: test_phyml (test_phyml_tool.AppTests)
Run PhyML using the wrapper.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/python-biopython-1.65+dfsg/.pybuild/pythonX.Y_2.7/build/Tests/test_phyml_tool.py", line 50, in test_phyml
    tree = Phylo.read(EX_PHYLIP + '_phyml_tree.txt', 'newick')
  File "/python-biopython-1.65+dfsg/.pybuild/pythonX.Y_2.7/build/Bio/Phylo/_io.py", line 65, in read
    tree = next(tree_gen)
  File "/python-biopython-1.65+dfsg/.pybuild/pythonX.Y_2.7/build/Bio/Phylo/_io.py", line 52, in parse
    with File.as_handle(file, 'r') as fp:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/python-biopython-1.65+dfsg/.pybuild/pythonX.Y_2.7/build/Bio/File.py", line 90, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IOError: [Errno 2] No such file or directory: 'Phylip/interlaced2.phy_phyml_tree.txt'

----------------------------------------------------------------------
Ran 219 tests in 81.776 seconds

FAILED (failures = 1)
```

Andreas Tille suggests the following change:
https://anonscm.debian.org/viewvc/debian-med/trunk/packages/python-biopython/trunk/debian/patches/fix_test_phyml_tool.patch?view=markup

```
--- python-biopython-1.65+dfsg.orig/Tests/test_phyml_tool.py
+++ python-biopython-1.65+dfsg/Tests/test_phyml_tool.py
@@ -47,7 +47,7 @@ class AppTests(unittest.TestCase):
             self.assertTrue(len(out) > 0)
             self.assertEqual(len(err), 0)
             # Check the output tree
-            tree = Phylo.read(EX_PHYLIP + '_phyml_tree.txt', 'newick')
+            tree = Phylo.read(EX_PHYLIP + '_phyml_tree', 'newick')
             self.assertEqual(tree.count_terminals(), 4)
         finally:
             # Clean up generated files
```

This may be dependent on the version of phyml?

**Comment by tillea** [comment] 2015-09-23 14:42
The phylip version used here is 3.696.
The authors told me that the only relevant change compared to the previous version was the free license.

**Comment by peterjc** [comment] 2015-09-23 14:56
Here we ``test_phyml_tool.py`` is calling the command line tool phyml (not phylip), presumably with a phylip-format input file.

The test is passing here where I have:

```
$ phyml --version | head

NAME
	- PhyML v3.0_360-500M - 

	''A simple, fast, and accurate algorithm to estimate
	large phylogenies by maximum likelihood''

	Stephane Guindon and Olivier Gascuel,
	Systematic Biology 52(5):696-704, 2003.

```

I presume your phyml is more recent?

**Comment by tillea** [comment] 2015-09-23 15:12
That's correct - sorry for mixing up phylip and phyml:

$ phyml --version | head

. command-line: phyml --version 
. This is PhyML version 20150827.


I did package this version of phyml at the advise of phyml author who consideres this version as stable.

**Comment by peterjc** [comment] 2015-09-23 15:28
That looks like a date-based version number rather than the numerical style on my (older) copy of PhyML.

@etal will you be able to look at this?

**Comment by etal** [comment] 2015-09-23 15:40
I'm a bit crunched but I'll try to check it out this week. The proposed
patch looks right to me, if the new output file name is right for the
updated phyml.

**Comment by peterjc** [comment] 2015-09-23 16:02
The test would need a bit of work to still cope with older phyml as well though.

**Comment by etal** [comment] 2017-07-03 19:43
I think this is a duplicate of #919 -- now fixed.

**Closed by etal** 2017-07-03 19:43 UTC
