### ISSUE TITLE
exonerate parser cannot parse interrupted codons

### ISSUE THREAD

**Issue by zbwrnz** [biopython/biopython#591] opened 2015-08-06 17:10 UTC
The exonerate parser in SearchIO fails when splice junctions interrupt codons.

Here is the failed command:

```python
>>> g = SearchIO.parse('test.txt', 'exonerate-text')
>>> next(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/Bio/SearchIO/__init__.py", line 316, in parse
    for qresult in generator:
  File "/usr/lib/python3.4/site-packages/Bio/SearchIO/ExonerateIO/_base.py", line 236, in __iter__
    for qresult in self._parse_qresult():
  File "/usr/lib/python3.4/site-packages/Bio/SearchIO/ExonerateIO/_base.py", line 364, in _parse_qresult
    hsp = _create_hsp(prev_hid, prev_qid, prev['hsp'])
  File "/usr/lib/python3.4/site-packages/Bio/SearchIO/ExonerateIO/_base.py", line 188, in _create_hsp
    frags = _adjust_aa_seq(frags)
  File "/usr/lib/python3.4/site-packages/Bio/SearchIO/ExonerateIO/_base.py", line 43, in _adjust_aa_seq
    assert len(frag) % 3 == 0
AssertionError
```

Here is the exonerate file

```
C4 Alignment:
------------
         Query: AT5G43430.1
        Target: scaffold_4
         Model: protein2genome:local
     Raw score: 56
   Query range: 94 -> 137 
  Target range: 12984925 -> 13063653

       95 : LeuThrIleAlaLysIleLeuLysSerLeuAlaAspValGluAsnProGlyLeu :      112 
            ||||||     !|||||||||!:!||||||::!  ! !!  !||||||..!|||
            LeuThrSerHisLysIleLeuArgSerLeuSerPhePheIleAsnProSerLeu
 12984926 : TTGACATCGCATAAAATCTTGAGATCATTGAGTTTCTTCATAAATCCTTCCCTC : 12984977

      113 : IlePheLeuGlyLysGlnAlaIleAspAspAspCysAsn{Gl}  >>>> Targ :      126 
            :!!!::|||..! ! !    !:!!  !   ...!  .!.{..}    
            LeuTrpLeuAsnAspLeuPheLeuIleLeuSerLeuGlu{Me}++    
 12984978 : CTCTGGTTGAATGATCTTTTCCTCATTCTATCATTGGAA{AT}gt......... : 12985023

      127 : et Intron 1 >>>>  {n}ThrGlyGlnMetValAlaAlaLeuLeuGlyTrp :      137 
            78599 bp          {!}  !|||! !     !|||||||||:!!||||||
                            ++{t}LeuGlyLeuCysAsnAlaAlaLeuIleGlyTrp
 12985024 : ................ag{G}CTCGGACTGTGTAACGCGGCTTTGATAGGTTGG : 13063651

vulgar: AT5G43430.1 94 137 . scaffold_4 12984925 13063653 + 56 M 31 93 S 0 2 5 0 2 I 0 78595 3 0 2 S 1 1 M 11 33
```

Records without interrupted codons in their splice sites, run smoothly, as in the record below:

```
C4 Alignment:
------------
         Query: AT5G43430.1
        Target: scaffold_8 [revcomp]
         Model: protein2genome:local
     Raw score: 52
   Query range: 138 -> 178
  Target range: 18089648 -> 17906475

      139 : GlnAlaThrPheAlaSerLysValValLeuAspLysAspLysAsnVal  >>>> :      155
            |||  !! !|||::!!.!::::!!||||||||||||!!:||||||! !      
            GlnIleIlePheSerLysArgIleValLeuAspLysGluLysAsnGlu-+    
 18089648 : CAAATCATATTTAGTAAGCGTATTGTCCTGGACAAAGAAAAAAATGAGct.... : 18089598

      156 :  Target Intron 1 >>>>  AlaThrValAspArgGluValAspGlyGlyL :      165
                183053 bp            !||||||! !..!..!  !! !|||||| 
                                 ++MetThrValValGluSerTyrAlaGlyGlyL
 18089597 : .....................agATGACAGTGGTCGAGTCGTATGCTGGGGGCA : 17906517

      166 : euGluThrLeuAsnValAspLeuProAlaValIleThrThr :      178
             !:!!|||  !!.!! !.!.|||||||||..!||||||:!!
            ysLysThrAspThrGluGlnLeuProAlaThrIleThrSer
 17906516 : AAAAAACAGATACTGAACAATTGCCAGCAACTATCACTTCG : 17906476

vulgar: AT5G43430.1 138 178 . scaffold_8 18089648 17906475 - 52 M 16 48 5 0 2 I 0 183049 3 0 2 M 24 72
```

If the problem is with translating an incomplete codon, I recommend you pad the sequence with 1 or 2 N's. The translator should interpret this as an unknown residue and represent it as 'X'. This common practice in bioinformatics. For example, the alignment editor Seaview translates incomplete codons surrounding gaps as 'X'.

It is common for splice junctions to interrupt codons. Often this phenomena is of biological interest.

**Comment by peterjc** [comment] 2015-08-06 19:49
Duplicate of #367 which needs a better title to make this more obvious. Could you read and then comment on that issue please? Thanks!

**Closed by peterjc** 2015-08-06 19:49 UTC
