### ISSUE TITLE
Reverse-translation function

### ISSUE THREAD

**Issue by Alp78** [biopython/biopython#2258] opened 2019-09-10 13:52 UTC
Is there a function to reverse-translate a protein sequence into RNA, and reverse-transcribe RNA into DNA?

**Comment by peterjc** [comment] 2019-09-10 14:07
Yes for reverse-transcribe:

```python
from Bio.Seq import back_transcribe
help(back_transcribe)
```

https://github.com/biopython/biopython/blob/biopython-174/Bio/Seq.py#L1015

Also there is a ``back_transcribe`` methods on the sequence objects.

See also http://biopython.org/DIST/docs/tutorial/Tutorial.html

For reverse-translate, the problem is ambiguous. See e.g. https://mailman.open-bio.org/pipermail/biopython/2014-April/015245.html

You might want to thread a know nucleotide sequence onto an aligned protein sequence, in which case see e.g. https://github.com/peterjc/pico_galaxy/tree/master/tools/align_back_trans

**Comment by Alp78** [comment] 2019-09-10 14:11
awesome thanks!

**Comment by peterjc** [comment] 2019-09-10 14:12
Did that cover your use case, and if so can we close this issue?

**Comment by Alp78** [comment] 2019-09-10 14:14
well, so there isn't a way to back-translate from protein to RNA, right?

**Comment by Alp78** [comment] 2019-09-10 14:19
smth like this : https://www.bioinformatics.org/sms2/rev_trans.html

**Comment by peterjc** [comment] 2019-09-10 14:30
Have you read https://mailman.open-bio.org/pipermail/biopython/2014-April/015245.html ?

What is your use case? Do you want just unambiguous A, C, G, T (or U) in the output? If so, which codon should be preferred when there is a choice? Or, if ambiguous nucleotides are OK, how should we pick when then is more than one representation covering different sets of codons?

My point is no one implementation of back-translate is going to please everyone, and in practise most people's needs seem to be quite different.

**Comment by Alp78** [comment] 2019-09-10 14:37
my use case is to get the DNA sequence of this protein: https://www.uniprot.org/uniprot/Q9UN81.fasta
for sure the DNA sequence is available somewhere, but it would be a time saver to have an easy tool to back-translate a protein out of the box. but indeed i get the point of the choice. There could be a function with arguments that cover all use-cases tho, like the choice of alphabet with translate functions..

**Comment by peterjc** [comment] 2019-09-10 14:46
A simple (fast) genetic code based translation table approach simply cannot give you "the" DNA sequence of https://www.uniprot.org/uniprot/Q9UN81.fasta

UniProt proteins can come from more than one nucleotide sequence (even different species if they happen to have the same protein sequence), so there is no single answer - and getting an answer, or the full list, would mean querying UniProt.

In this case, it looks like M80343 which has been replaced by AH005269, and AF148856 apply:

https://www.ebi.ac.uk/ena/data/view/AF148856
https://www.ebi.ac.uk/ena/data/view/AH005269

Presumably you just want the CDS here though...

**Comment by Alp78** [comment] 2019-09-10 15:16
cool :) that makes my day. the sequence of ORFs are no more available on Gene so I didn't know where to look. I understand your point regarding the barrier of back-translation. I'm still quite new to bioinformatics, and appreciate your detailed answers. Helps a lot. Thank you! Case can be closed. Cheers

**Comment by peterjc** [comment] 2019-09-10 16:33
Great.

If it helps, I was reading https://www.uniprot.org/uniprot/Q9UN81 and looked at the *Sequence* section. There probably is a way to do this computationally, but I'm not a UniProt expert.

**Closed by peterjc** 2019-09-10 16:33 UTC

**Comment by Alp78** [comment] 2019-09-11 21:32
for the record, the full GenBank data for LINE1 has moved here: 
http://l1base.charite.de/exportall.php?SESS=HSL13&START=0&NUM=20&SORT=0
