### ISSUE TITLE
RuntimeError: Search Backend failed with Entrez.esearch(db="taxonomy", term=organism)

### ISSUE THREAD

**Issue by Tim-Kirkwood** [biopython/biopython#3890] opened 2022-03-27 11:51 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
CPython
Windows-10-10.0.19041-SP0
1.76
```

### Expected behaviour

I have a web scraper that finds the GCA/GCF accessions for a given string (organism name from a gbk file).  `Record1 ` is the beginning of this scraper and is generated with `Entrez.esearch(db="taxonomy", term=organism)`

### Actual behaviour
I have had two `RuntimeError`s associated with `Search Backend`, caused by two different events - `Database is not supported: taxonomy` and `Unable to open connection to #PMQuerySrv?dbaf=taxonomy`.

I have put the code directly associated with the error.  Organism was "Aspergillus parasiticus":
```
handle = Entrez.esearch(db="taxonomy", term=organism)
record1 = Entrez.read(handle)
handle.close()

Traceback (most recent call last):

  File "C:\Users\u03132tk\.spyder-py3\ModuleMapper QC\file.py", line 66, in <module>
    record1 = Entrez.read(handle)

  File "C:\ANACONDA3\lib\site-packages\Bio\Entrez\__init__.py", line 487, in read
    record = handler.read(handle)

  File "C:\ANACONDA3\lib\site-packages\Bio\Entrez\Parser.py", line 345, in read
    self.parser.ParseFile(handle)

  File "c:\ci\python_1556135146416\work\modules\pyexpat.c", line 471, in EndElement

  File "C:\ANACONDA3\lib\site-packages\Bio\Entrez\Parser.py", line 696, in endErrorElementHandler
    raise RuntimeError(value)

RuntimeError: Search Backend failed: Database is not supported: taxonomy
```

Organism was Streptomyces venezuelae ATCC 10712 :
```
handle = Entrez.esearch(db="taxonomy", term=organism)
record1 = Entrez.read(handle)
handle.close()

Traceback (most recent call last):

  File "C:\Users\u03132tk\.spyder-py3\file.py", line 66, in <module>
    record1 = Entrez.read(handle)

  File "C:\ANACONDA3\lib\site-packages\Bio\Entrez\__init__.py", line 487, in read
    record = handler.read(handle)

  File "C:\ANACONDA3\lib\site-packages\Bio\Entrez\Parser.py", line 345, in read
    self.parser.ParseFile(handle)

  File "c:\ci\python_1556135146416\work\modules\pyexpat.c", line 471, in EndElement

  File "C:\ANACONDA3\lib\site-packages\Bio\Entrez\Parser.py", line 696, in endErrorElementHandler
    raise RuntimeError(value)

RuntimeError: Search Backend failed: Unable to open connection to #PMQuerySrv?dbaf=taxonomy
```

### Steps to reproduce

I cannot reproduce the errors - they occur in the loop, sometimes (but not every time I run the code), and also work when I try manually.  I suspect it is a niche, transient issue to do with my connection, but thought I would post this to make sure.  

If you want to pursue this further I can post my full code, but not sure it's worth your time if its a transient issue on my end!

**Comment by mdehoon** [comment] 2022-03-28 06:16
You could try
```python
>>> handle = Entrez.esearch(db="taxonomy", term=organism)
>>> data = handle.read()
```
to confirm that the problem is in `Entrez.esearch`, and not in `Entrez.read`.

**Comment by Tim-Kirkwood** [comment] 2022-03-28 06:22
Good point!  Unfortunately I can't reproduce the error (it's working fine now).  I'm guessing its a problem with my connection as that's the only thing that isn't constant - presumably this is then reflected in the error handling of `.read`?

**Comment by mdehoon** [comment] 2022-03-28 06:29
Yes; `.read` just reports the error message it received from NCBI.
Closing this issue, as it looks like a connection problem.

**Closed by mdehoon** 2022-03-28 06:29 UTC
