### ISSUE TITLE
pairwise2 localms sometimes returns different score for a sequence and its reverse

### ISSUE THREAD

**Issue by dhauge** [biopython/biopython#766] opened 2016-02-06 00:58 UTC
Unless I'm misunderstanding something, local alignment of sequences should produce the same score and reversed alignment strings if the input sequences are reversed. However, sometimes it doesn't:

    >>> pw.align.localms("abcdefgh", "abcdefgz", 1, -0.5, -1, -0.25)
    [('abcdefgh', 'abcdefgz', 7.0, 0, 7)]
    >>> pw.align.localms("hgfedcba", "zgfedcba", 1, -0.5, -1, -0.25)
    [('hgfedcba', 'zgfedcba', 6.5, 1, 8)]

I haven't investigated yet the limits of the difference, but it seems to happen often when there is one mismatch at the end. Compare with

    >>> pw.align.localms("abcdefgh", "abcdefzz", 1, -0.5, -1, -0.25)
    [('abcdefgh', 'abcdefzz', 6.0, 0, 6)]
    >>> pw.align.localms("hgfedcba", "zzfedcba", 1, -0.5, -1, -0.25)
    [('hgfedcba', 'zzfedcba', 6.0, 2, 8)]

* biopython version: 1.66
* Pyton version: 2.7.11
* OS: MacOS 10.9.5 (x64)

**Comment by MarkusPiotrowski** [comment] 2016-02-25 12:32
@dhauge: I'm acutally working on pairwise2 (for other reasons), and I can tell you that the new code works fine with your example.

**Comment by dhauge** [comment] 2016-02-25 19:34
Thanks, that's good to hear. Out of curiosity, are you working on an overhaul of the package, or will it be more along the lines of many small improvements? There are performance issues I've run into that I've been considering trying to fix, mainly involving trying to reduce the amount of callbacks from C to Python for common cases, and getting the optimized C version of the code to be used for byte sequences in Python 3. However, some of those would benefit from, if not require, a large restructuring of the C portion of the code. I'm wondering if your work might be addressing this, or if it would be worth me adding issues describing the specific cases I've encountered?

**Comment by MarkusPiotrowski** [comment] 2016-02-25 21:58
I started working on pairwise2 due to a paper which critizes that many programs (including pairwise2) have errors in their implementation of the Gotoh algorithm [http://www.exelixis-lab.org/web/software/alignment/](url). During this work I stumbled across other complains about performance of pairwise2, e.g. #603, #297 . The main reason for the bad performance of both the pure Python implementation and especially the C code (which can be slower than the Python implementation!) is the way the trace_matrix is designed: it stores all gap open positions it encounters. In the worst case, in an aligment of two 1000 bp sequences, a single cell of the trace matrix can contain up to 1000 positions! And in the C code these are back-transcribed into Python objects, while still in memory. 
What I have done: 1. Rewrote _make_score_matrix_fast to (a) adress the "insertion after deletion" problem mentioned in the paper and (b) implement a different trace matrix concept (each cell of the trace matrix just contains one int). This required to 2. rewrite the backtrace method. 3. I changed the C code accordingly. 4. I optimized the code for score_only (where we don't need a trace matrix).
It is still work in progress (_make_score_matrix_generic must be adapted to work with the new backtrace), but I think most of the stuff is done and I see nice enhancements in speed and maximum sequence length. If you want to test, the current version is saved as pairwise2a.py in my GitHub account (branch: pairwise2), together with cpairwise2a.pyd (a 32bit Windows version!). If you want/need to compile the C code, this is cpairwise2module_new.c.

**Comment by peterjc** [comment] 2016-06-15 21:34
The new version of ``Bio.pairwise2`` was merged on #782 and will be in Biopython 1.68 onwards.

@MarkusPiotrowski do the examples given here make sense as extra test cases for ``test_pairwise2.py``?

**Comment by MarkusPiotrowski** [comment] 2016-06-16 08:09
The problem is in principle the same as described in #279, in both cases the proposed match (which wasn't recognized) is at position 2 in the alignment, with a mismatch at position 1. This was a specific error for local alignments of the former implementation of the algorithm. So, no, the added test from #279 will cover this.

**Comment by peterjc** [comment] 2016-06-16 09:14
Thank you for checking this @MarkusPiotrowski - and thank you @dhauge for report it.

I'm marking this issue as closed - you can try the current code or wait for Biopython 1.68

**Closed by peterjc** 2016-06-16 09:14 UTC

**Comment by dhauge** [comment] 2016-06-30 18:24
Thanks for fixing this (and sorry for not responding earlier). I'll try it when Biopython 1.68 comes out.
