### ISSUE TITLE
`Blast.NCBIWWW.qblast` should return the `rid` of the submitted query to the caller 

### ISSUE THREAD

**Issue by kamurani** [biopython/biopython#4721] opened 2024-05-06 06:01 UTC
When using `qblast` to automate blast searches on NCBI, the RID of the submitted request is not returned to the user.  The RID is also not accessible anywhere within the `xml`-formatted output.  

The RID may be useful for later retrieval from NCBI, using the URL `https://blast.ncbi.nlm.nih.gov/Blast.cgi?RID={{rid}}&CMD=Get`, especially for submitted jobs that take a while to perform, and where the user may wish to revisit the results in the more accessible webpage view.  

Within `qblast`, the RID is already accessed using 

```python
rid, rtoe = _parse_qblast_ref_page(handle)
```

At the moment, I am using a modified version of the `qblast` function that returns a dictionary of values, as a workaround: 

https://github.com/kamurani/biopython/blob/c58c401b7a94bf06e13fadc4f41d5076dd1c78f4/Bio/Blast/NCBIWWW.py#L302-L307

https://github.com/kamurani/biopython/commit/c58c401b7a94bf06e13fadc4f41d5076dd1c78f4

Is this something that I could modify further to be a useful feature? Would appreciate any advice, and if so happy to make a PR.

**Comment by kamurani** [comment] 2024-05-06 06:03
https://github.com/kamurani/biopython/blob/c58c401b7a94bf06e13fadc4f41d5076dd1c78f4/Bio/Blast/NCBIWWW.py#L302-L307

**Comment by peterjc** [comment] 2024-05-06 09:19
Duplicate of #4263. Your suggested change is an API break (so not acceptable), see also the proposal on #3342 was backward compatible which could be worth reconsidering.

**Comment by mdehoon** [comment] 2024-05-06 09:58
@kamurani Have a look at the new qblast function in `Bio/Blast/__init__.py`. It contains a new qblast function that solves some of the issues of the old qblast function in `Bio/Blast/NCBIWWW.py`. As it has not yet been released, its API can still be changed.

**Closed** 2024-06-25 01:36 UTC
