### ISSUE TITLE
Pairwise alignment causing kernel restart

### ISSUE THREAD

**Issue by colombianBirdPerson** [biopython/biopython#2309] opened 2019-10-21 20:10 UTC
### Setup

I am reporting a problem with Biopython version 3.7.3, Python version 7.3.0, and operating
system Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid 1.74.

### Expected behaviour

Successful pairwise alignment

### Actual behavior

kernel dies and restarts automatically, without any error message

### Steps to reproduce
```
seq1='TTGCAGATACGTGGCTTTCCTGAAGCTGTTCCTGGAGACGGCGGAGAAGCACTTCATGGTGGGCCACCGTGTCCACTACTATGTCTTCACCGACCAGCCGGCCGCGGTGCCCCGCGTGACGCTGGGGACCGGTCGGCAGCTGTCAGTGCTGGAGGTGCGCGCCTACAAGCGCTRGCAGGACGTGTCCATGCGCCGCATGGAGATGATCAGTGACTTCTGCGAGCGGCGCTTCCTCAGCGAGGTGGATTACCTGGTGTGCGTGGACGTGGACATGGAGSTCCGCGACCACGTGGGCGTGGAGATCCTGACTCCRCTGTTCGGCACCCTGCACCCCGGCTTCTACGGAAGCAGCCGGGAGGCCTTCACCTACGAGCGCCGGCCCCAGTCCCAGGCCTACATCCCYAAGGACGAGGGCGATTTCTACTACCTGGGGGGGTTCTTCGGGGGGTCGGTGCAAGAGRTGCAGCGGCTCACCAGGGCCTGCCACCAGGCCATGATGGTCGACCAGGCCAACGGCATCGAGGCCGTGTGGCACGACGAGAGCCACCTGAACAAGTACCTGCTGCGCCACAAACCCACCAAGGTGCTCTCCCCCGAGTACTTGTGGGACCAGCAGCTGCTGGGCTGGCCCGCCGTCCTGAGGAAGCTGAGGTTCACTGCGGTGCCCAAGAACCACCAGGCGGTCCGGAACCCGTGAGCGGCTG'
seq2='ATACGTGGCTYTCCTGAAGCTGTTCCTGGAGAYGGYGGAGAAGCACTTCAYSGTGGGCCRCCGTGTCCACTACTATGTCYTCACCGACCAGCYGGCCGCGGTGCCCCGCGTGAYGCTGGGGNCYKGTBKGCAGCTGTCAGTGCTGGAGRTGSRCRCCTACAAGCVCYRKCAGRRCRTGTYCRTKYGCCGYRTGGAGATGAYCAGTGACTTCTGSGAGYGGYGCTTCCTCAGCVAGGTGGATTACSTGGTGTGCGTGGACRTGGACRBGGAGWTCYGCGACCAYGTGGGCRTGGAKATCCTGACTCCRCTGTTYSRCACCCYGCACBCCRGCTTCTACGGAAGCAGCYRGGAGGCYTTCACCTACGAGYSCYGGCCCCAGTCCCAGGYCTACAYMCCYAAGGRCRAGGGCRATTTCTACTACMTGGRNRVGTTCWTCGGGGGGTCGRTGCAAGAGRTGCAGCGGYTCACCAGGGCCTGCCACCAGGYCAKGATGGTCRASCAGGCCAACGGCATCRAGKCCGTGTGGCACGACGAGAGCCACCTGAACAAGTACCTGCTGCGCCACAAACCCACCAAGGTGCTCTCCCCCGAGTACTTGTGGGACCAGCAGCTGCTGGGCTGGCCCGCCGTCCTGAGGAAGCTGAGGTTCACTGCGGTGCCCRWGAACCACCAGGCGGTCBRGAACCCGTGA'
matrix={
    ('N','N'):0.5,
    ('N','A'):0.5,
    ('N','T'):0.5,
    ('N','C'):0.5,
    ('N','G'):0.5,
    ('N','R'):0.5,
    ('N','Y'):0.5,
    ('N','S'):0.5,
    ('N','W'):0.5,
    ('N','K'):0.5,
    ('N','M'):0.5,
    ('A','N'):0.5,
    ('T','N'):0.5,
    ('C','N'):0.5,
    ('G','N'):0.5,
    ('R','N'):0.5,
    ('Y','N'):0.5,
    ('S','N'):0.5,
    ('W','N'):0.5,
    ('K','N'):0.5,
    ('M','N'):0.5,
    ('A','A'):2,
    ('A','R'):1,
    ('A','W'):1,
    ('A','M'):1,
    ('A','C'): -1,
    ('A','T'): -1,
    ('A','G'): -1,
    ('A','Y'): -1,
    ('A','S'): -1,
    ('A','K'): -1,
    ('T','T'):2,
    ('T','Y'):1,
    ('T','W'):1,
    ('T','K'):1,
    ('T','C'): -1,
    ('T','A'): -1,
    ('T','G'): -1,
    ('T','R'): -1,
    ('T','S'): -1,
    ('T','M'): -1,
    ('C','C'):2,
    ('C','Y'):1,
    ('C','S'):1,
    ('C','M'):1,
    ('C','A'): -1,
    ('C','T'): -1,
    ('C','G'): -1,
    ('C','R'): -1,
    ('C','W'): -1,
    ('C','K'): -1,
    ('G','G'):2,
    ('G','R'):1,
    ('G','S'):1,
    ('G','K'):1,
    ('G','C'): -1,
    ('G','T'): -1,
    ('G','A'): -1,
    ('G','Y'): -1,
    ('G','W'): -1,
    ('G','M'): -1,
    ('A','A'):2,
    ('R','A'):1,
    ('W','A'):1,
    ('M','A'):1,
    ('C','A'): -1,
    ('T','A'): -1,
    ('G','A'): -1,
    ('Y','A'): -1,
    ('S','A'): -1,
    ('K','A'): -1,
    ('T','T'):2,
    ('Y','T'):1,
    ('W','T'):1,
    ('K','T'):1,
    ('C','T'): -1,
    ('A','T'): -1,
    ('G','T'): -1,
    ('R','T'): -1,
    ('S','T'): -1,
    ('M','T'): -1,
    ('C','C'):2,
    ('Y','C'):1,
    ('S','C'):1,
    ('M','C'):1,
    ('A','C'): -1,
    ('T','C'): -1,
    ('G','C'): -1,
    ('R','C'): -1,
    ('W','C'): -1,
    ('K','C'): -1,
    ('G','G'):2,
    ('R','G'):1,
    ('S','G'):1,
    ('K','G'):1,
    ('C','G'): -1,
    ('T','G'): -1,
    ('A','G'): -1,
    ('Y','G'): -1,
    ('W','G'): -1,
    ('M','G'): -1,
    ('R','R'):2,
    ('R','Y'): -1,
    ('R','S'):1,
    ('R','W'):1,
    ('R','K'):1,
    ('R','M'):1,
    ('Y','R'): -1,
    ('Y','Y'):2,
    ('Y','S'):1,
    ('Y','W'):1,
    ('Y','K'):1,
    ('Y','M'):1,
    ('S','R'):1,
    ('S','Y'):1,
    ('S','S'):2,
    ('S','W'):-1,
    ('S','K'):1,
    ('S','M'):1,
    ('W','R'):1,
    ('W','Y'):1,
    ('W','S'):-1,
    ('W','W'):2,
    ('W','K'):1,
    ('W','M'):1,
    ('K','R'):1,
    ('K','Y'):1,
    ('K','S'):1,
    ('K','W'):1,
    ('K','K'):2,
    ('K','M'): -1,
    ('M','R'):1,
    ('M','Y'):1,
    ('M','S'):1,
    ('M','W'):1,
    ('M','K'): -1,
    ('M','M'):2,
}

pa1=pairwise2.align.localds(consenso,seqPrim,matrix,-2,-1,penalize_end_gaps=False)
```

**Comment by mdehoon** [comment] 2019-10-22 00:54
I get the following traceback with this code:
```
>>> pa1=pairwise2.align.localds(seq1,seq2,matrix,-2,-1,penalize_end_gaps=False) 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/pairwise2.py", line 1074, in __call__
    return self.score_dict[(charA, charB)]
KeyError: ('B', 'G')

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: PyEval_EvalFrameEx returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/pairwise2.py", line 431, in __call__
    return _align(**keywds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/pairwise2.py", line 485, in _align
    align_globally, score_only)
SystemError: <built-in function _make_score_matrix_fast> returned a result with an error set
>>> 
```

**Comment by mdehoon** [comment] 2019-10-22 00:55
Have you tried with the new `PairwiseAligner` in `Bio.Align`?

**Comment by MarkusPiotrowski** [comment] 2019-10-22 07:29
@colombianBirdPerson I don't know why your system fails without error message, but I get the same error as @mdehoon:
```python
Traceback (most recent call last):
  File "D:/Desktop/pw2_test.py", line 145, in <module>
    pa1=pairwise2.align.localds(seq1, seq2, matrix, -2, -1, penalize_end_gaps=False)
  File "D:\Programme\Python27\lib\site-packages\Bio\pairwise2.py", line 413, in __call__
    return _align(**keywds)
  File "D:\Programme\Python27\lib\site-packages\Bio\pairwise2.py", line 467, in _align
    align_globally, score_only)
  File "D:\Programme\Python27\lib\site-packages\Bio\pairwise2.py", line 1056, in __call__
    return self.score_dict[(charA, charB)]
KeyError: ('B', 'T')
```

This means that your matrix is not complete, you are missing the '3 bases' letters B (C, G or T =not A) and V (=not T) (and for a general matrix: H (=not G) and D (=not C)) .

**Comment by chris-rands** [comment] 2019-10-23 13:18
I think you can select an appropriate matrix from `Bio.SubsMat.MatrixInfo` without the missing keys, e.g. the following results in no error:

```
>>> from Bio.SubsMat.MatrixInfo import blosum50
>>> pa1=pairwise2.align.localds(seq1,seq2,blosum50,-2,-1,penalize_end_gaps=False)
```

**Comment by MarkusPiotrowski** [comment] 2019-10-23 13:26
BLOSUM is a protein (amino acid) matrix, these here are nucleotide 
sequences.

**Comment by chris-rands** [comment] 2019-10-23 13:54
@MarkusPiotrowski technically they *could* be protein sequences based on the alphabet, but i agree that looking at the actual sequences it's not the case. In fact I think `Bio.SubsMat.MatrixInfo` only provides aa matrixes so my previous comment was unhelpful, thanks for pointing that out

**Comment by MarkusPiotrowski** [comment] 2019-10-25 14:05
@colombianBirdPerson I guess the solution to your principal problem (missing data in your matrix) was explained. 
We cannot reproduce that your 'kernel dies and restarts automatically without any error message', however, your example code was not complete (missing import) and contained errors (different sequence names) so maybe there are other factors in your complete script which results in this behavior. 

May I understand your 'thumbs up' that we can close the issue?

**Comment by MarkusPiotrowski** [comment] 2020-01-13 12:37
No further comment or feedback from OP; so closing this now.

**Closed by MarkusPiotrowski** 2020-01-13 12:37 UTC
