### ISSUE TITLE
GenBank parser get stuck on certain sequences and never returns with seqio object

### ISSUE THREAD

**Issue by sheoran** [biopython/biopython#853] opened 2016-06-14 17:00 UTC
This issues happens with many sequences in my dataset, I have uploaded one as an example. This happens due  something known as Catastrophic Backtracking, which basically will return but after a long long long time. 

The exact line in the sample file where it happens is below

In [2]: _re_complex_compound
Out[2]: 
re.compile(r'^(join|order|bond)\((([a-zA-Z][a-zA-Z0-9_\.]*[a-zA-Z0-9]?\:)?([<>]?\d+\.\.[<>]?\d+|[<>]?\d+|\d+\^\d+|([<>]?\d+|\(\d+\.
\d+\))\.\.([<>]?\d+|\(\d+\.\d+\))|([<>]?\d+|one\-of\(\d+(,\d+)+\))\.\.([<>]?\d+|one\-of\(\d+(,\d+)+\)))|complement\(([a-zA-Z][a-zA-
Z0-9_\.]*[a-zA-Z0-9]?\:)?([<>]?\d+\.\.[<>]?\d+|[<>]?\d+|\d+\^\d+|([<>]?\d+|\(\d+\.\d+\))\.\.([<>]?\d+|\(\d+\.\d+\))|([<>]?\d+|one\-
of\(\d+(,\d+)+\))\.\.([<>]?\d+|one\-of\(\d+(,\d+)+\)))\))(,(([a-zA-Z][a-zA-Z0-9_\.]*[a-zA-Z0-9]?\:)?([<>]?\d+\.\.[<>]?\d+|[<>]?\d+|
\d+\^\d+|([<>]?\d+|\(\d+\.\d+\))\.\.([<>]?\d+|\(\d+\.\d+\))|([<>]?\d+|one\-of\(\d+(,\d+)+\))\.\.([<>]?\d+|one\-of\(\d+(,\d+)+\)))|c
omplement\(([a-zA-Z][a-zA-Z0-9_\.]*[a-zA-Z0-9]?\:)?([<>]?\d+\.\.[<>]?\d+|[<>]?\d+|\d+\^\d+|([<>]?\d+|\(\d+\.\d+\))\.\.([<>]?\d+|\($
d+\.\d+\))|([<>]?\d+|one\-of\(\d+(,\d+)+\))\.\.([<>]?\d+|one\-of\(\d+(,\d+)+\)))\)))*\)$',
re.UNICODE)

In [3]: location_line
Out[3]: 'join(13367..13474,16398..16601,22833..22919,23028..23125,23748..23874,32358..32438,37810..37950,40438..40553,43429..43523$
48472..48617,51728..51879,53050..53163,58817..58898,61448..61496,64324..64463,65917..66032,71528..71633,74540..74700,96695..96818,$
9766..99924,105675..105743,107186..107322,110572..110695,gi|11022364:3805..4009,gi|11022364:6315..6429,gi|11022364:8560..8692,gi|1$
022364:9007..9126,gi|11022364:10101..10163,gi|11022364:11048..11193,gi|11022364:14962..15067,gi|11022364:20594..21033,gi|11022364:$
1127..21234,gi|11022364:23662..23797,gi|11022364:25490..25525)'

It get stucks in below line of Genbank.__init__.py

       if _re_complex_compound.match(location_line):
            i = location_line.find("(")
            # cur_feature.location_operator = location_line[:i]
            # Can't split on the comma because of positions like one-of(1,2,3)
            sub_features = cur_feature.sub_features
            for part in _split_compound_loc(location_line[i + 1:-1]):

[buggy.txt](https://github.com/biopython/biopython/files/314465/buggy.txt)

**Comment by peterjc** [comment] 2016-06-14 20:06
That's an interesting test case, Z75889 as viewable at http://www.ncbi.nlm.nih.gov/nuccore/Z75889

Maybe an iterator approach nibbling off one part of the join at a time might work for splitting up these long complex joins?

In case it is important, which OS and which version of Python and Biopython are you using?

**Comment by sheoran** [comment] 2016-06-14 23:51
Thanks for responding on this issue. 
I am using python 3.4 and ubuntu 14 LTS in a docker container and biopython 1.67

Addition to your suggestion, where location are lazy property and parsed when accessed. This will boost genbank parser speed a lot in cases where complex location are used. 

For now I am overriding this by extending GenbankParser and re-registering it in SeqIO for my code base.

**Comment by peterjc** [comment] 2016-06-21 13:47
We had a GSoC project on lazy loading, https://www.google-melange.com/gsoc/project/details/google/gsoc2014/eparker05/5643440998055936 https://github.com/biopython/biopython/pull/356 - which was far more ambitious. I think we looked at delayed parsing of the features as part of this.

Back to this bug though, I can't reproduce it (tried latest Biopython from github with Python 2.6 and 3.5):

```
$ python3.5 -c "import Bio; print(Bio.__version__)"
1.67+
$ python3.5 -c "from Bio import SeqIO; print(len(SeqIO.read('Z75889.gb', 'gb')))"
113704
```

The long location is there,

```
$ grep "join(13367..13474,16398..16601,22833..22919,23028..23125" Z75889.gb -A 13
     CDS             join(13367..13474,16398..16601,22833..22919,23028..23125,
                     23748..23874,32358..32438,37810..37950,40438..40553,
                     43429..43523,48472..48617,51728..51879,53050..53163,
                     58817..58898,61448..61496,64324..64463,65917..66032,
                     71528..71633,74540..74700,96695..96818,99766..99924,
                     105675..105743,107186..107322,110572..110695,
                     AL138820.11:3805..4009,AL138820.11:6315..6429,
                     AL138820.11:8560..8692,AL138820.11:9007..9126,
                     AL138820.11:10101..10163,AL138820.11:11048..11193,
                     AL138820.11:14962..15067,AL138820.11:20594..21033,
                     AL138820.11:21127..21234,AL138820.11:23662..23797,
                     AL138820.11:25490..25525)
                     /gene="PDS5B"
                     /locus_tag="RP1-267P19.1-006"
```

I downloaded this via http://www.ncbi.nlm.nih.gov/nuccore/Z75889 using the top right send menu (Complete Record, to File, format GenBank).

```
$ python2.6 -c "from Bio.GenBank import _re_complex_compound; print(_re_complex_compound.pattern)"
^(join|order|bond)\((([a-zA-Z][a-zA-Z0-9_\.]*[a-zA-Z0-9]?\:)?([<>]?\d+\.\.[<>]?\d+|[<>]?\d+|\d+\^\d+|([<>]?\d+|\(\d+\.\d+\))\.\.([<>]?\d+|\(\d+\.\d+\))|([<>]?\d+|one\-of\(\d+(,\d+)+\))\.\.([<>]?\d+|one\-of\(\d+(,\d+)+\)))|complement\(([a-zA-Z][a-zA-Z0-9_\.]*[a-zA-Z0-9]?\:)?([<>]?\d+\.\.[<>]?\d+|[<>]?\d+|\d+\^\d+|([<>]?\d+|\(\d+\.\d+\))\.\.([<>]?\d+|\(\d+\.\d+\))|([<>]?\d+|one\-of\(\d+(,\d+)+\))\.\.([<>]?\d+|one\-of\(\d+(,\d+)+\)))\))(,(([a-zA-Z][a-zA-Z0-9_\.]*[a-zA-Z0-9]?\:)?([<>]?\d+\.\.[<>]?\d+|[<>]?\d+|\d+\^\d+|([<>]?\d+|\(\d+\.\d+\))\.\.([<>]?\d+|\(\d+\.\d+\))|([<>]?\d+|one\-of\(\d+(,\d+)+\))\.\.([<>]?\d+|one\-of\(\d+(,\d+)+\)))|complement\(([a-zA-Z][a-zA-Z0-9_\.]*[a-zA-Z0-9]?\:)?([<>]?\d+\.\.[<>]?\d+|[<>]?\d+|\d+\^\d+|([<>]?\d+|\(\d+\.\d+\))\.\.([<>]?\d+|\(\d+\.\d+\))|([<>]?\d+|one\-of\(\d+(,\d+)+\))\.\.([<>]?\d+|one\-of\(\d+(,\d+)+\)))\)))*\)$
```

This has changed slightly over the years - and differs from your bug report, but that could easily have been a copy/paste error. Which version of Biopython do you have?

**Comment by sheoran** [comment] 2016-06-24 17:52
Don't download the record, please the one I have attached. Its created using asn2all tool from asn files. There is difference, my location have lot of 'gi' but you output doesn't have any, may be that is the  cause

**Comment by peterjc** [comment] 2016-06-27 11:33
OK, I can reproduce this on the latest Biopython from git, here using Mac OS X:

```
$ curl -L -O https://github.com/biopython/biopython/files/314465/buggy.txt
...
$ python3.5 -c "from Bio import SeqIO; print(len(SeqIO.read('buggy.txt', 'gb')))"
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(gi|2104578:42752..42918,13348..13474,16398..16601,22833..22919,23028..23125,23748..23874,32358..32438,37810..37950,40438..40553,43429..43523,48472..48617,51728..51879,53050..53163,58817..58898,61448..61496,64324..64463,65917..66032,71528..71633,74540..74700,96695..96818,99766..99924,105675..105743,107186..107322,110572..110695,gi|11022364:3805..4009,gi|11022364:6315..6429,gi|11022364:8560..8692,gi|11022364:9007..9126,gi|11022364:10101..10163,gi|11022364:11048..11193,gi|11022364:14962..15067,gi|11022364:20594..21033,gi|11022364:21127..21234,gi|11022364:23662..23797,gi|11022364:25490..28492)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(gi|2104578:42873..42918,13348..13474,16398..16601,22833..22919,23028..23125,23748..23874,32358..32438,37810..37950,40438..40553,43429..43523,48472..48617,51728..51879,53050..53163,58817..58898,61448..61496,64324..64463,65917..66032,71528..71633,74540..74700,96695..96818,99766..99924,105675..105743,107186..107322,110572..110695,gi|11022364:3805..4009,gi|11022364:6315..6429,gi|11022364:8560..8692,gi|11022364:9007..9126,gi|11022364:10101..10163,gi|11022364:11048..11193,gi|11022364:14962..15067,gi|11022364:20594..21033,gi|11022364:21127..21351,gi|11022364:25490..26381)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'join(gi|2104578:42752..42918,13348..13474,16398..16601,22833..22919,23028..23125,23748..23874,32358..32438,37810..37950,40438..40553,43429..43523,48472..48617,51728..51879,53050..53163,58817..58898,61448..61496,64324..64463,65917..66032,71528..71633,74540..74700,96695..96818,99766..99924,105675..105743,107186..107322,110572..110695,gi|11022364:3805..4009,gi|11022364:6315..6429,gi|11022364:8560..8692,gi|11022364:9007..9126,gi|11022364:10101..10163,gi|11022364:11048..11193,gi|11022364:14962..15067,gi|11022364:20594..21033,gi|11022364:21127..21234,gi|11022364:23662..23797,gi|11022364:25490..28492)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'join(gi|2104578:42873..42918,13348..13474,16398..16601,22833..22919,23028..23125,23748..23874,32358..32438,37810..37950,40438..40553,43429..43523,48472..48617,51728..51879,53050..53163,58817..58898,61448..61496,64324..64463,65917..66032,71528..71633,74540..74700,96695..96818,99766..99924,105675..105743,107186..107322,110572..110695,gi|11022364:3805..4009,gi|11022364:6315..6429,gi|11022364:8560..8692,gi|11022364:9007..9126,gi|11022364:10101..10163,gi|11022364:11048..11193,gi|11022364:14962..15067,gi|11022364:20594..21033,gi|11022364:21127..21351,gi|11022364:25490..26381)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(gi|2104578:42868..42918,13348..13474,16398..16601,22833..22919,23028..23125,23748..23874,32358..32438,37810..37950,40438..40553,43429..43523,48472..48617,51728..51879,53050..55862)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'join(gi|2104578:42868..42918,13348..13474,16398..16601,22833..22919,23028..23125,23748..23874,32358..32438,37810..37950,40438..40553,43429..43523,48472..48617,51728..51879,53050..55862)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(gi|2104578:42780..42918,13348..13474,16398..16601,22833..22943)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'join(gi|2104578:42780..42918,13348..13474,16398..16601,22833..22943)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(gi|2104578:42876..42918,13348..13474,16398..17199)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'join(gi|2104578:42876..42918,13348..13474,16398..17199)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'order(gi|2104578:42894..42918,13348..15211)'
  % (location_line)))
/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py:1123: BiopythonParserWarning: Couldn't parse feature location: 'join(gi|2104578:42894..42918,13348..15211)'
  % (location_line)))
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pjcock/lib/python3.5/site-packages/Bio/SeqIO/__init__.py", line 661, in read
    first = next(iterator)
  File "/Users/pjcock/lib/python3.5/site-packages/Bio/SeqIO/__init__.py", line 597, in parse
    for r in i:
  File "/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 478, in parse_records
    record = self.parse(handle, do_features)
  File "/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 462, in parse
    if self.feed(handle, consumer, do_features):
  File "/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 434, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 383, in _feed_feature_table
    consumer.location(location_string)
  File "/Users/pjcock/lib/python3.5/site-packages/Bio/GenBank/__init__.py", line 1064, in location
    if _re_complex_compound.match(location_line):
KeyboardInterrupt
```

This was stuck at 100% and from sampling via Activity Monitor this does look like it is in C code for the regular expressions.

Note that prior to this is is failing to parse and warning on multiple complex ``order`` and ``join`` locations. Interestingly the pipe ``|`` is not included in our regular expression for a complex location, which is why location fragments like ``gi|2104578:42752..42918`` are not matching.

With this tiny fix it seems fine again - can you try this locally on your Biopython installation please?

```
$ git diff
diff --git a/Bio/GenBank/__init__.py b/Bio/GenBank/__init__.py
index 776d79a..0a2ef66 100644
--- a/Bio/GenBank/__init__.py
+++ b/Bio/GenBank/__init__.py
@@ -96,7 +96,7 @@ _simple_location = r"\d+\.\.\d+"
 _re_simple_location = re.compile(r"^%s$" % _simple_location)
 _re_simple_compound = re.compile(r"^(join|order|bond)\(%s(,%s)*\)$"
                                  % (_simple_location, _simple_location))
-_complex_location = r"([a-zA-Z][a-zA-Z0-9_\.]*[a-zA-Z0-9]?\:)?(%s|%s|%s|%s|%s)" \
+_complex_location = r"([a-zA-Z][a-zA-Z0-9_\.\|]*[a-zA-Z0-9]?\:)?(%s|%s|%s|%s|%s)" \
                     % (_pair_location, _solo_location, _between_location,
                        _within_location, _oneof_location)
 _re_complex_location = re.compile(r"^%s$" % _complex_location)
```

Then:

```
$ python3.5 -c "from Bio import SeqIO; print(len(SeqIO.read('buggy.txt', 'gb')))"
113704
```

Where did the GenBank format file with ``|`` characters in the location references come from? Did the NCBI generate it, or a third party?

**Comment by peterjc** [comment] 2016-07-06 13:58
With 37e7e265d737eaba0b6184468a63e189efea5912 now on the master branch, these files should parse fine. Can you easily check this by either making the two-character edit locally, or re-installing Biopython from GitHub?

I'd still like to know where this file with the ``|`` characters came from...

**Comment by sheoran** [comment] 2016-07-08 07:07
Sorry for delayed response, yes the fix is working for me. Yes these files are generated using data available in asn format from ncbi.

**Comment by peterjc** [comment] 2016-07-08 11:17
Thanks. Are you using one of the NCBI tools to convert ASN into GenBank format?

**Comment by sheoran** [comment] 2016-07-09 18:43
yes

**Comment by peterjc** [comment] 2016-07-13 11:31
OK, I guess this make the use of pipes semi-official then (although it could be a bug in the NCBI ASN converter).

I'm marking this as closed since Biopython should now handle these files.

Thank you for reporting this :)

**Closed by peterjc** 2016-07-13 11:31 UTC
