### ISSUE TITLE
Unexpected item 'fda_recognized_database' in dictionary

### ISSUE THREAD

**Issue by barioux** [biopython/biopython#4851] opened 2024-09-20 18:54 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows: 

3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0]
CPython
Linux-5.15.0-1068-aws-x86_64-with-glibc2.31
1.84

### Expected behaviour

I am trying to pull information from ClinVar using this code:
handle_summary = Entrez.esummary(db="clinvar", id="4179")
record_summary = Entrez.read(handle_summary)
handle_summary.close()

### Actual behaviour

I get the error message: ValueError: Unexpected item 'fda_recognized_database' in dictionary

Is there a way around this issue? 
Thanks,

**Comment by michaelfm1211** [comment] 2024-09-21 18:35
Biopython caches DTDs locally to make parsing Entrez queries faster. It looks like the DTD for ESummary ClinVar responses was outdated and didn't include a definition for the `<fda_recognized_database>`. I opened a PR (#4852) that should fix this by updating the DTD.

**Comment by michaelfm1211** [comment] 2024-09-21 19:09
If you can't wait until the PR is merged, you can manually add the updated DTD to Biopython's DTD cache. To do this, first find the path to the cache directory. On macOS/Linux this should be ` ~/.config/biopython/Bio/Entrez/DTDs` and on Windows it should be  `%APPDATA%\biopython\Bio\Entrez\DTDs`. Once you have that path, you can download https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20240612/esummary_clinvar.dtd and place it into the cache directory.

I've confirmed that this works on macOS, but not on Linux or Windows, however I believe it should work on those platforms too.

**Closed** 2024-09-22 00:05 UTC
