### ISSUE TITLE
Uniprot KB "Q96QU6"

### ISSUE THREAD

**Issue by llrs** [biopython/biopython#513] opened 2015-04-14 14:06 UTC
I can't read the uniprot id Q96QU6 from: http://www.uniprot.org/uniprot/Q96QU6.txt on python 1.62 with 
```python
handle = ExPASy.get_sprot_raw(uniprot_id)
record = SwissProt.read(handle)
```

Error:

```shell
     record = SwissProt.read(handle)
  File "/usr/local/lib/python2.7/dist-packages/Bio/SwissProt/__init__.py", line 123, in read
    record = _read(handle)
  File "/usr/local/lib/python2.7/dist-packages/Bio/SwissProt/__init__.py", line 183, in _read
    _read_rn(reference, value)
  File "/usr/local/lib/python2.7/dist-packages/Bio/SwissProt/__init__.py", line 408, in _read_rn
    assert rn[0] == '[' and rn[-1] == ']', "Missing brackets %s" % rn
AssertionError: Missing brackets [1] {ECO:0000305, ECO:0000312|EMBL:AAK11482.1}
```

It is actually the line 424 of the [actual code](https://github.com/biopython/biopython/blob/master/Bio/SwissProt/__init__.py#L424)
This error is still on the newer version?

**Comment by peterjc** [comment] 2015-04-14 14:17
I think this is a duplicate of #369, which was fixed in Biopython 1.65.

**Closed by peterjc** 2015-04-14 14:17 UTC
