### ISSUE TITLE
ImportError: cannot import name 'BiopythonParserWarning' from 'Bio' (unknown location)

### ISSUE THREAD

**Issue by Nancy1030** [biopython/biopython#2395] opened 2019-12-11 19:08 UTC
### Setup

I am reporting a problem with Biopython module import:

```python
import Bio
from Bio import Seq
from Bio import SeqIO
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

import modules

### Actual behaviour

ImportError: cannot import name 'BiopythonParserWarning' from 'Bio' (unknown location)

**Comment by MarkusPiotrowski** [comment] 2019-12-11 20:24
@Nancy1030 Can you please do what the issue template suggests? Please run this code and report the output:
```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
It would also be nice to run your example manually line by line so that it becomes clear, which of these lines throws the error.

**Comment by Nancy1030** [comment] 2019-12-11 21:00
### Setup

I am reporting a problem with Biopython import as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

>>> import sys; print(sys.version)
3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Windows-10-10.0.17134-SP0
>>> import Bio; print(Bio.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'Bio' has no attribute '__version__'


### Expected behaviour

import Bio
from Bio import Seq
from Bio import SeqIO

### Actual behaviour

ImportError: cannot import name 'BiopythonParserWarning' from 'Bio' (unknown location)

### Steps to reproduce

run in python 3.7.7 and biopython 1.75:

**Comment by MarkusPiotrowski** [comment] 2019-12-11 21:26
Can you try:
```python
>>> import Bio
>>> help(Bio)
```

**Comment by Nancy1030** [comment] 2019-12-11 22:07
>>> help(Bio)
Help on package Bio:

NAME
    Bio

PACKAGE CONTENTS
    Affy (package)
    Align (package)
    AlignIO (package)
    Alphabet (package)
    Application (package)
    Blast (package)
    CAPS (package)
    Cluster (package)
    Compass (package)
    Crystal (package)
    Data (package)
    Emboss (package)
    Entrez (package)
    ExPASy (package)
    FSSP (package)
    File
    GenBank (package)
    Geo (package)
    Graphics (package)
    HMM (package)
    Index
    KDTree (package)
    KEGG (package)
-- More  --

**Comment by Nancy1030** [comment] 2019-12-11 22:08
>>> import Bio
>>> help(Bio)
Help on package Bio:

NAME
    Bio

PACKAGE CONTENTS
    Affy (package)
    Align (package)
    AlignIO (package)
    Alphabet (package)
    Application (package)
    Blast (package)
    CAPS (package)
    Cluster (package)
    Compass (package)
    Crystal (package)
    Data (package)
    Emboss (package)
    Entrez (package)
    ExPASy (package)
    FSSP (package)
    File
    GenBank (package)
    Geo (package)
    Graphics (package)
    HMM (package)
    Index
    KDTree (package)
    KEGG (package)
    LogisticRegression
    MarkovModel
    MaxEntropy
    Medline (package)
    NMR (package)
    NaiveBayes
    Nexus (package)
    PDB (package)
    Pathway (package)
    Phylo (package)
    PopGen (package)
    Restriction (package)
    SCOP (package)
    SVDSuperimposer (package)
    SearchIO (package)
    Seq
    SeqFeature
    SeqIO (package)
    SeqRecord
    SeqUtils (package)
    Sequencing (package)
    Statistics (package)
    SubsMat (package)
    SwissProt (package)
    TogoWS (package)
    UniGene (package)
    UniProt (package)
    Wise (package)
    _py3k (package)
    _utils
    bgzf
    codonalign (package)
    cpairwise2
    kNN
    motifs (package)
    pairwise2
    phenotype (package)
    trie
    triefind

FILE
    (built-in)

**Comment by MarkusPiotrowski** [comment] 2019-12-11 22:48
Actually, this is not the expected result. It should start with:

```bash
>>> import Bio
>>> help(Bio)
Help on package Bio:

NAME
    Bio - Collection of modules for dealing with biological data in Python.

FILE
    c:\program files\XXXX

DESCRIPTION
    The Biopython Project is an international association of developers
    of freely available Python tools for computational molecular biology.

    http://biopython.org

PACKAGE CONTENTS
    Affy (package)
    ...
```

You propably have a wrong `__init__.py` file in you `Bio` folder? This should start with

```python
# Copyright 1999-2003 by Jeffrey Chang.  All rights reserved.
#
# This file is part of the Biopython distribution and governed by your
# choice of the "Biopython License Agreement" or the "BSD 3-Clause License".
# Please see the LICENSE file that should have been included as part of this
# package.
"""Collection of modules for dealing with biological data in Python.

The Biopython Project is an international association of developers
of freely available Python tools for computational molecular biology.

http://biopython.org
"""

import os
import warnings

__version__ = "1.75"
...
```

Can you tell how you installed Biopython?

**Comment by Nancy1030** [comment] 2019-12-11 22:50
I used pip install biopython in conda

**Comment by MarkusPiotrowski** [comment] 2019-12-11 23:13
What's about your `__init__.py` in the `Bio` folder? (You will find it in your conda folder under \Lib\site-packages\Bio). Does it look as I have shown above?

**Comment by MarkusPiotrowski** [comment] 2019-12-13 12:22
@Nancy1030 
For sure there is something wrong with your installation. It seems clear that a) you have a Biopython installation (all the modules and packages seem to be present) but b) either you have a wrong `__init__.py` file in your `Bio` folder or Python is somehow referring to a wrong `__init__.py`.  Without `__init__.py` you shouldn't be able to do `import Bio`, but `help Bio` didn't show the expected messages and the missing attribute  `__version__` also indicate that a wrong init file is called. Also (c the location of the file as `built-in`  (as reported by help) is strange.

I tried several things but am not able to 100% reproduce the errors that you got. You may check several things:
- When using conda, do you activate it?
- Do you have several `Bio` folders in different locations? 

But most interestingly would be the exact location of your `Bio` folder within your Python installation and the content of the Bio `__init__.py` file.

Since you didn't respond to my last question, I'm not sure if you are still interested in this issue.

**Comment by Nancy1030** [comment] 2019-12-14 01:17
Thanks for following. As I was trying to figure out this problem, my python was messed up. So I reinstalled everything, and biopython seem to work now. 

One possibility is that, I had installed a package called"Bio" before biopython, which was deleted it after installing biopython. And this biopython package is installed as "bio", and later I change folder name into upper case.

In my new installed python, the biopython was installed as "Bio", capital case. And it worked fine.

**Comment by MarkusPiotrowski** [comment] 2019-12-14 17:18
This was exactly what I guessed, we stumbled across this `Bio` installation problem (with a lowercase `bio` folder) already twice, at least (#2238, #2363). 
However, since you manually changed the folder name into uppercase `Bio`, there were no obvious indications for that.

Good that you got it running, so I'm closing this issue now.

**Closed by MarkusPiotrowski** 2019-12-14 17:18 UTC
