### ISSUE TITLE
Wrong result with long pubmedid

### ISSUE THREAD

**Issue by LeonardoCoelho71950** [biopython/biopython#1048] opened 2017-01-24 10:58 UTC
I faced a problem when I tried to fetch publications with a long number, It casts the number to the scientific notation. For example, 1.1111111111111111e+35. And returns the pubmeds 1 and 35. Instead of giving an error.

**Comment by peterjc** [comment] 2017-01-24 11:01
Can you give ``Bio.Entrez`` the ID as a string yourself?

If that fixes it, we need to look at the automatic conversion of int/long into a string. Since the Python version is important here, could you provide more details of your setup?

**Comment by LeonardoCoelho71950** [comment] 2017-01-24 11:05
My input was this: 111111111111111111111111111111111111
Btw, my biopython version is: 1.63
And Python: 2.7

**Comment by LeonardoCoelho71950** [comment] 2017-01-24 11:06
And I was already giving it as a string

**Comment by peterjc** [comment] 2017-01-24 12:22
Can you provide the relevant code you are using please (ideally a small self contained example)? I am only guessing you are using the ``Bio.Entrez`` module here.

**Comment by peterjc** [comment] 2017-01-24 12:23
Also Biopython 1.63 is very old, please try the current release Biopython 1.68 which includes switching to using HTTPS rather than HTTP for accessing the NCBI web-services.

**Comment by LeonardoCoelho71950** [comment] 2017-01-24 12:25
`handle = Entrez.efetch(db='pubmed', id=self.pmid, retmode='xml')
record = Entrez.read(handle)`

where self.pmid is a string with the pubmedid

**Comment by peterjc** [comment] 2017-01-24 12:46
I'm pretty sure the NCBI is simply rejecting the invalid PubMed ID, but right now I think the site might be under heavy load as I'm getting ``HTTP Error 502: Bad Gateway`` using this code:

``` python
>>> handle = Entrez.efetch(db="pubmed", id=pmid, retmode="xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/Entrez/__init__.py", line 180, in efetch
    return _open(cgi, variables, post=post)
  File "/Library/Python/2.7/site-packages/Bio/Entrez/__init__.py", line 526, in _open
    raise exception
urllib2.HTTPError: HTTP Error 502: Bad Gateway
```

Since I got an exception I can't do ``print(handle.url)`` so wrapping this to access the URL via the exception,

``` python
from Bio import Entrez
from urllib2 import HTTPError
Entrez.email = "p.j.a.cock@googlemail.com"
pmid = "111111111111111111111111111111111111"
try:
    handle = Entrez.efetch(db="pubmed", id=pmid, retmode="xml")
    print(handle.url)
except HTTPError as e:
    print(e)
    print(e.url)
```

Giving:

```
HTTP Error 502: Bad Gateway
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?email=p.j.a.cock%40googlemail.com&tool=biopython&db=pubmed&id=111111111111111111111111111111111111&retmode=xml
```

We need to retest later once the server is less busy, but this shows that the latest Biopython code at least is using a sensible URL.

Could you try this example to check the URL please?

**Comment by peterjc** [comment] 2017-01-24 13:40
I'm now getting this (rather than the typical temporary network error of ``Bad Gateway``), which seems to me to be a sensible response from the NCBI when given a clearly invalid PubMed ID:

```
HTTP Error 400: Bad Request
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=111111111111111111111111111111111111&retmode=xml&tool=biopython&email=p.j.a.cock%40googlemail.com
```

As per https://www.nlm.nih.gov/bsd/mms/medlineelements.html#pmid PMID is a one to eight digit number.

**Comment by peterjc** [comment] 2018-07-04 15:06
I think this is working as intended (giving an error for an invalid ID), closing.

**Closed by peterjc** 2018-07-04 15:06 UTC
