### ISSUE TITLE
Building Debian jessie packages for 1.65 fails during tests

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#540] opened 2015-05-08 15:05 UTC
Hi folks,

I'm currently trying to build Biopython 1.65 for Debian jessie by stealing the debian/ directory from the jessie Biopython 1.64 package. After removing the PowerPC patch that is already included in 1.65, a debuild seems to go through until it fails during the test run with the following traceback:

```
...
Bio.PDB.Selection docstring test ... ok
======================================================================
FAIL: test_some_abs (test_SeqIO_index.NewIndexTest)
Check absolute filenames in index.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Tests/test_SeqIO_index.py", line 269, in test_some_abs
    self.check(t, expt_sff_files, expt_sff_files)
  File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Tests/test_SeqIO_index.py", line 204, in check
    self.assertEqual(filenames, expt_sff_files)
AssertionError: Lists differ: [u'buildd/python-biopython-1.6... != ['/tmp/buildd/python-biopython...

First differing element 0:
buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Tests/Roche/E3MFGYR02_no_manifest.sff
/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Tests/Roche/E3MFGYR02_no_manifest.sff

Diff is 661 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: Peaklist (Bio.NMR.xpktools)
Doctest: Bio.NMR.xpktools.Peaklist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.NMR.xpktools.Peaklist
  File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 61, in Peaklist

----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 93, in Bio.NMR.xpktools.Peaklist
Failed example:
    peaklist = Peaklist('../Doc/examples/nmr/noed.xpk')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist[1]>", line 1, in <module>
        peaklist = Peaklist('../Doc/examples/nmr/noed.xpk')
      File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 106, in __init__
        with open(infn, 'r') as infile:
    IOError: [Errno 2] No such file or directory: '../Doc/examples/nmr/noed.xpk'
----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 94, in Bio.NMR.xpktools.Peaklist
Failed example:
    peaklist.firstline
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist[2]>", line 1, in <module>
        peaklist.firstline
    NameError: name 'peaklist' is not defined
----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 96, in Bio.NMR.xpktools.Peaklist
Failed example:
    peaklist.dataset
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist[3]>", line 1, in <module>
        peaklist.dataset
    NameError: name 'peaklist' is not defined
----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 98, in Bio.NMR.xpktools.Peaklist
Failed example:
    peaklist.sf
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist[4]>", line 1, in <module>
        peaklist.sf
    NameError: name 'peaklist' is not defined
----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 100, in Bio.NMR.xpktools.Peaklist
Failed example:
    peaklist.datalabels
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist[5]>", line 1, in <module>
        peaklist.datalabels
    NameError: name 'peaklist' is not defined


======================================================================
FAIL: residue_dict (Bio.NMR.xpktools.Peaklist)
Doctest: Bio.NMR.xpktools.Peaklist.residue_dict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.NMR.xpktools.Peaklist.residue_dict
  File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 119, in residue_dict

----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 139, in Bio.NMR.xpktools.Peaklist.residue_dict
Failed example:
    peaklist = Peaklist('../Doc/examples/nmr/noed.xpk')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist.residue_dict[1]>", line 1, in <module>
        peaklist = Peaklist('../Doc/examples/nmr/noed.xpk')
      File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 106, in __init__
        with open(infn, 'r') as infile:
    IOError: [Errno 2] No such file or directory: '../Doc/examples/nmr/noed.xpk'
----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 140, in Bio.NMR.xpktools.Peaklist.residue_dict
Failed example:
    residue_d = peaklist.residue_dict('H1')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist.residue_dict[2]>", line 1, in <module>
        residue_d = peaklist.residue_dict('H1')
    NameError: name 'peaklist' is not defined
----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 141, in Bio.NMR.xpktools.Peaklist.residue_dict
Failed example:
    sorted(residue_d.keys())
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist.residue_dict[3]>", line 1, in <module>
        sorted(residue_d.keys())
    NameError: name 'residue_d' is not defined
----------------------------------------------------------------------
File "/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build/Bio/NMR/xpktools.py", line 143, in Bio.NMR.xpktools.Peaklist.residue_dict
Failed example:
    residue_d['10']
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.NMR.xpktools.Peaklist.residue_dict[4]>", line 1, in <module>
        residue_d['10']
    NameError: name 'residue_d' is not defined


----------------------------------------------------------------------
Ran 219 tests in 90.094 seconds

FAILED (failures = 2)
Skipping any tests requiring internet access
Python version: 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]
Operating system: posix linux2
E: pybuild pybuild:256: test: plugin custom failed with: exit code=1: set -e; \
                             mkdir -p '/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build'/home; \
                             mkdir -p '/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build'/Doc; \
                             cp -a Doc/Tutorial.tex '/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build'/Doc; \
                             cp -a Tests '/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build'; \
                             cd '/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build'/Tests; \
                             env DIALIGN2_DIR=/usr/share/dialign EMBOSS_ROOT=/usr/lib/emboss HOME='/tmp/buildd/python-biopython-1.65~jessie/.pybuild/pythonX.Y_2.7/build'/home python2.7 run_tests.py --offline
dh_auto_test: pybuild --test -i python{version} -p 2.7 --test --system=custom --test-args=set -e; \
                             mkdir -p {build_dir}/home; \
                             mkdir -p {build_dir}/Doc; \
                             cp -a Doc/Tutorial.tex {build_dir}/Doc; \
                             cp -a Tests {build_dir}; \
                             cd {build_dir}/Tests; \
                             env DIALIGN2_DIR=/usr/share/dialign EMBOSS_ROOT=/usr/lib/emboss HOME={build_dir}/home {interpreter} run_tests.py --offline --dir . returned exit code 13
debian/rules:71: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 13
make[1]: Leaving directory '/tmp/buildd/python-biopython-1.65~jessie'
debian/rules:53: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

**Comment by peterjc** [comment] 2015-05-08 15:16
Is this a "normal" 64-bit Linux machine? Nothing strange like PowerPC etc?

There seems to be some subtlety with the paths meaning ``../Doc/examples/nmr/noed.xpk`` is not found (which likely explains all the downstream doctests failing). Likewise, the ``test_some_abs`` failure in ``test_SeqIO_index.NewIndexTest`` is something odd about paths.

Can you try ``python2.7 setup.py build`` and ``python2.7 setup.py test`` outside the Debian build process but on the same machine (with the same Python etc)?

**Comment by kblin** [comment] 2015-05-08 15:19
I can try, but this is in pbuilder jessie chroot on an Ubuntu trusty host. :) I do have a jessie VM lying around somewhere, so a "proper" debuild should be doable.

**Comment by peterjc** [comment] 2015-05-08 15:23
We may have to ask the Debian/DebianMed team, e.g. @tillea did the most recent package (Biopython 1.64).

**Comment by tillea** [comment] 2015-05-08 15:46
Hi,

could you please provide any deep link to the issue.  BTW, I'll hope to
find the time to update testing to the latest BioPython anyway.

Kind regards

       Andreas.

On Fri, May 08, 2015 at 08:23:48AM -0700, Peter Cock wrote:
> We may have to ask the Debian/DebianMed team, e.g. @tillea did the most recent package (Biopython 1.64).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/biopython/biopython/issues/540#issuecomment-100272057

-- 
http://fam-tille.de

**Comment by peterjc** [comment] 2015-05-08 15:51
Hi Andreas.

Maybe I misunderstood your query, but other than a brief preceding discussion on Twitter, this Biopython GitHub issue 540 is the only link. i.e. https://github.com/biopython/biopython/issues/540

Do you want us to raise this with Debian / DebianMed?

Thanks,

Peter

**Comment by kblin** [comment] 2015-05-09 00:21
Ok, the `test_some_abs` error is reproducible on a clean test VM, let me test this on my dev box running Ubuntu 14.04.

**Comment by tillea** [comment] 2015-05-09 06:30
On Fri, May 08, 2015 at 05:21:14PM -0700, Kai Blin wrote:
> Ok, the `test_some_abs` error is reproducible on a clean test VM, let me test this on my dev box running Ubuntu 14.04. 

I injected packaging stuff for 1.65 into SVN and can confirm that the
following error occures:

FAIL: test_some_abs (test_SeqIO_index.NewIndexTest)
Check absolute filenames in index.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/python-biopython-1.65+dfsg/.pybuild/pythonX.Y_2.7/build/Tests/test_SeqIO_index.py", line 269, in test_some_abs
    self.check(t, expt_sff_files, expt_sff_files)
  File "/tmp/buildd/python-biopython-1.65+dfsg/.pybuild/pythonX.Y_2.7/build/Tests/test_SeqIO_index.py", line 204, in check
    self.assertEqual(filenames, expt_sff_files)
AssertionError: Lists differ: [u'buildd/python-biopython-1.6... != ['/tmp/buildd/python-biopython...

First differing element 0:
buildd/python-biopython-1.65+dfsg/.pybuild/pythonX.Y_2.7/build/Tests/Roche/E3MFGYR02_no_manifest.sff
/tmp/buildd/python-biopython-1.65+dfsg/.pybuild/pythonX.Y_2.7/build/Tests/Roche/E3MFGYR02_no_manifest.sff

Diff is 649 characters long. Set self.maxDiff to None to see it.


I admit I have no idea how to fix this.

Kind regards

        Andreas.

-- 
http://fam-tille.de

**Comment by kblin** [comment] 2015-05-09 07:28
Hm, can't repro this one on git tag biopython-165 on my ubuntu 14.04 system, the only test that fails is the NCBI_qblast test, but that's an online test that's never run during packaging anyway.

**Comment by peterjc** [comment] 2015-05-09 07:48
Good to know both @kblin and @tillea could reproduce a path mis-match issue within the Debian packaging test framework. I suspect this could be something about the paths and/or chroot used - can you point me at details of this setup? I may be need to try it locally to reproduce it and then debug it.

P.S. The issue with ``test_NCBI_blast.py`` was fixed after Biopython 1.65 https://github.com/biopython/biopython/commit/08c72f8778a87701586a03dffcce33c7589bc6d7 and was due to the NCBI database changing. i.e. Harmless.

**Comment by kblin** [comment] 2015-05-09 07:59
Hey @peterjc, it looks like the code on Debian is doing the right thing and there's a bug in some version of something in Ubuntu that causes the test to pass.

I'm looking at the check function in test_SeqIO_index.py, where `raw_filenames` is called. Then there's a test to make sure `flag` is True, which as far as I understand indicates that filenames are relative to the index file, i.e. **not** absolute. The next `assertEqual` checks for equality with a list of absolute filenames. This should never work, and on Debian, it doesn't. Here's what an excerpt of the index file looks like on Debian:
```SQL
INSERT INTO "meta_data" VALUES('filenames_relative_to_index','True');
CREATE TABLE file_data (file_number INTEGER, name TEXT);
INSERT INTO "file_data" VALUES(0,'biopython-biopython-165/Tests/Roche/E3MFGYR02_no_manifest.sff');
INSERT INTO "file_data" VALUES(1,'biopython-biopython-165/Tests/Roche/greek.sff');
INSERT INTO "file_data" VALUES(2,'biopython-biopython-165/Tests/Roche/paired.sff');
```
As you can see, filenames are relative to the index indeed, and comparing these against a list with the absolute path should fail.

The same index on Ubuntu 14.04 looks like this:
```SQL
INSERT INTO "meta_data" VALUES('filenames_relative_to_index','True');
CREATE TABLE file_data (file_number INTEGER, name TEXT);
INSERT INTO "file_data" VALUES(0,'/data/dev/libs/biopython/Tests/Roche/E3MFGYR02_no_manifest.sff');
INSERT INTO "file_data" VALUES(1,'/data/dev/libs/biopython/Tests/Roche/greek.sff');
INSERT INTO "file_data" VALUES(2,'/data/dev/libs/biopython/Tests/Roche/paired.sff');
```
So the index file claims paths are relative to the index, but they're clearly not.
Not sure what's going on here.

**Comment by kblin** [comment] 2015-05-09 08:01
Ah, bingo, it's not Ubuntu, it's where the biopython test files live. Can reproduce this on my Ubuntu system when I clone biopython to /tmp

**Comment by kblin** [comment] 2015-05-09 08:46
Ok, spun this out to another issue, as there's more than just this failure when trying to do a Debian build.

**Comment by kblin** [comment] 2015-05-09 09:09
Ok, with the following changes (apart from bumping the release numbers in debian/changelog), 1.65 builds in a jessie pbuilder for me:
```diff
Only in debian.orig/patches: fix_test_problem_on_powerpc.patch
diff -ur debian.orig/patches/series debian/patches/series
--- debian.orig/patches/series	2015-05-09 11:02:22.046561064 +0200
+++ debian/patches/series	2015-05-08 16:20:46.120858588 +0200
@@ -1,2 +1 @@
 remove_mathml-qname.patch
-fix_test_problem_on_powerpc.patch
diff -ur debian.orig/rules debian/rules
--- debian.orig/rules	2015-05-09 11:02:22.046561064 +0200
+++ debian/rules	2015-05-09 10:53:02.555786699 +0200
@@ -42,7 +42,7 @@
 #        specifically since test_ColorSpiral and test_trie are running when called manually
 #        .
 #        Regarding the Tutorial test it depends from a fix for python-reportlab (see #745985)
-EXCLUDEFAILINGTESTS=GenomeDiagram Fasttree_tool Mafft_tool Tutorial ColorSpiral trie
+EXCLUDEFAILINGTESTS=GenomeDiagram Fasttree_tool Mafft_tool Tutorial ColorSpiral trie SeqIO_index
 
 # FIXME: Currently it is not sure for what architecture samtools will be available
 #        to anable a smooth migration to testing the build-dependency will be dropped
@@ -86,8 +86,9 @@
 	LC_ALL=C.UTF-8 dh_auto_test -- --test --system=custom \
 		--test-args='set -e; \
                              mkdir -p {build_dir}/home; \
-                             mkdir -p {build_dir}/Doc; \
+                             mkdir -p {build_dir}/Doc/examples/nmr; \
                              cp -a Doc/Tutorial.tex {build_dir}/Doc; \
+                             cp -a Doc/examples/nmr/noed.xpk {build_dir}/Doc/examples/nmr; \
                              cp -a Tests {build_dir}; \
                              cd {build_dir}/Tests; \
                              env DIALIGN2_DIR=/usr/share/dialign EMBOSS_ROOT=/usr/lib/emboss HOME={build_dir}/home {interpreter} run_tests.py --offline'
```
So I remove a patch that is included in 1.65, I skip the wonky SeqIO_index test and I make sure the Debian build env has the `noed.xpk` file.
@tillea, if you want that diff file, let me know how to best send it to you. If @peterjc can fix the SeqIO_index test, we could just patch that instead of skipping the whole test.

**Comment by tillea** [comment] 2015-05-09 15:12
Hi,

On Sat, May 09, 2015 at 02:09:17AM -0700, Kai Blin wrote:
> Ok, with the following changes (apart from bumping the release numbers in debian/changelog), 1.65 builds in a jessie pbuilder for me:

One part of the patch was just commited this morning by me into
the packaging SVN.  However, the part marked below is just hiding
the problem by excluding the test:

> diff -ur debian.orig/rules debian/rules
> --- debian.orig/rules	2015-05-09 11:02:22.046561064 +0200
> +++ debian/rules	2015-05-09 10:53:02.555786699 +0200
> @@ -42,7 +42,7 @@
>  #        specifically since test_ColorSpiral and test_trie are running when called manually
>  #        .
>  #        Regarding the Tutorial test it depends from a fix for python-reportlab (see #745985)
> -EXCLUDEFAILINGTESTS=GenomeDiagram Fasttree_tool Mafft_tool Tutorial ColorSpiral trie
> +EXCLUDEFAILINGTESTS=GenomeDiagram Fasttree_tool Mafft_tool Tutorial ColorSpiral trie SeqIO_index

Here you simply exclude SeqIO_index which is the failing test - I'd
prefer to rather fix the test.
  
>  # FIXME: Currently it is not sure for what architecture samtools will be available
>  #        to anable a smooth migration to testing the build-dependency will be dropped
> @@ -86,8 +86,9 @@
>  	LC_ALL=C.UTF-8 dh_auto_test -- --test --system=custom \
>  		--test-args='set -e; \
>                               mkdir -p {build_dir}/home; \
> -                             mkdir -p {build_dir}/Doc; \
> +                             mkdir -p {build_dir}/Doc/examples/nmr; \
>                               cp -a Doc/Tutorial.tex {build_dir}/Doc; \
> +                             cp -a Doc/examples/nmr/noed.xpk {build_dir}/Doc/examples/nmr; \
>                               cp -a Tests {build_dir}; \

This is really needed to successfully run the test suite.

> So I remove a patch that is included in 1.65, I skip the wonky SeqIO_index test and I make sure the Debian build env has the `noed.xpk` file.
> @tillea, if you want that diff file, let me know how to best send it to you.

As I said I developed it this morning myself - at least the second part.

> If @peterjc can fix the SeqIO_index test, we could just patch that instead of skipping the whole test.

I'd be interested in a fix for SeqIO_index and I'd support Peters assumption
that it is connected to the fact that the test is running in the target dir
where the *.py files are moved to for beeing installed in the package.

Thanks for the patch anyway

      Andreas.

-- 
http://fam-tille.de

**Comment by tillea** [comment] 2015-05-09 16:24
Hi Peter,

On Sat, May 09, 2015 at 12:48:35AM -0700, Peter Cock wrote:
> Good to know both @kblin and @tillea could reproduce a path mis-match issue within the Debian packaging test framework. I suspect this could be something about the paths and/or chroot used - can you point me at details of this setup? I may be need to try it locally to reproduce it and then debug it.

The build is done in a minimal chroot without internet access.

Another specific thing is that the test is run by

set -e; \
                             mkdir -p {build_dir}/home; \
                             mkdir -p {build_dir}/Doc/examples; \
                             cp -a Doc/Tutorial.tex {build_dir}/Doc; \
                             cp -a Doc/examples/nmr {build_dir}/Doc/examples; \
                             cp -a Tests {build_dir}; \
                             cd {build_dir}/Tests; \
                             env DIALIGN2_DIR=/usr/share/dialign EMBOSS_ROOT=/usr/lib/emboss HOME={build_dir}/home {interpreter} run_tests.py --offline

while {build_dir} will be replaced by the target install dir fitting
the used interpreter.
 
> P.S. The issue with ``test_NCBI_blast.py`` was fixed after Biopython 1.65 https://github.com/biopython/biopython/commit/08c72f8778a87701586a03dffcce33c7589bc6d7 and was due to the NCBI database changing. i.e. Harmless.

Thanks for the information.

Hope this helps reproducing

         Andreas.

-- 
http://fam-tille.de

**Comment by kblin** [comment] 2015-05-09 19:22
the SeqIO_index test is a bit suspicious, as it also fails for me when I clone the biopython repo into /tmp on my development machine.

As you can see in the database dumps from the index files I posed above, the code basically lies in the index about the paths being relative to the index (relative is set to True despite the paths clearly being absolute). Now, the code only doesn't lie when the index and the biopython repository are in the same directory, because then the paths really are relative.

The test however explicitly expects the code to lie, as it checks the "relative" flag is set to True, and then in the next step expects to see absolute paths. When the code actually does the right thing, the test fails.

As the code comes with @peterjc's copyright message, I figured fixing this would be easier for him. :)

**Comment by peterjc** [comment] 2015-05-11 09:52
Yes, I'm probably the best person to fix issue #541 in ``test_SeqIO_index.py`` when run from under ``$TMPDIR``. It looks like a mistake in the tests though, rather than the indexing itself - so skipping the test is not unreasonable. Alternatively, I would expect this to be a small commit, which ought to be easy to back-port to Biopython 1.65 if that's what you'd prefer to do for the Debian package.

**Comment by tillea** [comment] 2015-05-11 10:05
Hi Peter,

On Mon, May 11, 2015 at 02:52:23AM -0700, Peter Cock wrote:
> Yes, I'm probably the best person to fix issue #541 in ``test_SeqIO_index.py`` when run from under ``$TMPDIR``.

:-)

> It looks like a mistake in the tests though, rather than the indexing itself

This is what was to be expected considering the issue which was just
cause by the location of the files.

> - so skipping the test is not unreasonable. Alternatively, I would expect this to be a small commit, which ought to be easy to back-port to Biopython 1.65 if that's what you'd prefer to do for the Debian package.

I'd prefer a simple patch if you don't mind.

Kind regards and thanks a lot for your cooperation

     Andreas.

-- 
http://fam-tille.de

**Comment by peterjc** [comment] 2015-05-11 14:38
This ought to work as a patch, https://github.com/biopython/biopython/commit/cf54c6c5a99be1127fdbd839ea01067ffc21f302 or https://github.com/biopython/biopython/commit/cf54c6c5a99be1127fdbd839ea01067ffc21f302.patch (remove the comments if you like).

**Comment by peterjc** [comment] 2015-05-11 15:14
@kblin RE: "*I'm looking at the check function in test_SeqIO_index.py, where raw_filenames is called. Then there's a test to make sure flag is True, which as far as I understand indicates that filenames are relative to the index file, i.e. not absolute. ...*"

Sorry I missed this question earlier. As I wrote on #541, the flag in the SQLite index file was introduced in Biopython 1.65 and determines if any relative paths are relative to the index file (new default behaviour) or to the current directory (historical behaviour). If a path is recorded with a leading `/` then it is always simply an absolute path.

**Comment by tillea** [comment] 2015-05-11 19:37
Hi Peter,

thanks.  I injected this patch into packaging VCS.  I plan to do some
more changes for instance adding phylip which was freed recently and
will upload soon.

Kind regards

     Andreas.

On Mon, May 11, 2015 at 07:38:41AM -0700, Peter Cock wrote:
> This ought to work as a patch, https://github.com/biopython/biopython/commit/cf54c6c5a99be1127fdbd839ea01067ffc21f302 or https://github.com/biopython/biopython/commit/cf54c6c5a99be1127fdbd839ea01067ffc21f302.patch (remove the comments if you like).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/biopython/biopython/issues/540#issuecomment-100928533

-- 
http://fam-tille.de

**Comment by peterjc** [comment] 2020-07-22 13:47
I'm assuming this was resolved from the Debian team's point of view. And the test fix is already in biopython.

Closing - thanks all.

**Closed by peterjc** 2020-07-22 13:47 UTC
