### ISSUE TITLE
Conversion from embl to fasta fails

### ISSUE THREAD

**Issue by ofajardo** [biopython/biopython#1368] opened 2017-08-18 15:40 UTC
### Setup

I am reporting a problem with Biopython version 1.68 and 1.70, Python version 2.7.11, and operating
system windows 7 and linux Red Hat as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
(On linux)
2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
CPython
Linux-2.6.32-431.20.3.el6.x86_64-x86_64-with-redhat-6.3-Santiago
1.68

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

Using SeqIO SeqIO.convert to convert from a protein embl file to fasta file should give a good output. In Biopython 1.66 it is still working, but broken in 1.68 and 1.70.

### Actual behaviour

fasta file produced is full of ????? instead of aminoacids.

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

Python code:

````python
from Bio import SeqIO

file_handler_emblFile = open("101ma.entret")
file_handler_fastaFile = open("101ma.fasta", "w")
count = SeqIO.convert(file_handler_emblFile, "embl", file_handler_fastaFile, "fasta")
````

embl input file 101ma.entret:

```
ID   101MA                             Unannotated; unspecified; UNC;                154 AA.
DT   1997-12-13 (PDB date in HEADER line)
DE   MOLECULE:MYOGLOBIN; MISC:; ENGINEERED:YES; CHAIN:A; MUTATION:YES;
OS   PHYSETER CATODON
KW   LIGAND BINDING, OXYGEN STORAGE, OXYGEN BINDING, HEME, OXYGEN TRANSPORT
SQ   Sequence 154 AA;
     MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAE
     MKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISE
     AIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG
//
```

fasta output in biopython 1.66 (correct)

```
>101MA MOLECULE:MYOGLOBIN; MISC:; ENGINEERED:YES; CHAIN:A; MUTATION:YES;
MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASE
DLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRH
PGNFGADAQGAMNKALELFRKDIAAKYKELGYQG
```

fasta output in biopython 1.68 and 1.7.0 (wrong)

```
>101MA MOLECULE:MYOGLOBIN; MISC:; ENGINEERED:YES; CHAIN:A; MUTATION:YES;
????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????
??????????????????????????????????
```

**Comment by ofajardo** [comment] 2017-08-18 15:42
Files with an extra .txt so that this page lets me attach


[101ma_168.fasta.txt](https://github.com/biopython/biopython/files/1234871/101ma_168.fasta.txt)
[101ma.entret.txt](https://github.com/biopython/biopython/files/1234872/101ma.entret.txt)
[101ma_166.fasta.txt](https://github.com/biopython/biopython/files/1234870/101ma_166.fasta.txt)

**Comment by peterjc** [comment] 2017-08-18 16:01
Confirmed using latest Biopython from github and Python 2.7 and 3.6 on macOS.

This is not a problem in the convert function itself, parse/write also fails:

```
count = SeqIO.write(SeqIO.parse(file_handler_emblFile, "embl"),  file_handler_fastaFile, "fasta")
```

as too does simply using parse:

```
for record in SeqIO.parse(file_handler_emblFile, "embl"):
    print(record.seq)
```

Where does the input file ``101ma.entret`` come from please?

**Comment by peterjc** [comment] 2017-08-18 16:09
Confirming this worked on Biopython 1.67,

```
$ python3 -c "from Bio import SeqIO; print(repr(SeqIO.read('/tmp/101ma.entret', 'embl').seq)); import Bio; print(Bio.__version__)"
Seq('MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEA...YQG', Alphabet())
1.67
```

(Although note it did not label the sequence as protein)

This broke in Biopython 1.68,

```
$ python3 -c "from Bio import SeqIO; print(repr(SeqIO.read('/tmp/101ma.entret', 'embl').seq)); import Bio; print(Bio.__version__)"
UnknownSeq(154, alphabet = Alphabet(), character = '?')
1.68
```

**Comment by peterjc** [comment] 2017-08-18 16:20
I believe this was caused by 81a2cee65da4198af3021df1d4ef1160e3812dfc which did not consider the special case of not-quite-valid sequence lines which are missing the coordinates at the end of each line of sequence.

As noted above, I'd like to know where your EMBL file came from.

**Comment by peterjc** [comment] 2017-08-18 16:29
Possible fix on https://github.com/biopython/biopython/pull/1369 - are you familiar with git and how to install Biopython from source order to test this?

If the example EMBL file ``101ma.entret`` is not from a public source, may we have your permission to use it as a test case?

**Comment by ofajardo** [comment] 2017-08-19 10:21
Hi, 

The embl file was generated with the Emboss command entret (thats where the extension is coming from). I tried with several other variants as well and none did work. I chose this as example, as I would consider that the output of Emboss should be a standard and something that biopython should be able to deal with. By the way, what is the standard for embl files that biopython takes?
The sequence is from public source, it is the PDB structure 101M, chain A, so you can use it as you wish.
I just cloned biopython repo and tried again with no success. I will be happy to test again.
Thanks for looking at it!

**Comment by ofajardo** [comment] 2017-08-19 10:38
For completeness here the original output from Emboss entret.
[101ma_original.entret.txt](https://github.com/biopython/biopython/files/1236266/101ma_original.entret.txt)

**Comment by peterjc** [comment] 2017-08-19 21:57
Thanks for the extra info - if you can check the version of EMBOSS you have, that may be useful too.

Regarding git, you'd need to checkout my branch to test the proposed fix - it isn't (yet) on the main Biopython master branch. However, with that test case etc I'll probably have this included next week...

**Comment by ofajardo** [comment] 2017-08-20 10:09
The Emboss version is 6.6.0.0

I cloned https://github.com/peterjc/biopython.git and tested, but again got the ???? characters instead of the aminoacids.

**Comment by peterjc** [comment] 2017-08-21 11:18
After cloning my repository you'd need to do something like ``git checkout -t peterjc/embl_no_coord`` to try the branch from pull request #1369

Thanks for checking the EMBOSS version - that should be useful.

Regarding the EMBL file format as defined by the EBI at ftp://ftp.ebi.ac.uk/pub/databases/ena/sequence/release/doc/usrman.txt this says:

```
3.4.17  The SQ Line
The SQ (SeQuence header) line marks the beginning of the sequence data and 
Gives a summary of its content. An example is:
     SQ   Sequence 1859 BP; 609 A; 314 C; 355 G; 581 T; 0 other; 
As shown, the line contains the length of the sequence in base pairs followed
by its base composition.  Bases other than A, C, G and T are grouped 
together as "other". (Note that "BP" is also used for single stranded RNA
sequences, which is not strictly accurate, but has been used for consistency
of format.) This information can be used as a check on accuracy or for
statistical  purposes. The word "Sequence" is present solely as a marker for
readability.

3.4.18 The Sequence Data Line
The sequence data line has a line code consisting of two blanks. The sequence
is written 60 bases per line, in groups of 10 bases separated by a blank
character, beginning at position 6 of the line. The direction listed is 
always 5' to 3', and wherever possible the non-coding strand 
(homologous to the message) has been stored. Columns 73-80 of each 
sequence line contain base numbers for easier reading and quick 
location of regions of interest. The numbers are right justified and indicate
the number of the last base on each line.
An example of a data line is:
     aaacaaacca aatatggatt ttattgtagc catatttgct ctgtttgtta ttagctcatt        60
      
The characters used for the bases correspond to the IUPAC-IUB 
Commission recommendations (see appendices).
```

i.e. This does seem like an EMBOSS bug if the numbers are missing in columns 73-80.

**Comment by peterjc** [comment] 2017-08-21 11:30
What file did you give to EMBOSS ``seqret`` to make this EMBL (like) file, and how did you run it?

I've tried starting from the PDB file from http://www.rcsb.org/pdb/explore/webMol.do?structureId=101M

EMBOSS will happily turn the PDB file into FASTA:

```
$ seqret -sequence 101m.pdb -filter -osformat pearson
>101M_A
VLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASED
LKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHP
GNFGADAQGAMNKALELFRKDIAAKYKELGYQG
```

However, it refused to make a protein EMBL file:

```
$ seqret -sequence 101m.pdb -filter -osformat embl
Error: Sequence format 'embl' not supported for protein sequences
Warning: No sequences written to output file 'stdout'
```

The EBI does provide protein EMBL files for patent sequences etc. Perhaps my EMBOSS is just too old:

My copy of EMBOSS is older though:

```
$ seqret --version
EMBOSS:6.5.7.0
```

**Comment by peterjc** [comment] 2017-08-21 11:31
For interest, using Biopython to convert from the PDB to FASTA:

```
$ python3 -c "import sys; from Bio import SeqIO; SeqIO.convert(sys.stdin, 'pdb-seqres', sys.stdout, 'fasta')" < 101m.pdb 
>101M:A UNP:P02185 MYG_PHYCA
MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASE
DLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRH
PGNFGADAQGAMNKALELFRKDIAAKYKELGYQG
```

```
$ python3 -c "import sys; from Bio import SeqIO; SeqIO.convert(sys.stdin, 'pdb-atom', sys.stdout, 'fasta')" < 101m.pdb 
>101M:A
MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASE
DLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRH
PGNFGADAQGAMNKALELFRKDIAAKYKELGYQG
```

In this example the solved structure seems to be complete as the sequences match. See http://biopython.org/wiki/SeqIO

This is the FASTA file downloaded from http://www.rcsb.org/pdb/explore/webMol.do?structureId=101M

```
$ more 101m_a.fasta 
>101M_A
VLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASED
LKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHP
GNFGADAQGAMNKALELFRKDIAAKYKELGYQG
```

**Comment by ofajardo** [comment] 2017-08-21 14:59
Thanks a lot for the interesting comments. I am surprised that Emboss writes embl files with bugs. The function to generate fasta from pdb with biopython looks good and I potentially could use that in the future.

Regarding your question about how I generated the entret file in first place.

Short answer: A embl database was generated from an embl file such as this. My embl file to generate the database contains of course all public pdbs and some non public ones.

[101ma_original.embl.txt](https://github.com/biopython/biopython/files/1239132/101ma_original.embl.txt)

Long answer: 

I Inherited an old peculiar workflow written in C and I translated to python with the help of another colleague (now gone). We used biopython extensively for it. but trying to keep the logic of the old workflow, aiming on getting the same results.

For this part, what we did, is writing a module to translate PDB files into embl (both from seqres and atom), but keeping some critical lines in the header, then using the resulting embl file to create the embl database. Transforming PDB into fasta for example would make the headers to disappear, and they (the people consuming this emboss database) needed those to do text searches. Later, we needed to do some other stuff with those sequences (blast, basically), so this time we needed them as a fasta. For that purpose we were converting the embl file previously generated into fasta (because these embl files are considered now the "source" for these sequences), and here is where I noticed this issue I am reporting here. So, the embl file here, with a little change in the header is the one we typically give to biopython and not the one coming from emboss, as emboss is installed not in another machine as the one where we run the workflow. The format of this file however was copied from the output of Emboss (from the old workflow actually). I don't know what happens if we would write a good canonical embl, maybe Emboss does not read it?

I guess I could also go directly from PDB to fasta as you suggested, but actually the workflow does work well, so if this conversion works in the future, I feel just to keep as it is rather than investing more on changing it.

**Comment by peterjc** [comment] 2017-08-21 15:06
File formats change, so it may be EMBOSS is matching an older style of EMBL file. For example, their output is missing the ``XX`` lines added in more recent EMBL releases which are basically a redundant separator between other line types. For parsing Biopython does not care about that.

**Comment by peterjc** [comment] 2017-08-21 15:24
GitHub has been a little unreliable today, but hopefully our automated checks on pull request #1369 will pass which now include your test case, thank you.

**Comment by peterjc** [comment] 2017-08-22 09:29
I've merged the pull request so if you are able to re-test with the latest Biopython from git (the default ``master`` branch on the main repository), that would be great. Thank you .

**Comment by ofajardo** [comment] 2017-08-23 17:10
yes, it works well! thanks a lot!

**Comment by peterjc** [comment] 2017-08-24 09:37
Great - thank you!

**Closed by peterjc** 2017-08-24 09:37 UTC
