### ISSUE TITLE
installation of biopython - issue with external symbols

### ISSUE THREAD

**Issue by martymessi** [biopython/biopython#4900] opened 2024-12-30 12:08 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Windows-11-10.0.22631-SP0

### Expected behaviour

i tried to install biopython with the cmd "pip install biopython"   but the installallation does not conclude with success 

### Actual behaviour

 cpairwise2module.obj : error LNK2001: simbolo esterno PyEval_CallObject non risolto
      build\lib.win-amd64-cpython-313\Bio\cpairwise2.cp313-win_amd64.pyd : fatal error LNK1120: 1 esterni non risolti
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2024\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120

before i see some warning as 

Bio/cpairwise2module.c(60): warning C4013: 'PyEval_CallObject' non definita. Verr… considerata come esterna che restituisce un int.
      Bio/cpairwise2module.c(60): warning C4047: '=': 'PyObject *' differisce da 'int' nei livelli di riferimento indiretto
      Bio/cpairwise2module.c(207): warning C4244: '=': conversione da 'Py_ssize_t' a 'int'. Possibile perdita di dati.
      Bio/cpairwise2module.c(208): warning C4244: '=': conversione da 'Py_ssize_t' a 'int'. Possibile perdita di dati.

sorry for the outputs in Italian ,  i can  translate here 
 
possibile perdita di dati = possible data loss 
considerata come esterna che restituisce un int = considered as external that produce integer  
### Steps to reproduce

(*Please fill this in *)

**Comment by peterjc** [comment] 2024-12-30 13:14
Duplicate of #4880, ``cpairwise2module`` was not compatible with Python 3.13.

Same advice, you can:
1. Downgrade to Python 3.12 for now, where pre-compiled wheels are available
2. Stay with Python 3.13, but compile biopython from the latest source from GitHub
3. Stay with Python 3.13, and wait for Biopython 1.85 which I am hoping to do over the winter break, https://mailman.open-bio.org/pipermail/biopython/2024-December/017074.html

**Comment by martymessi** [comment] 2024-12-31 06:40
i have done option 1 , it works and  now i start to play ! thanks

**Closed** 2024-12-31 18:42 UTC
