### ISSUE TITLE
Error parsing ABI files

### ISSUE THREAD

**Issue by MarkDunne** [biopython/biopython#1444] opened 2017-11-07 13:11 UTC
The current master breaks when trying to read FSA files

### Setup

```
>>> import sys; print(sys.version)
2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-16.7.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.71.dev0
```

### Expected behaviour

No Errors

### Actual behaviour

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mark/src/biopython/Bio/SeqIO/__init__.py", line 612, in parse
    for r in i:
  File "/Users/mark/src/biopython/Bio/SeqIO/AbiIO.py", line 425, in AbiIterator
    record = SeqRecord(Seq(seq, alphabet),
UnboundLocalError: local variable 'seq' referenced before assignment
```

### Steps to reproduce

```
>>> from Bio import SeqIO
>>> list(SeqIO.parse('MyFile.fsa', 'abi'))
```

**Comment by bow** [comment] 2017-11-07 13:28
Hi @MarkDunne ,

Hmm..this is unexpected. I could not reproduce this on my machine, either on Python 2 or Python 3. Both are also on the tip of the current master branch (d465649c2). Perhaps this is a MacOS-specific behavior? I do not expect that as well, to be honest.

**Comment by peterjc** [comment] 2017-11-07 13:34
Confirmed using the FSA file in our test suite on my Mac laptop using Apple's Python 2:

```
$ which python
/usr/bin/python
$ python --version
Python 2.7.10
$ python -c "from Bio import SeqIO; print([r.id for r in SeqIO.parse('test.fsa', 'abi')])" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/AbiIO.py", line 409, in AbiIterator
    record = SeqRecord(Seq(seq, alphabet),
UnboundLocalError: local variable 'seq' referenced before assignment
```

Or, for the record, using our test suite:

```
$ python test_SeqIO_AbiIO.py
test_file_type (__main__.TestAbi)
Test if filetype is ABIF. ... ok
test_raw (__main__.TestAbi)
Test access to raw ABIF tags. ... ok
test_seqrecord (__main__.TestAbi)
Test if the extracted seqrecords data are equal to expected values. ... ERROR
test_trim (__main__.TestAbi)
Test if trim works. ... ERROR
test_file_type (__main__.TestAbiFake)
Test if error is raised if filetype is not ABIF. ... ok
test_file_mode (__main__.TestAbiWrongMode)
Test if exception is raised if file is not opened in 'rb' mode. ... ok

======================================================================
ERROR: test_seqrecord (__main__.TestAbi)
Test if the extracted seqrecords data are equal to expected values.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_SeqIO_AbiIO.py", line 245, in test_seqrecord
    record = SeqIO.read(test_data[trace]['handle'], 'abi')
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 664, in read
    first = next(iterator)
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/AbiIO.py", line 409, in AbiIterator
    record = SeqRecord(Seq(seq, alphabet),
UnboundLocalError: local variable 'seq' referenced before assignment

======================================================================
ERROR: test_trim (__main__.TestAbi)
Test if trim works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_SeqIO_AbiIO.py", line 260, in test_trim
    record = SeqIO.read(test_data[trace]['handle'], 'abi-trim')
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 664, in read
    first = next(iterator)
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/Library/Python/2.7/site-packages/Bio/SeqIO/AbiIO.py", line 409, in AbiIterator
    record = SeqRecord(Seq(seq, alphabet),
UnboundLocalError: local variable 'seq' referenced before assignment

----------------------------------------------------------------------
Ran 6 tests in 0.101s

FAILED (errors=2)
```

It works on the same machine using a self-compiled Python 3.4.1

This is unusual - we don't currently have macOS continuous integration (last time I checked, TravisCI did not yet officially support Python on macOS).

**Comment by peterjc** [comment] 2017-11-07 13:39
Correction: I was testing with an older version of the master branch (I rarely use Python 2 on this machine, mostly Python 3). It works now that I've updated to the current master branch, i.e. commit d465649c2f2ef85bbf067bd84d3ac4b6fd46444d

Note my failure was at line 409, likely reflecting a commit prior to the FSA work being merged.

@MarkDunne could you double check you have the latest version of the master branch installed please? i.e. what is the most recent commit listed by  ``git log``?

**Comment by MarkDunne** [comment] 2017-11-07 14:05
@peterjc 

Yes, I am on d465649


`git log -n 3`
```
commit d465649c2f2ef85bbf067bd84d3ac4b6fd46444d (HEAD -> master, origin/master, origin/HEAD)
Author: BioGeek <jeroen.vangoey@gmail.com>
Date:   Tue Oct 31 14:34:19 2017 +0100

    Mention the fixing of typos in NEWS.rst

commit 523438b56b7eab57f629f3fe251b0b1bf636b67b
Author: BioGeek <jeroen.vangoey@gmail.com>
Date:   Tue Oct 31 11:38:18 2017 +0100

    Fix typo: choosen -> chosen

commit f351f2912a032306e51a915d3e7a3cda08446913
Author: BioGeek <jeroen.vangoey@gmail.com>
Date:   Tue Oct 31 11:37:07 2017 +0100

    Fix typo: heterogenous -> heterogeneous (twice)
```

**Comment by bow** [comment] 2017-11-07 14:16
@MarkDunne, aha ~ this looks like a failing check on the `fsa` file then. Currently we define a file as fsa if it has these following tags: `['SpNm1', 'LIMS1', 'CTID1']` (appropriately located on line 404). Looks like your file is missing one of these tag values, so `AbiIO` thinks it's an ABI file that has a sequence (failing the check at line 406).

Would it be possible for us to look into the FSA file you have?

**Comment by MarkDunne** [comment] 2017-11-07 14:20
@bow Sorry I don't think I'll be able able to do that for confidentiality reasons. If you could tell me how to inspect the files, I can let you know what tags there are.

**Comment by bow** [comment] 2017-11-07 14:25
@MarkDunne No worries. If you don't mind a simple print-style debugging, adding this:

    print([t in raw for t in ['SpNm1', 'LIMS1', 'CTID1']])

on line 404, above `is_fsa_file` should show which of the expected-to-be-present tags are not there.

**Comment by peterjc** [comment] 2017-11-07 14:28
@MarkDunne if it helps, you'd only need to email a sample file to Bow in private (we don't need a public sample for debugging this).

**Comment by MarkDunne** [comment] 2017-11-07 14:31
@bow Thanks bow. The output was `[True, True, False]`, so it doesn't contain a `CTID1` tag.

**Comment by bow** [comment] 2017-11-07 14:54
Great, thank you @MarkDunne. Modifying the fsa check to handle this is quite simple (I just pushed a branch [here](https://github.com/bow/biopython/commit/9aa256f254d7516037623e1667a81d8307cd7781)).

That being said, I feel less confident about the fsa file check now. @peterjc , what do you think about making `fsa` a separate file format string that `SeqIO.[read|parse]` accepts?

**Comment by peterjc** [comment] 2017-11-07 17:58
I don't know enough about this file format ecosystem, but if you think so adding ``fsa`` or maybe ``abi-fsa`` as a named (sub)format ought to be fine.

If we do add ``fsa`` as its own top level format, I'd like to deprecate parsing FSA files under the ``abi`` format name.

**Comment by MarkDunne** [comment] 2017-11-07 18:11
There is a document published by ABI specifying the fields in .abi and .fsa ABIF file formats. Maybe this might help to determine the file type.

http://www6.appliedbiosystems.com/support/software_community/ABIF_File_Format.pdf

**Comment by peterjc** [comment] 2017-11-08 11:56
I'm pretty sure we've looked at that before, but worth reviewing again now. Quoting that,

> The fsa file is a file type produced by Data Collection software generating fragment analysis data, with the extension ".fsa". Both the ab1 and fsa files use the ABIF file format.

That to me argues against adding ``fsa`` as a top level format in the SeqIO API.

Sadly they do not seem to state explicitly how to tell the ABI and FSA files apart from the tags, but list lots of instrument specific tags in tables so it can perhaps be deduced.

Do you know which instrument your file is from Mark?

**Comment by MarkDunne** [comment] 2017-11-08 12:01
@peterjc This FSA file comes from an ABI 3500 Series Genetic Analyzer.

I also agree that it seems dubious for FSA files to be the top level file type. It should be ABIF file formats in general. In fact, that was my original understanding from reading the Bio.SeqIO [documentation](http://biopython.org/DIST/docs/api/Bio.SeqIO-module.html). I think it implies that SeqIO.parse is meant to accept 'abif' as a file format, but this is unrecognised.

**Comment by peterjc** [comment] 2017-11-08 13:09
Yes, with hindsight perhaps the format name in SeqIO ought to have been "abif".

**Comment by bow** [comment] 2017-11-08 13:12
My rationale for adding this as a separate file format is simply being explicit. While the underlying file format (ABIF) is technically the same for both `.ab1` and `.fsa` files, the information they store is apparently different.

Under the hood, they would still use the same iterator of course. Only then, for example, there would be another argument passed to the iterator. This is, in some ways, similar to us encoding `abi` and `abi-trim` as separate SeqIO formats.

However I must say that my ideal condition is to have `SeqIO.*` method accept format-specific arguments. So one might say `SeqIO.read('file.fsa', 'abif', is_fsa=True)` or something similar.

The alternative is perhaps to not use the existing tags check at all, but instead only check for the presence of the `PBAS` tag. This is a tag that is supposed to store the sequence, and as far as I know, no sequence is stored in `.fsa` files. Incoming ABIF files without this tag should then be interpreted as fsa files.

**Comment by peterjc** [comment] 2017-11-08 13:14
Checking for the ``PBAS`` tag with a sequence sounds like a good choice, very Pythonic (in terms of object type checking).

**Comment by bow** [comment] 2017-11-08 17:34
Hmm..after more thought, this is indeed perhaps the most sensible thing to do now. The absence of this tag is what caused this buggy behavior essentially. Modifying the check would require minimal change to the code and is still in line with what we currently are doing.

I'm not to keen on scouring the fsa vs ab1 tags from the specs, to be honest, simply because of the worry that there are exceptions out there. We can at least confidently say that there should be no sequence in fsa files :).

I'll update my branch soon and open a merge request.

**Comment by bow** [comment] 2017-11-09 10:28
@MarkDunne and @peterjc, a merge request is now open. If there are no errors and/or objections, I will merge it.

**Comment by peterjc** [comment] 2017-11-09 14:19
Good job. Thanks @MarkDunne for reporting this and working though it with us. Are you able to re-test with the latest master branch now that #1448 has been merged?

**Comment by MarkDunne** [comment] 2017-11-10 11:01
@peterjc @bow Yes this is all working perfectly now. Thank you for fixing this so quickly.

**Comment by peterjc** [comment] 2017-11-10 13:30
Great - thanks for engaging with this process and testing. Marking as closed.

**Closed by peterjc** 2017-11-10 13:30 UTC
