### ISSUE TITLE
Intended return of `Bio.PDB.Atom.Atom.get_full_id`

### ISSUE THREAD

**Issue by bzoracler** [biopython/biopython#3461] opened 2021-01-06 23:39 UTC
It isn't entirely clear what the intended return value of this method is:

https://github.com/biopython/biopython/blob/23b7548dbf1365f2f134695c7007af3f86af5dc0/Bio/PDB/Atom.py#L365-L375

Looking at the commit history,

- The comments have consistently suggested a standard return of a tuple of length 6, while the corresponding code has mostly suggested a tuple of length 5:
    https://github.com/biopython/biopython/pull/2900/files#
- With the `AttributeError` catch, the return is a tuple of length 6:
    https://github.com/biopython/biopython/commit/f951bda7ecbae97955886bb8b0c90ce33d2518d2#
- If `self.parent` has been detached, the standard return is now a tuple of length 2.

### Steps to reproduce

```
>>> # Load a structure
>>> from Bio.PDB.mmtf import MMTFParser
>>> structure = MMTFParser.get_structure_from_url("6LO9")
>>>
>>> # Set a reference to residue and atom object
>>> residue = structure.child_list[0].child_list[0].child_list[0]
>>> atom = residue.child_list[0]
>>> 
>>> # Print full ID of a fully hierarchically connected atom. This results in a tuple of length 5.
>>> print(atom.get_full_id())
('6LO9', 0, 'A', (' ', 265, ' '), ('N', ' '))
>>> 
>>> # Detach the residue from its parent chain, then print full ID of the atom. This results in a tuple of length 2.
>>> residue.detach_parent()
>>> residue._reset_full_id()
>>> print(atom.get_full_id())
((' ', 265, ' '), ('N', ' '))
>>> 
>>> # Detach the atom from its parent residue, then print full ID of the atom. This results in a tuple of length 6.
>>> atom.detach_parent()
>>> print(atom.get_full_id())
(None, None, None, None, 'N', ' ')
```

**Comment by peterjc** [comment] 2021-01-07 13:42
Looks like a duplicate of #2858 but the detached 2-tuple return is another wrinkle. Could you comment there please?

**Closed by peterjc** 2021-01-07 13:42 UTC
