### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Santhi1901** [biopython/biopython#2784] opened 2020-03-05 06:03 UTC
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)
(3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
CPython
Windows-8-6.2.9200-SP0
1.76)

### Expected behaviour

(import NCBIXML from Bio.Blast)

### Actual behaviour

(ImportError: cannot import name '_aligners' from partially initialized module 'Bio.Align' (most likely due to circular import) (C:\Python3.8\biopython-1.76\Bio\Align\__int__.py))

### Steps to reproduce

(from Bio.Blast import NCBIXML)

**Comment by MarkusPiotrowski** [comment] 2020-03-05 07:27
Cannot reproduce this:

```
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on w
in32
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio.Blast import NCBIXML
>>>
```


From the error message, it looks like you run a script `Align_int.py`. Is there something else in this script? Also, the location of your Biopython folder let suggest that you did install Biopython manually from source (i.e. not via `pip install biopython` or something else). Can you give some more details? E.g. if you have installed from source, did you compile the `.c` files?

**Comment by peterjc** [comment] 2020-03-05 11:26
Do not write your scripts in the Biopython source code folder (file ``Align_int.py`` is in ``C:\Python3.8\biopython-1.76\Bio\`` which is likely an unzipped copy of the Biopython source code). If you do this you run into problems like with the C code, and it is not considered a good way to manage your Python code.

Just install Biopython - we recommend ``pip install biopython`` which will download it for you and put the files in the right place, and then you keep your scripts somewhere like ``ProjectX`` under your documents folder?

(I strongly recommend something like a [Software Carpentry ](https://software-carpentry.org/)workshop for an introduction to Python and version control)

**Comment by peterjc** [comment] 2020-10-09 11:41
Closing as no further information provided.

**Closed by peterjc** 2020-10-09 11:41 UTC
