### ISSUE TITLE
UnicodeDecodeError  when reading ABI file with Python 3.6 but not with Python 2.7

### ISSUE THREAD

**Issue by zqfang** [biopython/biopython#1982] opened 2019-03-26 10:55 UTC
### Setup

I am reporting a problem with Biopython version 1.73, Python version 3.6, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-17.7.0-x86_64-i386-64bit
1.73

### Expected behaviour

These code works in python 2:
```python
In [8]: from Bio import SeqIO

In [9]: record = SeqIO.read("./8s11-KO-F1_E08.ab1","abi")

In [10]: record.seq
Out[10]: Seq('NNNNNNNNNNCTCGAGCGCTCGGCGGAGACACTAAGGCGGCCCGGGGCGCGGCG...CAG', IUPACUnambiguousDNA())
```

### Actual behaviour
The same code caused errors in python 3:
```
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-27-79ec5da732f7> in <module>
----> 1 SeqIO.read("./8s11-KO-F1_E08.ab1",format='abi')

~/miniconda/envs/snakeflow/lib/python3.6/site-packages/Bio/SeqIO/__init__.py in read(handle, format, alphabet)
    718     iterator = parse(handle, format, alphabet)
    719     try:
--> 720         first = next(iterator)
    721     except StopIteration:
    722         first = None

~/miniconda/envs/snakeflow/lib/python3.6/site-packages/Bio/SeqIO/__init__.py in parse(handle, format, alphabet)
    653             raise ValueError("Unknown format '%s'" % format)
    654         # This imposes some overhead... wait until we drop Python 2.4 to fix it
--> 655         for r in i:
    656             yield r
    657 

~/miniconda/envs/snakeflow/lib/python3.6/site-packages/Bio/SeqIO/AbiIO.py in AbiIterator(handle, alphabet, trim)
    373 
    374     raw = dict()
--> 375     for tag_name, tag_number, tag_data in _abi_parse_header(header, handle):
    376         key = tag_name + str(tag_number)
    377 

~/miniconda/envs/snakeflow/lib/python3.6/site-packages/Bio/SeqIO/AbiIO.py in _abi_parse_header(header, handle)
    482         data = handle.read(data_size)
    483         yield tag_name, tag_number, \
--> 484             _parse_tag_data(elem_code, elem_num, data)
    485 
    486 

~/miniconda/envs/snakeflow/lib/python3.6/site-packages/Bio/SeqIO/AbiIO.py in _parse_tag_data(elem_code, elem_num, raw_data)
    569             return bool(data)
    570         elif elem_code == 18:
--> 571             return _bytes_to_string(data[1:])
    572         elif elem_code == 19:
    573             return _bytes_to_string(data[:-1])

~/miniconda/envs/snakeflow/lib/python3.6/site-packages/Bio/_py3k/__init__.py in <lambda>(b)
     59     unicode = str
     60 
---> 61     _bytes_to_string = lambda b: b.decode()  # bytes to unicode string
     62     _string_to_bytes = lambda s: s.encode()  # unicode string to bytes
     63 
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 11: invalid continuation byte

### Steps to reproduce
```python
from Bio import SeqIO
record = SeqIO.read("./8s11-KO-F1_E08.ab1", format='abi')
record.seq
```

**Comment by peterjc** [comment] 2019-03-26 12:01
Python 2 does not care about unicode and string encodings, so it just works.

On Python 3, strings are unicode by default, which requires picking an encoding when loading binary data - and evidently the default of UTF-8 does not work here.

It seems there is something unusual in this ABI file. Perhaps it was run on a machine not using English as the system language? This character might (depending on the encoding) mean the character e-acute or example.

Can you share the sample file? In public would be ideal (especially if we could add this as a new test case), but if not by email privately?

CC @bow, original author of the ABI parser.

**Comment by zqfang** [comment] 2019-03-27 02:47
Yes, I believe the abi file contains Non-English words. Please find the test file below. @bow 
By the way, could the abi parser adds a new argument, which could handle non-English characters?  
For example
```python
 SeqIO.read("input.ab1", encoding='gbk')
```


[8s11-KO-F1_E08.zip](https://github.com/biopython/biopython/files/3011267/8s11-KO-F1_E08.zip)

**Comment by peterjc** [comment] 2019-03-27 17:06
Thanks for the example. I can re-produce the problem locally on macOS:

```
$ locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
$ python -c "from Bio import SeqIO; r =SeqIO.read('8s11-KO-F1_E08.ab1', 'abi'); print(r.id, len(r))"
('8s11-KO-F1', 1076)
$ python3 -c "from Bio import SeqIO; r =SeqIO.read('8s11-KO-F1_E08.ab1', 'abi'); print(r.id, len(r))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 720, in read
    first = next(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 655, in parse
    for r in i:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqIO/AbiIO.py", line 375, in AbiIterator
    for tag_name, tag_number, tag_data in _abi_parse_header(header, handle):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqIO/AbiIO.py", line 484, in _abi_parse_header
    _parse_tag_data(elem_code, elem_num, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/SeqIO/AbiIO.py", line 571, in _parse_tag_data
    return _bytes_to_string(data[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Bio/_py3k/__init__.py", line 61, in <lambda>
    _bytes_to_string = lambda b: b.decode()  # bytes to unicode string
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 11: invalid continuation byte
```

I was puzzled for a moment as gbk usually means GenBank (the NCBI file format), but here it is a simplified Chinese encoding: https://en.wikipedia.org/wiki/GBK_(character_encoding)

It might be useful for testing, but what is your system locale?

@bow, do you still have a copy of http://www6.appliedbiosystems.com/support/software_community/ABIF_File_Format.pdf as this URL now redirects to https://www.thermofisher.com and I didn't find it using their search.

I found a copy from 2006 here https://projects.nfstc.org/workshops/resources/literature/ABIF_File_Format.pdf

This does not mention encoding, it does say:

> In addition, two types of strings are supported. The cString type is a C-style string (null terminated). The pString type is a Pascal-style string (the length of the string is stored in the first byte of data). Values stored as pString are required to be less than 256 characters.

**Comment by peterjc** [comment] 2019-03-27 17:34
Looking at the code, I wonder if we could leave the fields as raw bytes as long as possible (meaning if the user wants to work with a raw field, they now get it as raw bytes). If that works for this example will depend on where this problem character is being used...

**Comment by peterjc** [comment] 2019-03-27 18:24
Pull request #1984 would ignore problems tags with a warning.

In this file, the problem is in tag CMNT 1 (sample comment tag), which we do not use directly.

**Comment by zqfang** [comment] 2019-03-28 03:03
@peterjc . In my system:
```
~$ locale                                                                                                              
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by bow** [comment] 2019-03-28 23:45
@zqfang Thanks for reporting this and for sharing a file. Would you mind if we use it for our test suite?

@peterjc I don't have a PDF of the specs and it's unfortunate that they have decided to remove the original one (good that you found a version available elsewhere).

In page 16 of that document, they describe the pString and cString in slightly more detail, and they did mention that the file format expects ASCII string. So the specs seem to formally exclude non-ascii unicode strings here.

In the interest of being more flexible though, what do you think about trying to just parse the bytes as-is, if we can't decode it to string? I played with @zqfang suggestion of adding a unicode argument, but quickly found that different tags may have different encodings. I suppose it is more acceptable here to just return the value as-is.

**Comment by zqfang** [comment] 2019-03-29 03:12
Not mind at all. @bow   
So it works fine as long as we parse the abi file with ASCII.

**Comment by peterjc** [comment] 2019-03-29 09:26
I don't like the idea of sometimes returning a unicode string, and sometimes bytes. Consistently using one or the other makes life easier downstream.

Sticking with ASCII only sounds reasonable (and in line with the standard), and in order that files like this can be parsed, a warning and discarding tags which contain non-ASCII seems a good compromise.

i.e. Even stricter than my quick patch on #1984 which currently does not enforce ASCII?

**Comment by bow** [comment] 2019-03-29 21:43
Hmm..having a consistent return type is preferrable indeed. I'm not so sure about discarding tags, I feel that the parser should preserve as much data as possible.

We could be strict and reject all non-ASCII characters by discarding tags that contain it. It is after all what the specs say.

But perhaps this is also where it is better to follow the Python 2 vs 3 difference. For elements 18 and 19 (pString and cString), we return plain strings in Python 2 and return bytes in Python 3. This would mean some breaking change as currently it's returning strings (bytes) in Python 2 and strings (unicode) in Python 3, but I feel this is acceptable.

**Comment by peterjc** [comment] 2019-03-30 10:34
That's what I was wondering in https://github.com/biopython/biopython/issues/1982#issuecomment-477270587 - for the  'raw' annotations returning bytes seems like a good compromise. Updating the tests will be a bit of a hassle, but probably not too bad.

Note we have to stick to strings for things like the sample name/id/description etc which are standard ``SeqRecord`` properties.

**Comment by bow** [comment] 2019-03-31 22:43
Aha, that does sound preferrable.

For parsing the expected SeqRecord attributes, it boils down to three tags:
* `SMPL1` for `.ab1` and optionally `.fsa` files (used for `SeqRecord.id`).
* `LIMS1` for `.fsa` files (used for `SeqRecord.id`)
* `CTID1` for `.fsa` files (used for `SeqRecord.description`)

`SeqRecord.name` uses the input file name for both file types, so this is fully under the control of the library user, and `SeqRecord.description` for `.ab1` files is set to always be an empty string.

For the three tags above then, should we expose additional `SeqIIO.read` arguments (something like `id_encoding` and `desc_encoding`)? We can set the default value of both arguments to be `utf-8` (or `ascii`, if we really want stricter specs compliance).

**Comment by peterjc** [comment] 2019-04-03 07:57
I wouldn't want to add a top level argument to ``Bio.SeqIO.parse(...)`` etc for the encoding, especially as it isn't even allowed in this file format (and hasn't been suggested/needed for any others).

For these three key fields, I think using we should try using either ASCII (as per the standard) or the system default encoding (being practical - seems a likely match if special characters are used), and issue a warning if that fails - leaving the field blank.

**Comment by bow** [comment] 2019-04-03 10:21
Ok, an ASCII default followed by the system's default encoding, and then defaulting to an empty string sounds sensible.

Looks like a plan for #1984 then :) (in addition to keeping other cString/pString tags as bytes)?

**Comment by peterjc** [comment] 2019-04-03 10:33
Sounds sensible. If you want to work from #1984, great - or start a new branch. Whatever is easier for you.

**Comment by bow** [comment] 2019-04-03 11:20
Great, ok then ~ I'll start working from #1984 and make a new PR.

**Comment by zqfang** [comment] 2019-04-21 04:16
How this is going now? Could I have a worked PR to play with?

**Comment by peterjc** [comment] 2020-05-06 14:09
Can we close this with #2022 merged?

**Comment by bow** [comment] 2020-05-07 09:28
I vote for closing ~ the parser has been updated to address the original issue.

**Comment by peterjc** [comment] 2020-05-07 09:36
Thanks all

**Closed** 2020-05-07 09:36 UTC
