### ISSUE TITLE
Incorrect branch support values after phylogenetic tree rooting

### ISSUE THREAD

**Issue by jhcepas** [biopython/biopython#824] opened 2016-05-17 14:36 UTC
Hi there, 
I have expanded the analysis by Czech and Stamatakis
regarding the [incorrect mapping of support values after tree rooting](http://biorxiv.org/content/early/2015/12/25/035360) in tree viewers, and found that multiple toolkits (including biopython) might also be affected. 

@lczech, @stamatak  and I are now working on reporting/confirming the bug in more frameworks and tree viewers. 

Current tests are here: 
https://github.com/jhcepas/test_branch_support_after_tree_rerooting 

If confirmed in BioPython is it something easy to fix?

**Comment by peterjc** [comment] 2016-05-17 14:49
This is a duplicate of #745, but you have some specific test cases which should help :)

CC @etal

**Closed by peterjc** 2016-05-17 14:49 UTC
